### ISSUE TITLE
ortho function is broken

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#1278]
_Original author: bearmoun...@gmail.com (September 12, 2012 17:01:00)_

1. ortho() works fine
2. ortho(0, width, 0, height) seem to be be misaligned
3. ortho(0, width, 0, height, -10, 10) don't seem to show anything

For any practical use of ortho(...) function you must now be followed up with a call to translate(...) with specific coordinates which depend on the left, right, top, and bottom parameters for the ortho call as well as width and height of your window. This is unpractical.

Reproduce:
void setup() {
    size(800, 600, OPENGL);
}

void draw() {
    float x0 = 124213;
    float x1 = x0 + 512;
    float y0 = 2342;
    float y1 = y0 + 384;
    float tx = width/2 + x0;
    float ty = height/2 - y1;

    ortho(x0, x1, y0, y1);

    translate(tx, ty);

    background(0x234567);
    rect(0, 0, 10, 10);
    line(0, 0, width, height);
    rect(x1-x0, y1-y0, -10, -10);
}

Version 2.0b3 Mac OSX Mountain Lion 10.8.1

note: I have yet to figure out how to get ortho(left,right,bottom,top,far,near) to display anything.

_Original issue: http://code.google.com/p/processing/issues/detail?id=1240_

**Comment by codeanticode** [comment]
I went through the different use cases of the ortho() function, and I realize that my decision of using the upper left corner as the reference point (so ortho() is equivalent to ortho(0, 0, width, height)) is problematic due to two reasons: one, the automatic offset the renderer currently applies so that (0, 0, width, height) corresponds to (-width/2, width/2, -height/2, height/2) only works when the camera is aligned to the z axis. I think it is possible to come up with the correct transformation that would work for any camera orientation, but not 100% sure. Even if we add the correct offset transformation, people will keep coming back to this issue and reporting that (-width/2, width/2, -height/2, height/2) doesn't work, because it is the standard way of defining the orthographic projection

@benfry, @REAS, @shiffman, @alignedleft  I would strongly recommend to go back to the original way of specifying the ortho() arguments, so the default orthographic projection setup is ortho(-width/2, width/2, -height/2, height/2). I will update the examples and reference accordingly.

**Comment by benfry** [comment]
By "original" way do you mean OpenGL? GLU? Processing 1.x?

**Comment by codeanticode** [comment]
1.x, which followed gluOrtho2D() I believe.

**Comment by benfry** [comment]
That sounds like the correct solution. We should just verify that we're following `gluOrtho2D()` properly.

**Comment by codeanticode** [comment]
Yes, actually we should follow [gluOrtho()](https://www.opengl.org/sdk/docs/man2/xhtml/glOrtho.xml), which allows to set near/far planes.

**Comment by yousifucv** [comment]
Hello again, I should have mentioned this earlier, but I think I fixed this issue.

In [PGraphicsOpenGL's ortho(float, float, float, float, float, float) function](https://github.com/processing/processing/blob/c59b92d52ef7f8386fd1985ccc3e437e41495abe/core/src/processing/opengl/PGraphicsOpenGL.java#L4653) there were unnecessary  translations.
There is no need to apply camera translation. Comment out the following lines:

```java
left -= cameraEyeX;
right -= cameraEyeX;
bottom -= cameraEyeY;
top -= cameraEyeY;
```
Going off my previous example, the cube rotates around the centre now, as expected.
```java
void setup() {
  size(1024, 512, P3D);
}

void draw() {
  background(200);

  //cam variables
  float fov = PI / 3;
  float cameraEyeZ = (height / 2) / (tan(fov / 2));
  float angle = (mouseY * 1.0 / height) * 2 * PI; //cam rotation angle around the origin [0, 2*PI]

  camera(
  cameraEyeZ * sin(angle), 0.0, cameraEyeZ * cos(angle), //position
  0.0, 0.0, 0.0, //centre
  0.0, 1.0, 0.0); //up

  //ortho
  float m = 1.0;
  ortho2(-width/2 * m, width/2  * m, -height/2  * m, height/2 * m, cameraEyeZ * 0.10, cameraEyeZ * 100.0);
  stroke(0);
  fill(255);
  box(30, 30, 30);
}

void ortho2(float left, float right, 
float bottom, float top, 
float near, float far) {
  float w = right - left;
  float h = top - bottom;
  float d = far - near;

  //This causes bugs
  // Applying the camera translation (only on x and y, as near and far
  // are given as distances from the viewer)
  //    left   -= cameraEyeX;
  //    right  -= cameraEyeX;
  //    bottom -= cameraEyeY;
  //    top    -= cameraEyeY;
  // Flushing geometry with a different perspective configuration.
  flush();

  float x = +2.0f / w;
  float y = +2.0f / h;
  float z = -2.0f / d;

  float tx = -(right + left) / w;
  float ty = -(top + bottom) / h;
  float tz = -(far + near) / d;

  // The minus sign is needed to invert the Y axis.
  ((PGraphics3D) g).projection.set(x, 0, 0, tx, 
  0, -y, 0, ty, 
  0, 0, z, tz, 
  0, 0, 0, 1);

  ((PGraphics3D) g).updateProjmodelview();
}
```

**Comment by codeanticode** [comment]
@yousifucv yes you are right, thanks for the note! I removed those translations in code I didn't pushed yet. I'm doing some extra testing to make sure that Processing's ortho() is consistent with gluOrtho(), hopefully will be able to close this long-standing issue soon.

**Comment by codeanticode** [comment]
@REAS, @alignedleft  where are the examples stored now so I can update the ones using ortho()? The reference also needs updating.

**Comment by alignedleft** [comment]
@codeanticode Example are under processing-docs/content/examples (although be aware that p5 adaptations are in progress, though that may not apply to 3D examples).  Reference page examples are in processing-docs/content/api_en/ XML files.

If you want to send me specific changes, I can apply them.

**Comment by codeanticode** [comment]
@alignedleft The changes are the following:

* In the Basics|Camera|Orthographic example, the line

```java
ortho(0, width, 0, height, 10, far);
```

should be replaced with

```java
ortho(-width/2, width/2, -height/2, height/2, 10, far);
```

* In the reference page for ortho(), the the example code should have

```java
ortho(width/2, width/2, -height/2, height/2); // same as ortho()
```

instead of

```java
ortho(0, width/2, 0, height); // same as ortho()
```

**Comment by codeanticode** [comment]
@yousifucv if you have the chance to run some tests using the latest revisions from, let me know if you find any other issues with orthographic projection. Thanks a lot!

**Comment by codeanticode** [comment]
@alignedleft I already updated the example and reference.

I no one has any further comments, I will close this issue in the following days.

**Comment by alignedleft** [comment]
@codeanticode I didn't see those edits, so I went ahead and applied them. This should be all set, but I will let you close the issue.

**Comment by codeanticode** [comment]
Hi Scott, sorry I did the chances but forgot to push them :-) And then I pushed a conflicted file :-O but everything is fixed now!

**Comment by felzam** [comment]
Hi guys, while the Examples section of ortho() in the Reference has been correctly updated, the Description section still says that ortho() defaults to ortho(0, width, 0, height).  

Also, the DomeProjection example in examples/Topics/Shaders doesn't work properly in v3.0 because of this change. In the drawDomeMaster() function, the line ortho(0, width, 0, height) should be changed to either ortho() or the same function with the new correct arguments.

**Comment by codeanticode** [comment]
This should be reported in the processing-docs repo:

https://github.com/processing/processing-docs/issues/324
https://github.com/processing/processing-docs/issues/325
