### ISSUE TITLE
Request to add PVector to all graphics methods

### ISSUE THREAD

**Issue by aengelke** [processing/processing#1897]
A `line(PVector,PVector)` method would be helpful. The same for ellipse, rect, etc.

**Comment by benfry** [comment]
Since this has come up again, just an update that there are still no plans to do this.

* As some have noted, this would be hundreds of new methods! We already get many complaints about the “monolithic” size of the `PGraphics` and `PApplet` classes and their API.
* If anything, it may encourage a coding style that makes sketches run a little slower (creating many `PVector` objects, and the dereferencing to get the `x` and `y` coordinates). It's not much but it's not a practice we encourage.
* It's *super easy* to add this yourself. You can even put the methods in a second tab if you don't want them to make a mess of your code. It'd be great if someone who cares about this issue made a version of such a `.pde` file available and posted it for others.
