### ISSUE TITLE
filter(shader) returns result with inverted y

### ISSUE THREAD

**Issue by AmnonOwed** [processing/processing#1988]
When I use the exact same PShader with shader() and filter() they return different results. The shader() result is correct. The filter() result is upside down. The attached PShader should render from top-red to bottom-blue. As the example below shows only shader() gives the expected result.

**test.pde**

``` java
PShader shader;
PGraphics pgShader, pgFilter;

void setup() {
  size(800, 400, P2D);

  shader = loadShader("shader.glsl");

  pgShader = createGraphics(width/2, height, P2D);
  pgShader.beginDraw();
  pgShader.shader(shader);
  pgShader.image(pgShader.get(), 0, 0);
  pgShader.endDraw();

  pgFilter = createGraphics(width/2, height, P2D);
  pgFilter.beginDraw();
  pgFilter.filter(shader);
  pgFilter.endDraw();
}

void draw() {
  background(0);
  image(pgShader, 0, 0);
  image(pgFilter, width/2, 0);
}
```

**shader.glsl**

``` glsl
#define PROCESSING_TEXTURE_SHADER

uniform vec4 color0 = vec4(1.0, 0.0, 0.0, 1.0);
uniform vec4 color1 = vec4(0.0, 0.0, 1.0, 1.0);

varying vec4 vertTexCoord;

void main(void) {
  gl_FragColor = mix(color0, color1, vertTexCoord.y);
}
```

**Comment by neilcsmith-net** [comment]
Just coming up against this in supporting multi-texturing in Praxis LIVE.  There is code in PShader to set up texture matrix and offset for normal usage.  It might be good to extend this so that the PShader can set matrix and offset uniforms for arbitrary PImage (without having to access the underlying Texture)?

eg.
```java
shader.set("sampler", "samplerOffset", "samplerMatrix", myImage);
// OR
shader.set("sampler", myImage);
shader.setOffset("samplerOffset", myImage);
shader.setMatrix("samplerMatrix", myImage);
```
Incidentally, Andres, with regards to the framebuffer / flipped-Y issue, in earlier (non-Processing) GL code I've used "upside-down" FBO's to keep coordinates consistent, only flipping on render to screen.  That's likely a breaking-change for Processing now, which is a shame.
