### ISSUE TITLE
Enhancement wish: Load shader from string

### ISSUE THREAD

**Issue by gregersn** [processing/processing#1999]
I have a wish that I could load a shader from string, instead of just from a file. 

This would make it easier to have generative shaders.

**Comment by cansik** [comment]
So the recommendation is to save the shader file first, and then reload it?

In my opinion, this can be very I/O intensive, if you need to load a lot of shaders.

I have the problem at the moment, that I would like to ship some shaders bundled with my library, because there is no easy way to get the own library path (or is there?!).
