### ISSUE TITLE
rect() with stroke outline renders 1px wider and taller in P2D

### ISSUE THREAD

**Issue by martinleopold** [processing/processing#2065]
This is the output of multiple rect(x,y,3,3) calls rendered with default P2D. 
Black pixels are placed 1px apart to provide a reference. Fill is green, stroke is red.
It seems that the stroke is overlayed starting at the top left corner but extending one extra pixel down and to the right. If this is intended, I wonder what's the reasoning behind it?
![screen shot 2013-09-05 at 22 33 15](https://f.cloud.github.com/assets/1692826/1091702/1c8c0c48-166c-11e3-9951-0a6cf33eb63a.png)

**Comment by JakubValtar** [comment]
Hi!

If the stroke weight is 1 px, 0.5 px would overlap the edge of the rect and 0.5 px would lay outside of the rect (so total width/height of the rectangle increases by 0.5 + 0.5 = 1 px). We move the stroke 0.5 px down and to the right to align in with pixel grid (otherwise it would be in two pixel columns/rows and would be blurred by antialiasing). We do this to make both strokes and shapes appear sharp in P2D.
