### ISSUE TITLE
Exported applications report “this application is damaged”

### ISSUE THREAD

**Issue by medecau** [processing/processing#2095]
An application exported any processing sketch will not open when downloaded from the web. It fails even before prompting the user if it is OK to run the app downloaded from the internet.

I have found this to be hard to replicate as it seems to only happen on some recent MACs.

http://forum.processing.org/topic/help-app-exported-doesn-t-work

**Comment by tomspace** [comment]
This is still an issue in Processing 3.3 - apps exported are flagged as damaged by OSX gatekeeper... 

![screen shot 2017-03-14 at 13 18 13](https://cloud.githubusercontent.com/assets/1330148/23904965/96fb8f3a-08c1-11e7-9324-ef94e6a14e3d.png)

**Comment by EmLR** [comment]
yep. Gave up a while ago :(

**Comment by Reinoudvanlaar** [comment]
I'm also encountering this problem and looking into "manually code-signing" my app as prescribed by the processing export dialogue box. I've made an account at Apple Developer but that's as far as I've got. Any information on the sharing of processing apps under the purview of the Apple Gatekeeper would be much appreciated.

**Comment by Reinoudvanlaar** [comment]
This worked for me so incase it helps anyone else here goes: Manually 'code-signing' seems to require an Apple Developer Program Yearly Membership ($99). Once you've 'enrolled' you can go to your certificates in your account and follow the steps for a new mac osx certificiate - select 'outside appstore' option. It will lead you through a process where you download a keychain. Then in terminal you navigate to your sketch folder "cd ~/Documents/Processing/Sketch/App" and enter "codesign -f -v -s "Developer ID Application: John Doe" Nameofapp.app" (replacing 'Developer ID Application: John Doe' with the 'common name' given in the keychain process & ‘Nameofapp.app' with the name of your app). Then when people download it they'll get the "downloaded from the internet" message but will be able to open it.
(see article about a similar issue with flash http://blog.rustymoyher.com/post/36142106531/signing-apps-without-xcode).
(BTW you need to use absolute paths instead of relative ones if you're loading/saving images etc)

**Comment by benfry** [comment]
Folks, this is a separate issue in macOS Sierra: https://github.com/processing/processing/issues/4705

The original issue was fixed several years ago, that's why the bug has been closed.
