### ISSUE TITLE
dataPath() not working when app is not run from appdir (linux)

### ISSUE THREAD

**Issue by charlesgoyard** [processing/processing#2195]
On Linux with java 1.7 :
When exporting the following code:
```
println("datapath: " + dataPath("somedata"));
```
and running:
```
#correct
cd /home/charles/w/processing/sketchbook/datapathbug/application.linux32
./ datapathbug
datapath: /home/charles/w/processing/sketchbook/datapathbug/application.linux32/data/somedata
# wrong
cd /
/home/charles/w/processing/sketchbook/datapathbug/application.linux32/datapathbug
datapath: /data/somedata
```

I could get a bit closer by doing:
```
import java.net.URL;
URL urlpath = datapathbug.class.getProtectionDomain().getCodeSource().getLocation();
   File filepath = new File(urlpath.getPath());
```
but it returns the application.linux32/lib/databug.jar path. Splitting this string sounds like an ugly hack.

This can be related to issue #2181, but I'm not sure.

A quick fix is to add
```
cd $APPDIR
```
in the shell script generated when exporting while things get sorted out.

Thanks,
Charles

**Comment by benfry** [comment]
Fixed for 3.0 beta 4. 

However, none of those are good reasons to use the data path. It's [not documented](https://processing.org/reference/) and it behaves differently than most people expect. Libraries should use `createInput()` (with a specific path that makes sense for the library's use) and `createOutput()` if they need to read/write files. Maybe it needs to be removed so that there's no confusion. 

If a specific path is needed, `sketchPath()` is a better option. But keep in mind that a sketch may be bundled inside a .app file on OS X, so creating files nearby mean a folder just hanging out inside /Applications, or wherever the .app is located.
