### ISSUE TITLE
Problems with shortcuts on non-US keyboards (ctrl-/ and others)

### ISSUE THREAD

**Issue by designhofmann** [processing/processing#2199]
The keyboard shortcut for Comment/Uncomment ( Cmd + / ) in Processing 2.1 doesn't seem to work on Mac OSX (10.8.5). The menu bar gets highlighted when pressed, but no action is performed on the code. 

When I click manually on the menu item it works fine but not via the shortcut. All other shortcuts work. I can confirm that it worked well in version 2.0.3.

**Comment by kontur** [comment]
This still seems to be an issue. Is there a way to overwrite the shortcut combinations for keyboards that don't have these key combinations available in some configuration file for the user?

For me, too, @designhofmann 's suggestion works and when I press `cmd` + `-` on my Finnish keyboard I get the functionality of `cmd` + `/`, because the keyboard positions seem to coincide - but unless I've typed on foreign keyboard layouts before, there is no way of a user knowing or discovering this.

**Comment by Ghostbird** [comment]
I'm in favour of a way to edit keyboard shortcuts too (just a configuration file is fine). The Redo action is mapped to Ctrl+Y for some reason, which is a hard to grab combo. Most of my software uses Ctrl+Shift+Z, which is a very easy and logical grab for QWERTY keyboards.

**Comment by linco95** [comment]
@Ghostbird ctrl + z is actually pretty standard (not saying that what you are used to is not) way of redoing.
"control-Y is often used to redo actions." (source: "ctrl-y" at wikipedia). Just fyi :)

**Comment by Pablofero** [comment]
Commenting on a spanish keyboard in windows 10 doesen't work in Processing 3.3.5! `/` is inaccesible, in other programs `ctrl+ç` is used. I hope that this problem is adressed, it has been in Processing since ages!

**Comment by DonnyCraft1** [comment]
It's been five years since this issue was opened, and it's still not fixed. The majority of programmers use the US or British keyboard and don't have these problems, but the rest of us still can't use many of the shortcuts... It's time to look into this issue now, so we don't have to deal with these problems anymore.

I'm from Norway, and can't use many of the shortcuts, one of them being the `Comment/Uncomment` shortcut (`ctrl + slash`) because we access slash by typing `shift + 7`. I have tried to use `ctrl + shift + 7` but it does not work.

I hope someone can look into this issue.
Anyways, I love what the open source community can do as a whole. Just look at how long processing has come!

Here's how the norwegian keyboard looks like:
![Norwegian Keyboard](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/KB_Norway.svg/810px-KB_Norway.svg.png)

**Comment by Robomate** [comment]
Same for Germany on Ubuntu 18, really the only short cut which does not seem to work.

I'm from Norway, and can't use many of the shortcuts, one of them being the Comment/Uncomment shortcut (ctrl + slash) because we access slash by typing shift + 7. I have tried to use ctrl + shift + 7 but it does not work.

**Comment by benfry** [comment]
For Processing 3.5, I've done some work to move the problematic key sequences out to the language files, so that they can be localized based on what's best on a locale/keyboard basis. 

More details [here](https://github.com/processing/processing/wiki/Localization#shortcuts-and-key-bindings). Please help us by updating the language files to make use of the feature.
