### ISSUE TITLE
Allow library .jar files to contain version numbers

### ISSUE THREAD

**Issue by kiwistrongis** [processing/processing#2647]
I'd like to be able to package my library(ies) with version numbers in the jar and zip filenames, but the filenames have to match the library name exactly. I'd rather that filenames just had to start with the library name ( eg. library ABCD's jar could be ABCD-1.0.2.jar or ABCDv1.0.2.jar or ABCD.jar or ABCDasdfasdf.jar, etc. ).

I appreciate that this wouldn't make any difference for people that dl their libraries through the processing ui, for everyone else I think it'd be an easy and great improvement. I'll do it myself if you want.

While I've got a moment of your time, is there anywhere I can read about the planned features and release schedule for processing 3?

**Comment by benfry** [comment]
This isn't a great idea because in practice, you'd wind up with multiple versions of the same library installed which would conflict with each other. They're implemented this way for sake of simplicity, and in general our focus is on making the Contribution Manager process as smooth as possible, rather than adding more features for installing libraries by hand.
