### ISSUE TITLE
Use enums for constants.

### ISSUE THREAD

**Issue by aengelke** [processing/processing#2778]
Follow-up of #2761.

**Comment by benfry** [comment]
Closing this one. At the end of the day, we'd have to rename the constants, i.e. `LEFT` would have to become `ALIGN_LEFT` for `textAlign()` and `KEY_LEFT` or key events. Otherwise there wouldn't be a good way to `import static` the enums so we'd have to make people type `TextAlign.LEFT` or something like that. This would both break the simplicity of what we've had there all along, but it would also break the current syntax in a *significant* way due to our use of overlapping constants. Not great, but the tradeoff isn't worth it.
