### ISSUE TITLE
"Your sketch has been modified externally" messages even w/ no changes

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#2852]
Hello, this popup appear often without reason, because there is no external modification.
I think it's when you work on few sketches, and you switch between them and you've write on it.
Some time there's a lot of windows popup open for the same sketch.
P 303 / OSX 10.9.4 / iMac 2012

![capture d ecran 2014-09-10 a 22 15 10](https://cloud.githubusercontent.com/assets/3332269/4224692/510f5cd4-3927-11e4-953c-8e0d4554e032.png)

**Comment by benfry** [comment]
Think I have this fixed for the next release. For some reason, OS X is reporting the files as modified offset by exactly 1000 ms.

**Comment by pvrs12** [comment]
I'm glad you were able to find that exceptionally strange bug. Sorry I wasn't able to keep with this without a mac

**Comment by benfry** [comment]
Totally understand; appreciate your help in the first place.

**Comment by distinctdan** [comment]
I'm seeing this bug on windows with version 3.0.1 on windows 7. When I run my sketch and then close it, processing constantly prompts me if I want to reload until I click "Yes". Clicking "No" only makes the popup immediately reappear. Also, after I click yes, one of my files (tabs) is gone. However, I can recover it by renaming the .tmp file for it. The bug is intermittent, but when it happens it's really annoying and kind of scary. I was afraid I had lost work the first time it happened.

**Comment by distinctdan** [comment]
Update: I did just lose some work on a file. What I had after my last save is gone. This is unacceptable for an IDE. Is there some kind of config setting to turn this off?

**Comment by ichbinscheisse** [comment]
Lost several files within one sketch after getting this message and "reloading" the sketch.
Any help if I mail the sketch to someone?

**Comment by benfry** [comment]
There's a new issue here: https://github.com/processing/processing/issues/3965 that's probably what you're seeing. If not, please file a new bug. The problem reported here has been fixed (even though the symptoms may be similar.
