### ISSUE TITLE
Breakpoints don't work in classes

### ISSUE THREAD

**Issue by REAS** [processing/processing#2946]
From the original post processing/processing-experimental#47

Breakpoints don't seem to work when placed within classes. If I create a breakpoint in a class the debugger never stops. For example, in the following code, if I place a breakpoint inside Ball.display the debugger won't stop (if I place it in the main draw function it does)

```
Ball b;

void setup()
{
  size(300, 300);
  b = new Ball(100, 100);
}


void draw()
{
  b.display();
}

class Ball
{
  int x, y;
  Ball(int _x, int _y)
  {
    this.x = _x;
    this.y = _y;
  }

  void display()
  {
    ellipse(x,y,20,20);
  }
}
```

**Comment by martinleopold** [comment]
I have a fix for this in the old debug mode. Will send a pull request shortly.

**Comment by Manindra29** [comment]
Hi Martin,

That would be great!

Thanks,
Manindra

**Comment by JoshDreamland** [comment]
This bug seems to have fallen between the cracks. It's really hard to debug something when your debugger suggests it isn't running. Anyway, what is breaking, here? Is Processing filtering breakpoints in classes it doesn't recognize, or is it failing to properly set a breakpoint in the generated source for nested classes, at all?

**Comment by pjm56** [comment]
I can confirm this is definitely still an issue in 3.3.
A breakpoint on line 26 of the OP's code (the call to 'ellipse') never gets hit.
I can break at the display call, and "step in" to the class, but never break within a class.
