### ISSUE TITLE
Ready to add contributed example packages?

### ISSUE THREAD

**Issue by shiffman** [processing/processing#2953]
(moving this discussion from e-mail to github).

@prisonerjohn and @joelmoniz we're ready to start adding example packages to the contributions manager.  Looks like this was implemented with https://github.com/processing/processing/pull/2795 and we just need now for an example category in contributions.txt.  Here is my first attempt at making an examples package:

http://shiffman.net/p5/example-packages/natureofcode.txt
http://shiffman.net/p5/example-packages/natureofcode.zip

Also, the window title for the examples should say: "Examples Manager" rather than "Examples-Package Manager".

![screen shot 2014-11-15 at 11 53 02 am](https://cloud.githubusercontent.com/assets/191758/5058810/0b2beb86-6cbe-11e4-8c13-a23d35184e3c.png)

**Comment by shiffman** [comment]
What's the status of this?  I'm ready to work on some example packages as well as put together some documentation (see: https://github.com/processing/processing-docs/issues/173).

**Comment by joelmoniz** [comment]
Examples work well now. But it seems the [contribs.txt](http://download.processing.org/contribs.txt) doesn't contain The Nature of Code examples package any more, although things worked perfectly when it was there some time ago.

**Comment by shiffman** [comment]
I think the issue was that if we add it to `contribs.txt` then previous alphas break.  My question would be does this include a5.  If it breaks a5 then let's wait until a6 is released and add it in.  @prisonerjohn can you shed any light?   Let's make sure we double-check that it works before the next release as it would be great to start getting these packages in there.

**Comment by prisonerjohn** [comment]
Yes, adding any example packages would break previous versions, including a5.

The issue, as detailed in [my comment above](https://github.com/processing/processing/issues/2953#issuecomment-63483130), is that the Contribution Manager will fail if it receives a contribution type other than "library", "tool", "mode", or "examples-package" for any version of Processing released to date. However, ["examples-package" was changed to "examples"](https://github.com/processing/processing/commit/31a186ace3318d20fb88730a58cc95519548b9ab) soon after the a5 release, so adding an "examples" contribution would break all releases out there.

We should definitely wait until a6 is released before adding any "examples" contributions.

Also, I strongly suggest we change the `return` statement [here](https://github.com/processing/processing/blob/master/app/src/processing/app/contrib/ContributionListing.java#L509) to something like a `continue` in order to avoid this problem with future releases.

**Comment by benfry** [comment]
Thanks for the clarification @prisonerjohn. Given that information, I think we release a6 without adding the examples type (since a5 is actually quite 'stable'). Once we know a6 is behaving (or we make fixes and release a7), we can make this change, or we can wait until a future alpha.

**Comment by joelmoniz** [comment]
A possible way out might be to include the new ```examples``` type at the very end of the contributions.txt. That way, as per [this](https://github.com/processing/processing/blob/master/app/src/processing/app/contrib/ContributionListing.java#L509) part of the code @prisonerjohn highlighted, as soon as the ```examples``` tag is encountered, the code would return with list of available contributions, which would be everything except those contributions listed after the first ```examples``` line (which again would be only other examples). I've tested this out, and it seems to be running as expected, without any hiccups. Would this have any possible drawbacks?

As a side note, we could, perhaps, have our cake and eat it too. If we replaced the ```return``` statement @prisonerjohn  highlighted with a continue, and incorporate it into the a6 release, we could have a contributions file as follows:

```
library/tool/mode
<details>
  
library/tool/mode
<details>
  
.
.
.
  
examples-package
<details of example_package_1>
  
examples-package
<details of example_package_2>
  
examples-package
<details of example_package_3>
  
.
.
.
  
examples
<details of example_package_1>
  
examples
<details of example_package_2>
  
examples
<details of example_package_2>
.
.
.
```

This way, since a5 and previous alpha releases worked with the ```examples-package``` type, and since (if this change is incorporated) a6 will be able to skip contribution names it doesn't recognize, listing things in the above order should enable examples to be used in (hopefully) all versions of alpha releases of processing that support examples (irrespective of how they were named), and not affect the contributions listing of any releases of processing before that.

Should I submit a PR with this proposed change?

**Comment by prisonerjohn** [comment]
@joelmoniz  Just to be clear, in your proposed change we would include each example twice in the contribs file, once under the `examples-package` category and once under the `examples` category?

**Comment by joelmoniz** [comment]
Exactly. This isn't the neatest of solutions, but it should work. Are there
any possible drawbacks to this proposal, or some error that might crop up
that I might have missed out?

**Comment by benfry** [comment]
Nah, the alpha releases are truly "alpha" releases. We shouldn't be supporting them or making changes to keep backwards compatibility with them.

**Comment by joelmoniz** [comment]
Ah yes, alright. Would listing examples after tools/libraries/modes be
helpful to prevent breaking 2.0's contribution manager, however?

**Comment by benfry** [comment]
The 2.x contrib manager reads a different file, doesn't it? (To fix this issue, in fact?)

**Comment by prisonerjohn** [comment]
Yes, 2.x uses a different file, mostly to filter out incompatible or pre-included libraries (like video and sound). The issue here really only touches the alpha 3.x releases.

**Comment by joelmoniz** [comment]
Oops, yes. Sorry, it slipped my mind.

**Comment by benfry** [comment]
Ok, I think we're ready to move ahead on this for the new `contribs.txt` used by 3.0. Will the change break 3.0a5? Regardlesss, I think we should move forward with it. We need to move on from a5 and a11 should get us there.

And as mentioned in that other post, it should be `examples` not `examples-package` for all relevant places that a file/tag/whatever is used.

**Comment by shiffman** [comment]
Ok, I have redone my examples package, hopefully correctly.  It's quite possible I made a mistake.  Here are the new URLs for `contribs.txt`.

http://shiffman.net/p5/examples/natureofcode.txt
http://shiffman.net/p5/examples/natureofcode.zip

**Comment by joelmoniz** [comment]
@shiffman : Could you please change the structure to:

```
/natureofcode/examples/chapter1/
/natureofcode/examples/chapter2/
```
etc.
```
/natureofcode/examples.properties/
```

Everything looks perfect once this is done :) :

![image](https://cloud.githubusercontent.com/assets/4526417/8292668/f43f0fee-1941-11e5-9555-0ed604e7b959.png)

**Comment by shiffman** [comment]
changed! (i think).  Let me know if I've done it correctly.

**Comment by joelmoniz** [comment]
Thanks! Looks fantastic :)

**Comment by benfry** [comment]
Cool, Also, `authorList` has now changed to `authors` (though `authorList` still works to keep compatibility)

**Comment by shiffman** [comment]
got it, fixing for whenever i do an update (but won't bother to reupload now)

**Comment by benfry** [comment]
With the PR from @joelmoniz, are we all clear to close this one?

**Comment by shiffman** [comment]
I'm not seeing the nature of code examples show up in 238 (built from source).  I deleted `contribs.txt` and restarted just in case.  Did I miss something?

**Comment by benfry** [comment]
Oh, maybe @prisonerjohn still needs to turn them on in `contribs.txt`.

**Comment by prisonerjohn** [comment]
I do, and will do that today.

On Wednesday, June 24, 2015, Ben Fry <notifications@github.com> wrote:

> Oh, maybe @prisonerjohn <https://github.com/prisonerjohn> still needs to
> turn them on in contribs.txt.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processing/processing/issues/2953#issuecomment-114857654>
> .
>


-- 
--
Elie Zananiri
@prisonerjohn

**Comment by benfry** [comment]
Thanks Elie, that'd be great.

**Comment by prisonerjohn** [comment]
Ok just added Dan's NoC examples and they're showing up in the Contribution Manager. I was able to install the package successfully but it's not showing up in the list. Am I looking in the right place?

![screen shot 2015-06-25 at 8 11 12 pm](https://cloud.githubusercontent.com/assets/119702/8368302/70b6117c-1b76-11e5-8ef1-892721c3508a.png)

**Comment by joelmoniz** [comment]
I think that's because of #3429?

**Comment by shiffman** [comment]
I can confirm that I'm seeing an "error during installation"

![screen shot 2015-06-26 at 6 11 59 am](https://cloud.githubusercontent.com/assets/191758/8371114/4f86010c-1bca-11e5-8ae7-930e3349d9dd.png)

**Comment by alignedleft** [comment]
#3429 has been closed. @Akarshit could you test this? I wonder if something broke with the Examples installer during the process of creating the unified CM window.

**Comment by benfry** [comment]
Where are we on this, folks?

**Comment by shiffman** [comment]
I believe this particular issue can be closed, however there is still #3420 to resolve before I can really test.

**Comment by benfry** [comment]
#3420 is all set, are we done here?

**Comment by shiffman** [comment]
I believe so, yes.  Closing.
