### ISSUE TITLE
background(pImage) costs lots of fps with p3d

### ISSUE THREAD

**Issue by mschi** [processing/processing#3012]
hi,

the following programm runs with only 14 fps. when "background(0,0,0)" is used instead of the image i get 400 fps. dimensions of the image are 1680*1050px. processing 2.2.1 is used.

PImage bg;
 
void setup(){
  size(1680, 1050, P3D);
  smooth(8);
  frameRate(30000);
  
  bg = loadImage("bg.jpg");
}
 
void draw(){
    frame.setTitle(int(frameRate) + " fps");
    background(bg);
}

**Comment by codeanticode** [comment]
@mschi performance of the background(PImage) function in P2D/P3D will be much better in the next release after 3.0a9 due to https://github.com/processing/processing/issues/160. However, it will still be slower than using image() because background(PImage) also copies the pixels of the source image into the pixels of the screen, which can be an expensive operation if resolution is high.

A trick to use image() instead of background() is to disable depth mask, so no object occludes the background image (which is basically a textured quad at z=0):

```java
PImage bg;

void setup() {
  size(displayWidth, displayHeight, P2D);
  smooth(8);
  frameRate(300);
  bg = loadImage("bg.jpg");
}

void draw(){
  hint(DISABLE_DEPTH_MASK);
  image(bg, 0, 0, width, height);
  hint(ENABLE_DEPTH_MASK);  
  
  println(frameRate);
}
```
