### ISSUE TITLE
Use varargs in min() and max()

### ISSUE THREAD

**Issue by colouredmirrorball** [processing/processing#3027]
https://github.com/processing/processing/blob/master/core/src/processing/core/PApplet.java#L3724
I propose using eg max(int... a) in the method header instead of limiting to two or three arguments.

**Comment by clankill3r** [comment]
It is not possible to have

```int max (int... a) {```` next to the current one cause it will make it ambiguous. 

I think replacing the existing one is a bad idea cause the current one is so simple which is fast.
Something like this could be done:

```
int max(int a, int b, int... c) {

  int max = max(a, b);

  if ( c != null) {
    for (int i = 0; i < c.length; i++) {
      max = (c[i] > max) ? c[i] : max;
    }
  }

  return max;
}
```

**Comment by colouredmirrorball** [comment]
Ah, yes, that is a much more elegant idea.

**Comment by datguy** [comment]
I was looking at the code tonight and found another solution:
```
  static public final int max(int a, int b, int... c) {
    int max = max(a, b);
    if ( c != null) {
      max = max(max,max(c));
    }
    return max;
  }
```
In addition to reusing the existing method to find the max value in the array, I love the line with 4 maxes.

**Comment by colouredmirrorball** [comment]
Does that work? Because in general, c would be an array, and the current max method doesn't take arrays as input...

**Comment by clankill3r** [comment]
No it won't work. And even if it did. I still think it's good to avoid the call to the max methodl to save overhead. Although I do not now when java compiles inline.

**Comment by datguy** [comment]
It does work. There is a separate method that accepts an array, and max(c) makes use of that method.

**Comment by datguy** [comment]
I tested the performance of a few variations (using min instead of max, but I expect max to be similar). Your implementation was slightly faster (5ms per 10M operations). Surprisingly, even though my implementation used the existing min(int[]) method, the existing method by itself was slower by 20ms per 10M.

**Comment by GKFX** [comment]
Just out of curiosity, do any of these three changes to @clankill3r 's code help with speed?

````java
int max(int a, int b, int... c) {

  int max = a > b ? a : b; // manual max

  if (c != null) {
    for (int i : c) { //advanced for
      if (i > max) max = i; // don't run "max=max;" when i < max
    }
  }

  return max;
}
````

**Comment by datguy** [comment]
I tried the first and 3rd, but didn't think of the 2nd one. However, the results were inconclusive.  Sometimes it was faster, sometimes it wasn't.  I'm not using a profiling tool, just taking start/stop times for millions of operations, and there are many things the JVM could be doing that interfere with accurate timing.  I didn't think any of the variations made enough of a difference to matter, so IMO it's better to go with the code that is the clearest and most maintainable.

**Comment by datguy** [comment]
So as I mentioned in my last edit, I did further profiling and I was wrong.  The changes proposed by @GKFX  were significantly faster than the other variations, and mine were the slowest.  We're still only talking about a difference of 6 ms per 100k operations, but it adds up.  The other 2 tests (minFrom...) compare the performance of the existing method that accepts an array.  The are for the benefit of @benfry, to show that this change adds value. One creates a new array every time, but it is initialized from an array literal.  The other defines the array once and reuses it for each invocation.

![minprofilewith20](https://cloud.githubusercontent.com/assets/131480/5692343/c1f74a18-98bf-11e4-8255-4d7748c22e9a.png)

@GKFX I'll withdraw my pull request if you would like to submit one to get credit for your suggested changes.

**Comment by GKFX** [comment]
Thanks very much for that work @datguy – I'm preparing a PR now.

**Comment by benfry** [comment]
Someone needs to check whether this is going to change the method signature or otherwise conflict with the existing min/max methods. We can't just change those w/o breaking any library or compiled code that uses min/max already.

**Comment by GKFX** [comment]
Would it be sensible to create,

**Comment by GKFX** [comment]
Would ut be sensible to creat the methods `min(int a, int b, int c, int... d)` instead? I just followed @datguy's lead when making the PR, and it worked, but might it be better to avoid conflicting with the current `min(int,int,int)`?

**Comment by datguy** [comment]
I wrote tests to confirm that the new methods would not interfere with the existing methods.  I did this by modifying the PApplet methods to have them write to System.out (to let me know which method was used). I used this along with the following test class: https://gist.github.com/datguy/a2353668b77a53e1ea82#file-papplettest-java. When 3 or fewer parameters were sent, the existing methods were used.  When 4+ parameters were sent, the new methods were used.

**Comment by benfry** [comment]
@datguy That's not the part of it that needs to be tested. Of course it'll work inside the environment if the function is updated, because the sketch code will be recompiled each time and the core.jar files are using the new methods. The problem is for any library jar that doesn't expect a varargs version of min() and max(), and whether that causes a conflict.

I suspect @GKFX is correct that we'd have to use `min(int a, int b, int c, int... d)` to avoid a collision. However, that's not really how varargs tend to work in practice—if you pass in an array, you want it to behave properly as well (yes, we have array versions that are separate, but...) 

Regardless, someone needs to look into the method signature change and how that affects libraries. 

Or maybe more important, why is this even useful? I can't say that I've ever wanted min or max on more than 3 variables in a single statement—that's what arrays or the XxxxList types are for.

**Comment by colouredmirrorball** [comment]
I opened this issue because I had to determine the maximum of four variables and found it odd the min() and max() values were limited to three parameters.

**Comment by GKFX** [comment]
I'm doing the other test now, so we can check what is actually necessary soon. I doubt that people will try to pass `max(int,int,int[])` very often – I certainly wouldn't call it a requirement that that work (though it's an added bonus if my PR works OK.)

**Comment by GKFX** [comment]
OK, I've test three different `core.jar`s against each other, by compiling the attached Test.java against them, and then attempting to run each of them using each of the three libraries. All 9 tests worked, so we have forward and backward compatibility. I'm using `java-7-openjdk-amd64` on Ubuntu x64 – I can test Sun Java 8 if you think that's necessary.
````java
package processing.test;

import processing.core.PApplet;

public class Test extends PApplet {
  public void setup() {
    size(200, 200);
  }

  public void draw() {
    text(
      min(1, 3) + " " +
      min(1, 3, 5) + " ", 50, 50);
  }
}
````

**Comment by GKFX** [comment]
Sorry, just to clarify the three verions were 2.2.1, latest code, and #3038.

**Comment by clankill3r** [comment]
I think adding the method doesn't make sense.
The proper way would be `int max (int... a) {` which is ambiguous.
Something like `int max(int a, int b, int... c) {` is a cheap workaround.

If I would have an array I need to use `max(arr[0], arr[1], arr);` which doesn't make sense.
Yes it helps if you have to test agains a few values and not an array but still.

**Comment by datguy** [comment]
@clankill3r nobody suggested that we remove the existing methods that accept arrays, so that part of your argument doesn't hold up - you can still call max(arr). 

I will agree that the value of the new methods is debatable. I don't know how often people write sketches that need to compare many values that are not in an array. If that capability is useful, the proposed methods are the way to do it. No, it's not the ideal implantation, but I don't see it as a cheap workaround, I prefer the term "backwards-compatible compromise". If compatibility were not an issue, I would suggest that we replace all of the existing methods with a single varArgs method.

**Comment by colouredmirrorball** [comment]
Purely for academic purpose, why would max(int a, int... b) not be compatible with max(int a, int b, int c)?

**Comment by datguy** [comment]
The methods would be compatible, as long as you could recompile.  The point that @benfry made is the need to be byte-code compatible with existing (already compiled) libraries.  ```max(int a, int... b)``` effectively becomes ```max(int a, int[] b)```, which I would expect to look different in the byte code.

**Comment by GoToLoop** [comment]
If you look into past attempts to make Processing's API better & more flexible, you're gonna reach 1 only conclusion:
Benfry`s almost never accepts any of them! You're wasting your time!

**Comment by datguy** [comment]
@GoToLoop I don't know what kind of history you have with trying to influence change in Processing, but I'm fairly certain that a comment like the one above won't help your cause.

**Comment by GoToLoop** [comment]
Just some examples:

* Chained PVector: https://github.com/processing/processing/issues/257
* A supposed "Potential pull request" for pre-processor directives: https://github.com/processing/processing/issues/2788
* Observe the excuse made to close down every1's hopes above!

And of course some of mine too:

* Got rid of (cast) for object array methods: https://github.com/processing/processing/pull/2903
* signum(float) & signum(int): https://github.com/processing/processing/pull/2894
* int sq() version: https://github.com/processing/processing/pull/2891
* Make undocumented & dangerous delay() static: https://github.com/processing/processing/pull/2890

**Comment by pvrs12** [comment]
@GoToLoop 
* #257 Implemented, but temporarily removed because it broke too much code. Plans to re-add at a later time
* #2788 #include and #define directives can lead to some nasty coding practices and #includes in Java can get complicated fast.
* #2903 The types added are not explicitly supported by Processing so to add them here would imply adding them everywhere, which is a huge mountain of work and potential error
* #2894 Has never been requested before and is very rarely used. Additionally if a developer can't find the docs for their language online they can roll their own trivially
* #2891 No real context for use
* #2890 Changed method signature

Merely because you can find a handful of examples where a feature was not added does not mean that no features are ever added to Processing. It takes a lot of work to write something which is up to par for addition. I'm on my third rewrite of a file change detector for processing because it hasn't been good enough yet. 

If you want to see Processing continue to grow, find an issue with a `help` tag and try to fix or add to Processing by tackling that issue. New features can be added to Processing, they just need to be well thought out and they can't break existing things.

On a completely different note, I don't really see the value in these methods.
If I have many values that I want the max of I would probably just write something like `max(max(max(a,b),c),d)` and the methods for arrays already exist

**Comment by GoToLoop** [comment]
So it's enough for some library needing a simple re-compilation (not modification btW) to bar any API betterment!?
This is very bad & sad! As mentioned, a waste of time this whole discussion! Not gonna be approved!

**Comment by GKFX** [comment]
@GoToLoop As stated above when I was testing, it does not seem to be necessary to recompile. Unless someone has some reason that pre-complied sketches don't work the same way as libraries, the issue is gone.

**Comment by benfry** [comment]
We've now officially spent far too much time on this issue, and we're completely off track. 

To keep the API clean, we shouldn't add `min/max(a, b, c, ...)` since it's just an awkward bandaid on top of the older API that makes the code more cumbersome. The appeal of the varargs option is that we could 1) support the (extremely narrow) use case noted above as well as 2) we could remove the existing min/max variants since they'd no longer be necessary. 

For point 1, it's simply not worth the ugliness in the code and API for such a rare use case. We've had to make thousands of decisions like this over the years, and not everyone agrees, but it's core to keeping things simple.

For point 2, I'm putting this into the PVector/JSON/XML chaining pile. If we do in fact break enough libraries with 3.x with the Applet base class change, we'll do the chaining stuff and we can potentially make this varargs switch as well. The recompile of existing libraries has been a headache for our authors in the past, so we're trying to avoid it.

As @pvrs12 helpfully points out, the way to best help us move the project forward is to find and fix things here in the database. We have tons to do that will impact far, far more people than the ability to add a fourth argument to min or max. Please help!
