### ISSUE TITLE
Finish updating build scripts for Windows and Linux to use Ant Task for downloading JRE

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3059]
While building processing . I am getting the following error ->  
Error getting http://download.processing.org/java/jre-8u31-linux-x64.tar.gz to ....  

I suppose this is because in build.xml this is set -  
\<property name="jdk.update" value="31" /\>
but on http://download.processing.org/java/ only 8u25 is available.

**Comment by benfry** [comment]
Sorry about that... We're changing it over to download directly from Oracle (see the new Ant Task inside the /jre folder) but I haven't finished on wiring that into the Windows/Linux build.

I'm uploading 8u31 copies now so that the build will be usable in the meantime, but I should have it sorted out soon.

**Comment by benfry** [comment]
Now fixed in the current source; there's a new Ant Task in build/jre that handles downloading the JRE directly from Oracle.
