### ISSUE TITLE
Processing does not respond when println-ing text in a for loop

### ISSUE THREAD

**Issue by AlexLardschneider** [processing/processing#3098]
Processing stops responding when I println something in a for-looü used by Netty IO in the Client.

**Comment by AlexLardschneider** [comment]
Well, I just found out it stops responding when the sketch is still running, but it throws no errors.

**Comment by JakubValtar** [comment]
Would you please post your code? It's impossible for us to tell where the problem is without looking at the code.

**Comment by REAS** [comment]
The println() function can be overwhelmed with too much data and that will lock the program. I'll add a note to the reference page: https://processing.org/reference/println_.html

**Comment by AlexLardschneider** [comment]
Yeah, it happens using this method:

for (;;) {
  println(1);
}

just this piece of code will make processing crash

**Comment by JakubValtar** [comment]
This is an infinite loop. It's not a bug, it's expected to crash, because your program will stop here forever printing 1 and can't do anything else unless you kill it.

Could you please post your code to the [Processing forum](http://forum.processing.org/two/)? Folks there will help you make your program work.
