### ISSUE TITLE
Calling textSize() before text() give NullPointer error

### ISSUE THREAD

**Issue by JobLeonard** [processing/processing#3110]
One of my students gave me this code, which kept crashing on the textSize call:

````
void setup(){
  size(900, 900);
}

void draw(){
  background(0, 250, 150);
  fill(250, 20, 20);
  ellipse(mouseX, mouseY, mouseX, mouseY);
  fill(0, 100, 100);
  textSize(mouseX);
  text("hello", mouseX, mouseY);
}
````

Switching text() and textSize() fixes this. Calling textSize() once in setup also fixes this.

Although I understand why it goes wrong, the reference doesn't suggest why - this had my student stumped for a day (and unfairly feeling like he did something wrong, poor lad).

**Comment by poqudrof** [comment]
Hello, 

It seems that is there is a half - bug here. 
The problem is quite simple, you use   **mouseX** to give to textSize().
When the program starts  **mouseX** is set to 0 at some point and passed to textSize. 
Here is a simple fix : 

```
void setup(){
  size(900, 900);
}

void draw(){
  background(0, 250, 150);
  fill(250, 20, 20);
  ellipse(mouseX, mouseY, mouseX, mouseY);
  fill(0, 100, 100);
  if(mouseX>0)
    textSize(mouseX);
  text("hello", mouseX, mouseY);
}
```

A solution would be an warning in the textSize documentation to check that the value passed must be  superior to 0.

**Comment by JobLeonard** [comment]
Well, this does not crash and makes text invisible as expected:

````
textSize(10);
textSize(0);
text("no prob", 5, 5);
````

Wouldn't it make

**Comment by Akarshit** [comment]
The problem is that a font with 0 size can't be created but as the characters are taken as model hence font of 0 size can be drawn.There are 3 ways to handle this  
1. Make changes so that a font of 0 size could be created.  
2. Put checks so that font on 0 size cannot be created and the font's size could not be set to 0.  
3. Make changes so that to create a font of 0 size first a font with some defalt size is created and then its size is set to 0.  
But i would like to hear others view on this .
