### ISSUE TITLE
Feature request: allow users to enable 3.0a4 autocomplete behaviour again

### ISSUE THREAD

**Issue by BlueBoy1987** [processing/processing#3112]
I might be mistaken, but I seem to remember that in an earlier alpha of Processing 3, the auto-complete box popped up by itself (without having to press ctrl-space). Did this change recently?

The only thing that I see in the changelog is "[Change code completion preferences a bit] (https://github.com/processing/processing/blob/master/build/shared/revisions.txt#L43)".

If this is the case - would it be possible to (also) allowing users to switch back to the old behaviour?

**Comment by BlueBoy1987** [comment]
I just checked with the previous (3.0-a4) release.
My recollection was correct. In this version the autocomplete box automatically pops up.

**Comment by benfry** [comment]
You can set `pdex.completion.trigger = true` in preferences.txt to use the old behavior. Our testing found that it was too aggressive and most people found it confusing, so we removed it from the Preferences window.

**Comment by geo7** [comment]
where is this done though? I've just found this post trying to enable autocompletion and It would be nice if you linked 
where to find out about this config file / how to set autocomplete on in Processing seeing as it's not in preferences. 

I can't imagine why the option would be confusing for people - surely having it off as default would have been enough for such 
cases rather than completely removing it? 

Cheers

**Comment by toastbrotch** [comment]
you can activate that inside the file->preferences: "code completion with ctrl+space" (around in the middle)
