### ISSUE TITLE
Cannot rename tabs if the only change is capitalization

### ISSUE THREAD

**Issue by JobLeonard** [processing/processing#3127]
I just did a search, this is a really old bug (feature?) that has been closed without explanation:

https://github.com/processing/processing/issues/1307
(also, that bug was falsely repoted to be a duplicate of this bug)
https://github.com/processing/processing/issues/958

https://github.com/processing/processing/issues/721
https://github.com/processing/processing/issues/32

I'm opening this more as a request to get an official explanation on the matter than as a genuine bug-report.

Say I have a tab called `init` and I want to rename it `Init`. If I try to do this directly, nothing happens. I have to give it a totally different name first, and *then* I can rename it to `init`. This is on Ubuntu, by the way.

Is this due to Windows not playing nicely with the capitalisation of filenames? I vaguely recall an earlier issue I had with loading images that was the result of that.

**Comment by benfry** [comment]
It hasn't been implemented because it's a cross platform mess: OS X is case insensitive but preserving (but sometimes case sensitive, if the FS is formatted that way), Windows is mostly case insensitive (and has other weird DOS 8.3 syntax exceptions), and *nix is case sensitive. I'm not personally interested in writing/maintaining that code, and nobody has implemented a fix. It's an edge case, and the workaround is to rename twice (which is what the code would have to do internally). 

The bug numbers are explained right in the project readme: 

> The issues list has been imported from Google Code, so there are many spurious references amongst them since the numbering changed. Basically, any time you see references to changes made by processing-bugs, it may be somewhat suspect. Over time this will clean itself up as bugs are fixed and new issues are added from within Github. Help speed this process along by helping us!

**Comment by Akarshit** [comment]
Yes this was left becuase of the different behaviour of various OS with case-sentivity  
https://github.com/processing/processing/blob/master/app/src/processing/app/Sketch.java#L437  
Further problem is that the behaviour not only specific to OS because there are different version of the same OS available which are case-sensitive and case-insensitive.  So i think it would be best if this behaviour is left as is.

**Comment by Akarshit** [comment]
@benfry So do you want the workaround to be implemented ?

**Comment by JobLeonard** [comment]
@benfry Thanks for clarifying :). Sounds like a proper mess indeed.
