### ISSUE TITLE
Install/Remove button in Mode/Library/Tool managers not working in the current source

### ISSUE THREAD

**Issue by REAS** [processing/processing#3172]
OS X 10.8.5, running from source. 

The install button is there and it highlights on rollover, but there is no action when it's pressed.

**Comment by benfry** [comment]
@joelmoniz any thoughts on what's happening here?

**Comment by Plastix** [comment]
I am replicating this on OSX 10.10 and running latest commit from master. Will investigate.

**Comment by Plastix** [comment]
I figured out that you have to click the install/remove button (so it is selected) and press space to actually send the click event. No idea why...

**Comment by joelmoniz** [comment]
@benfry
Terribly sorry. I'm afraid I've not yet been able to look into this, since
I've had loads of work at school this last week. Will definitely be able to
look into this tomorrow.

On a side note, based on @Plastix 's tests, might this be related to #3079?
@Plastix could you please let me know if double clicking the install/remove
button enables installation/removal?

Thanks!

**Comment by Plastix** [comment]
@joelmoniz No matter how many times I click the buttons it doesn't install/remove the library. The only way I've found is to click the button to select it and press space. Code is all over the place in `ContributionPanel.java` and it is hard to tell what is going wrong.

Here is a gif: 
![test](https://cloud.githubusercontent.com/assets/1526881/6994385/8f79a712-dae5-11e4-9935-3fff8c6b8918.gif)

**Comment by joelmoniz** [comment]
Oh wow. Thanks a bunch. Probably related to #3079, but definitely not a
duplicate, since the behavior on Windows isn't like this at all, although
I'm fairly certain that the same bug in the Contributions Manager is at the
root of both these issues. I shall definitely have a look at this asap.

Thanks again.
