### ISSUE TITLE
Support the full SVG style spec

### ISSUE THREAD

**Issue by vitorgalvao** [processing/processing#3179]
Refs #3150.

In that issue, an SVG was not being displayed correctly by Processing and the root cause was found out to be [a specific style rule](https://github.com/processing/processing/issues/3150#issuecomment-89695705). Supporting the full spec would be highly desirable, since SVG is the way to go when dealing with vectors in Processing.

**Comment by benfry** [comment]
Ha, sounds so simple! Supporting all of the SVG spec is an *enormous* feature request. The code for Batik, a full SVG implementation, is several times larger than the entire codebase for all of processing.core. We try to support as much of the frequently used features as we can, without reinventing the wheel. See here:
http://processing.org/reference/javadoc/core/processing/core/PShapeSVG.html

That being said, the best way to resolve this issue would be for someone to build a full-featured Processing-compatible layer on top of something like Batik. By that I mean that it works with OpenGL and PDF renderers, not just the default Java2D renderer (i.e. when rendering it calls Processing methods to draw shapes to the screen).

Once implemented, I'd happily provide the internal changes to `PApplet` that would make it use the new library for `loadShape()` when it was present/available, but not increase the core several-fold by adding the entire Batik library to processing.core for all users.

**Comment by vitorgalvao** [comment]
By no means did I meant to imply it would be easy. My goal with opening the issue was as a way of tracking its progress and recognising the desire for the feature (since I did not find another issue for this). I was also expecting to learn a bit more of the current limitations with its implementation, and that you provided plenty of; way more then I was expecting. Thank you for taking the time to explain it in such detail.

**Comment by poqudrof** [comment]
Hello, I had a look into this issue for quite some time. Integrating Batik looks much more difficult than rewriting a SVG player in Processing and OpenGL.
If you want "better support", you can have a look in my [Processing fork](https://github.com/poqudrof/processing/releases/tag/2.2.1-svg). It supports the images as links in the SVG and embedded. I compiled it for Linux only, you can replace your core.jar by the one in the archive to make it work on other architectures.  

As the current Processing rendering engine is... not very quick (at last much slower than 1.5.1 and GLGraphics), and it seems in heavy development, I did not have look to reimplement the SVG rendering. I want to do this because SVG are awesome, and I work on a presentation software which is based on [Sozi](https://github.com/senshu/Sozi) for the SVGs and Ruby-Processing for the rendering, it is called [Soby](https://github.com/poqudrof/Soby). I will have a look into the dev of the rendering engine of Processing 3 to see if it would be easier to do now. 

Jeremy.

**Comment by benfry** [comment]
Rolling these requests into https://github.com/processing/processing/issues/5935
