### ISSUE TITLE
Should there be a maximum RAM usage slider in preferences?

### ISSUE THREAD

**Issue by jgall** [processing/processing#3181]
Wanted to start by saying how awesome Processing is and how useful it has been to me. 

I would like to offer to implement a logarithmic based slider into the preferences that would update the value in the text field, making it more intuitive for users to control their RAM usage. In the preferences of Processing the maximum RAM is controlled with a JTexField only; I'll try offering both side by side, having them update each other's values. 
It is useful to include a slider when dealing with maximum memory adjustments in programs -- sliders give a maximum and minimum preference, allowing for context when making a decision. 

If anyone thinks that there is a want/need for this, I'd be happy to implement it.

**Comment by benfry** [comment]
It's a great idea, and an obvious UX thing, but we haven't done it because it's just not possible. It changes over the course of time (i.e. how many applications you have open, or sketch windows for that matter) and there isn't a good definition of what's really "available" RAM. It's also a bit confusing because the upper bound amount, depending on your OS, might be a number like 50% more than the amount of RAM you actually have installed (because of how virtual memory works). It's just a really unfortunate situation with how memory is handled in Java. To be sure, I don't like directing people to our long explanation about Out Of Memory Errors: https://github.com/processing/processing/wiki/Troubleshooting
