### ISSUE TITLE
add variable/constants for processing implementation (js, android, desktop, etc)

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#320]
_Original author: fjen...@gmail.com (June 27, 2010 09:16:11)_

With the increasing number of implementations it would be really handy to add a flag for the environment to the API similar to &quot;online&quot;.

_Original issue: http://code.google.com/p/processing/issues/detail?id=281_

**Comment by benfry** [comment]
Closing this, since we're moving away from the syntax being so similar as different languages are used. p5js is our focus instead of processing.js, and that's not identical code. Android and desktop versions of Java are different enough that we're not just talking about a single implementation variable being the only different between the two.
