### ISSUE TITLE
Export DXF dosen't work correctly with bezier()

### ISSUE THREAD

**Issue by yshahin** [processing/processing#3228]
I have a script that generates a pattern and I use the bezier() method, when exporting from processing to dxf format the file is generated but the output has a lot of extra triangles as if it was using them to generate the curve.
The curve is there and looks good but the extra lines seem like they need to be removed.

Any ideas?
![screen shot 2015-04-29 at 12 59 59 am](https://cloud.githubusercontent.com/assets/207449/7382108/41e8ba36-ee0b-11e4-9cc4-7c6a995f8038.png)
![screen shot 2015-04-29 at 1 01 05 am](https://cloud.githubusercontent.com/assets/207449/7382111/4c106914-ee0b-11e4-993f-256430c9ca0f.png)

**Comment by benfry** [comment]
Please use forum.processing.org for questions.

**Comment by yshahin** [comment]
@benfry this is a bug not a question

**Comment by REAS** [comment]
I think Ben's point is that the DXF library is behaving according to its specification. It reduces everything to triangles and lines, so that's what happens with a bezier(). I think you will need to use bezierPoint() to pre-compute a series of lines that are compatible with the DXF library. If that's not clear, that is the kind of question that is appropriate for the Forum. The issues reported on GitHub are many and time is short, so sometimes replies are terse by necessity.

**Comment by yshahin** [comment]
Thank you very much for the clarification
