### ISSUE TITLE
Debugger "step"

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3266]
When the debugger is active and I'm stopped at a breakpoint, my expectation is as follows:

1. "continue" will advance the code until the next breakpoint.
2. "step" will move the code line by line (as if there is a breakpoint at each line.)

1 works as expected.  2 works, however, as soon as the debugger cycles back to the beginning of `draw()` it no longer steps, but rather continues.  Here is what I am using to test:

```
float x = 0;

void setup() {
}

void draw() {
  println("test0");
  println("test1");
  x = x +  1;    // ***** breakpoint is here ***** //
  println("test2");
  println("test3");
}
```

"step" will advance line by line through ` println("test2");` and `println("test3");` but then jump again to `x = x + 1` without stopping at `println("test0");` or `println("test1");`

**Comment by benfry** [comment]
Hm, on closer look, I think this might be in line with how "step" works in a debugger. When you hit the end of `draw()`, you're stepping out of the function (otherwise we'd be dropping you into a bunch of `PApplet` arcana), and there's no way for a debugger to know that `draw()` is your function of interest and you want to go back to stepping there. 

Put another way, to the debugger, `draw()` is like a different function each time. The way you signal that you're always interested in `draw()` is to put a breakpoint at the beginning of it.

Does that make sense?

**Comment by shiffman** [comment]
Yes, I completely understand.  Linking this to https://github.com/processing/processing-docs/issues/211 so I remember this when I write tutorial.  Closing.
