### ISSUE TITLE
Localize MovieMaker.java

### ISSUE THREAD

**Issue by GKFX** [processing/processing#3289]
I'm currently updating `MovieMaker.java` to the latest version of the Monte Media library, but in the course of that I've internationalized the code so it's now ready to translate.
The English version of `PDE.properties` is at https://github.com/GKFX/processing/blob/404d6dfc9c548f85175c6d77bab341460f16f3a1/build/shared/lib/languages/PDE.properties – please could someone(s) produce foreign language versions of that and submit pull requests? (I'm not sure if it's proper protocol to ask people to build on a commit that's not been submitted, but the strings aren't going to change, so it doesn't seem to matter.)
- [x] English
- [ ] German
- [ ] Greek
- [ ] Spanish
- [ ] French
- [ ] Japanese
- [ ] Korean
- [ ] Dutch
- [ ] Portuguese
- [ ] Turkish
- [ ] Chinese

**Comment by benfry** [comment]
Let's not go this route, since it leaves an issue filed here for something that's not finished, in your own repo (that we don't control), and that will likely never be resolved (because it's highly unlikely that each translator will find this item). 

When a translation doesn't exist, the English version is used. We just have to wait for the other translations to catch up. But we also can't do that until this updated MovieMaker code is actually submitted and checked in.

**Comment by GKFX** [comment]
OK, cool.
