### ISSUE TITLE
sketch window briefly appears on the top left corner when using OpenGL renderers

### ISSUE THREAD

**Issue by codeanticode** [processing/processing#3308]
When starting a sketch in 3.0a9, the output window briefly appears (less than a sec) on the top left corner of the screen, to be then placed at the correct location. This properly due to an incorrect initial position values for the GLWIndow.

**Comment by monkstone** [comment]
Similar spooky thing on linux, window appears briefly on right of ide, then switches left of ide (on my fairly wide screen).

**Comment by aengelke** [comment]
This also happens with also with JAVA2D on Linux.

**Comment by codeanticode** [comment]
@benfry this could be solved in the case of the GL renderer if surface.startThread() is called at the end runSketchEDT(), and only then making the window visible. In this way, it is never visible while it has its initial default location. However, for that to work I had to comment out the while (sketch.defaultSize && !sketch.finished) loop, which I'm not entirely sure if it is still needed after all the changes in the renderer's architecture. Didn't seem to have an effect on the GL renderers.

**Comment by benfry** [comment]
At the moment, that loop exists as a convenience to not show a window until `setup()` (the first frame) has finished. If that method takes a while, and we show the window before it's done, we run the risk of a blank window until the first frame is complete.

In Java2D it's working (in a10), but how can we get around these issues for OpenGL? Even if we need to show the frame for GL so that it has a rendering surface, we shouldn't cripple Java2D by making it open a blank window.

**Comment by codeanticode** [comment]
fixed with https://github.com/processing/processing/commit/8707194f003444a9fb8e00bffa2893ef0c2492c6

**Comment by benfry** [comment]
That's great news.
