### ISSUE TITLE
If I wrote a "Run Processing Headless" how likely is it to be merged?

### ISSUE THREAD

**Issue by sirhcsenots** [processing/processing#3323]
I'm building various webapps and I need to render the sketches server side. 
It is currently not possible since Processing rightfully expects to be hooked up to a monitor etc.
However, if I added this feature to processing what is the likeliness that my pull request would be merged back to master? 

I'm aware there are alternative ways to accomplish this (Xvfb) but I can not install that on the the paid hosting service I use. Hence, my debate over whether to program this or not.

**Comment by pvrs12** [comment]
You might try editing the various config files which build the processing executable to add this option `-Djava.awt.headless=true`. This should 'ideally' set the output to be headless. I haven't had any luck so far though.

**Comment by benfry** [comment]
Unlikely to be merged. It's an absolutely enormous change, and just not something that I can support over the long-term in my spare time. 

https://github.com/processing/processing/wiki/Running-without-a-Display

Your time would be better spent getting something like Xvfb to work statically, so that you don't need root permissions to use it.
