### ISSUE TITLE
Trig issue/Unit circle Maths versus Processing

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#336]
_Original author: i.o.mari...@gmail.com (July 04, 2010 19:23:42)_

Not sure, where else should I post my question/doubt.

In trigonometry we use the Unit circle: 90 degrees - Pi/2 on the top, and 270 degrees = 3Pi/2.
(quick reference http://en.wikipedia.org/wiki/File:Unit_circle_angles.svg)

In Processing it seems that the Unit circle is set other way round (it goes clockwise, thus 90 is set in the bottom and 270 degrees in the top, ).

That is clear using the arc() function as well as sin() and cos().

I don't understand why and if that is intentional or a bug.

_Original issue: http://code.google.com/p/processing/issues/detail?id=297_

**Comment by LightAtPlay** [comment]
To clarify here, we need to make a distinction between the mathematical operators and the drawing canvas. The math operations in processing work correctly, if you calculate sin(PI/2), you'll get 1, just like you expect. Try

    void init() {
      print(sin(PI/2));
    }

to see this.

The issue comes from the canvas on to which you're drawing. In most raster computer graphics, the upper left pixel of the display is considered the display and is given the coordinates [0,0]. For a display with width and height, the lower right pixel of the screen is given coordinates [width-1, height-1]. This applies to not only to the screen itself, but to most raster drawing APIs, including the ones that Processing uses internally.

That there is no quadrant in the cartesian plane that behaves like this. What we have is essentially quadrant 1, but with the Y axis flipped. A larger Y value goes down, while a larger X value goes right. You must correct for this when computing coordinates. One easy way is to simply flip the processing space along the Y axis with

    translate(0, height);
    scale(1, -1);

at the beginning of your draw() function. Now the lower /left/ corner of the screen is at (0,0), and everything will work as expected.

This ultimately comes down to which set of conventions are being used by processing. The designers could have chosen to flip the coordinate space by default (or do some other mapping like maping [0,0] the center of the screen). Doing so would have  alienated anyone used to working with computer graphics libraries. Going the other way, as they did, confuses people familiar with traditional graphing. 

The advantage, in my opinion, of going the route they chose is that when people move from processing to other graphics environments (Java graphics, Javascript canvas, SVG, etc...) they will not have to relearn the coordinate space. I would love to see, however, functions built into processing to change the coordinate space explicitly. Something like setCoordinateSpace(CARTESIAN_QUADRANT_1, 200, 200) or CARTESIAN_ALL_QUADRANTS.

I apologize if I used any terminology incorrectly, I'm a computer graphics guy, not a math guy.
