### ISSUE TITLE
How do images behave when pixelDensity(2) is set?

### ISSUE THREAD

**Issue by REAS** [processing/processing#3364]
See processing/processing#3361

Essentially, does the behavior of `get()`, `set()`, `copy()`, `blend()`, and `pixels[]` change when `pixelDensity(2)` is run in `setup()` or does another function get added to adjust image functions to the High-DPI world?

*Do we add a function like `imageDensity()`?
*Does this affect more than `get()`, `set()`, `copy()`, `blend()`, and `pixels[]`?

I think it's best for pre-3.0 code to behave like it did before when `pixelsDensity(2)` is set but I'm flipping and flopping at the moment.

**Comment by benfry** [comment]
My general thoughts are as follows:
* Images load and may look a little ugly since `image()` draws them at the same on-screen size whether retina or not. This looks fuzzier on retina if it's not a high-res image. But this preserves the same code across different screens.
* The easiest way to support retina is to load images that are 2x the size, and they'll just be scaled down for 1x situations. So long as you use `image(x, y, w ,h)` instead of `image(x, y)`, you're fine.

Separately, we could do something to automatically load 2x versions of images that are different. i.e. `loadImage()` detects pixel density of your renderer, and checks for a (specially named) 2x version of your image. This is what most apps do (say on OS X) with a weird `@2x` suffix in the image name. I find this a really hokey solution, and don't like the idea of messing with `loadImage()` parameters this way. If you *might* be using retina, I don't know why one wouldn't always include a larger image (we're not talking bandwidth here) and just have it scale when drawn (since most of the time, the image is scaled while drawing anyway).

**Comment by shiffman** [comment]
> The easiest way to support retina is to load images that are 2x the size, and they'll just be scaled down for 1x situations. So long as you use `image(x, y, w ,h)` instead of `image(x, y)`, you're fine.

This makes sense to me and I think is the right place to start.  I don't think we should try to have an automatic magic naming / loading system.  I'm not against the idea of a library to help manage auto-retina image loading, but I don't think we want it in core.

This solves it in my head for `image()`, `get()`, `set()`, `copy()`, `blend()`, however, I am completely confused as to what happens here:

```
size(200, 200);
pixelDensity(2);  // What world of madness am I entering?
loadPixels();
for (int x = 0; x < width; x++ ) {  // Is width 200 or 400, it's 200 right?
  for (int y = 0; y < height; y++ ) {
    int index = x + y * width;    // Ok, but now I want to look at 400*400 pixels
    pixels[loc] = color(random(255));  // But then  what pixel am I setting, am I setting 4 pixels?     
}
updatePixels();
```

Is the right way to do this:

```
int density = 2;
size(200, 200);
pixelDensity(density); 
loadPixels();
for (int x = 0; x < width * density; x++ ) { 
  for (int y = 0; y < height * density; y++ ) {
    int index = x + y * width * density;   // Blegh
    pixels[loc] = color(random(255));
  }
}
updatePixels();
```

Or now I have some memory or a built in variable like `pixelFactor` or `getDensity()` discussion?i  I had an insane thought where we could handle this in `loadPixels()`, like `loadPixels("2X")`.  @benfry is sure to love that one!

**Comment by benfry** [comment]
`width` and `height` stay the same, so that all non-pixel operations work. 

For pixel operations, there are three variables: `pixelWidth`, `pixelHeight`, and `pixelDensity`. So the code changes to:
```
size(200, 200);
pixelDensity(2);  // I heard about this thing that makes my code awesome
loadPixels();
for (int x = 0; x < pixelWidth; x++ ) {  // pixelWidth is 400, but width is still 200
  for (int y = 0; y < pixelHeight; y++ ) {
    int index = x + y * pixelWidth;    // you're using 400x400 pixels
    pixels[loc] = color(random(255));  // setting a single pixel, one of the 400*400
}
updatePixels();
```

**Comment by benfry** [comment]
...but now I realize this is all folly, and I should have used `loadPixels("2X")` or `ploadPPixels("P2X")`.

**Comment by shiffman** [comment]
Ah, perfect, thanks for rehashing this again, I needed to hear about this again for it to all make sense.

Just to make sure I've really got it, let's say you forget to deal with `pixelWidth`, etc.

```
size(200, 200);
pixelDensity(2);

// Oops, I left in old code that doesn't account for pixelDensity
loadPixels();
for (int x = 0; x < width; x++ ) {  
  for (int y = 0; y < height; y++ ) {
    int index = x + y * width; 
    pixels[index] = color(random(255)); 
  }
}
updatePixels();
```

The result will be:

![screenshot 2015-06-08 22 23 16](https://cloud.githubusercontent.com/assets/191758/8045724/33d9ea40-0e2d-11e5-88b9-a317d69fec79.png)

And just like `smooth()`, `pixelDensity()` can only be called once in `setup()` so it's not possible to mix and use `pixelDensity(2)` for drawing but `pixelDensity(1)` for pixel operations?

```
// Invalid!  pixelDensity has to be in setup and can't change!
void draw() {
  pixelDensity(1);
  // do my pixel operations the old fashioned way
  pixelDensity(2);
  // Now fancy hIrEz drawing!
}
```

Am I right?  I think I've got it in my head now.

**Comment by alignedleft** [comment]
Do we want to be able to switch `pixelDensity()` in `draw()`? I thought the idea was for it to be set once in `setup()` and not change.

The web world now differentiates between "display pixels" (used for rendering) and "CSS pixels" (used for measurement.  To clarify, I understand that `width` and `height` and all the existing terminology would represent pixels for measurement purposes, and (on hi-dpi displays) screen pixels.  These new values, 
`pixelWidth`, `pixelHeight`, and `pixelDensity` would only apply as "display pixels" and are only relevant on hi-dpi displays.

**Comment by shiffman** [comment]
@alignedleft yes that is correct, set once in `setup()` and not change.  Apologies if my note was misleading, I was providing ***incorrect*** code to understand what we cannot do.

**Comment by benfry** [comment]
Right, so we don't want to change it, because it also affects the rendering surface. This is the issue I'm referring to [here](https://github.com/processing/processing/issues/3361#issuecomment-109949617) as far as splitting 1) the way that the rendering surface draws with 2) the handling of pixel operations. 

Originally, they were separate, and we had `PGraphicsRetina2D` as the renderer and then `hint(ENABLE_RETINA_PIXELS)` (or even `hint(DISABLE_RETINA_PIXELS)`), but I think it was super confusing, not to mention a nightmare to maintain.

**Comment by benfry** [comment]
Are we all set here? I'm not sure if there's anything that needs to change from our current setup, without causing more problems than it solves. 

I think the one change would be to add the ability to call `pixelDensity(2)` on an image, which would make a 200x200 pixel source image into an image that had width/height 100x100 and pixelWidth/pixelHeight of 200x200, and then draw things accordingly. But even that seems like another quirk for the renderers to support (what happens when the source image has odd (not even) numbers for the width/height? how do we make sure this is covered in all renderers?), when the general fix is to simply use images that are larger than necessary, and always specify a width and height when using the `image()` method.

**Comment by REAS** [comment]
Yes, I think. To clarify, we will document `pixelWidth`, `pixelHeight`, and `pixelDensity` as Processing variables, like `width` and `height`

**Comment by shiffman** [comment]
re: your question about `pixelDensity(2)` on an image I think we haven't had enough (any really) user testing of how these new concepts and capabilities will affect users so we should keep it as simple as possible and add only the global methods / variables.

**Comment by benfry** [comment]
Yeah, I think we just leave things unchanged until we hear calls for a real API to cover a specific use case. I don't see anything useful to be done here that doesn't create more problems than it preemptively tries to solve.

**Comment by shiffman** [comment]
Agreed!
