### ISSUE TITLE
implement better way to select GL profile

### ISSUE THREAD

**Issue by codeanticode** [processing/processing#3382]
Right now, a GL profile can be set by using the static field PGL.profile like so:

```java

{ PJOGL.PROFILE = 4; }

PImage heightMap;
GL4Shader terrainShader;
GL4Shader edgesShader;
PShape grid;
Scene scene;

void setup() { 
  size(640, 360, P3D);
  ...
```

(see [this sketch](https://github.com/codeanticode/pshader-experiments/blob/master/TerrainTess/TerrainTess.pde) for a complete example). This is obviously not a good solution, and although setting the GL profile is a feature only of interest to advanced users, the focus given to full-screen desktop applications in Processing 3, make the use of newer GL profiles (3, 4+)  a very relevant feature.

**Comment by benfry** [comment]
Let's not use the `{ PJOGL.PROFILE = 4; }` syntax anywhere public. It's absolutely dreadful form. 

If this has to be done, write a custom `settings()` method and call it from there (and in doing so, move `size()` and the other methods that are automatically moved into `settings()` there as well). 

Since it's for advanced users anyway, they can start understanding the way that `settings()` works.

**Comment by codeanticode** [comment]
fixed with https://github.com/processing/processing/commit/445cb17ff76c2018e556410fddb28e695b93a583
