### ISSUE TITLE
NullPointerException in Demos > Graphics > Planets

### ISSUE THREAD

**Issue by ewelinka** [processing/processing#3551]
I

**Comment by ewelinka** [comment]
I just installed Processing 3 and tried to run Planets example (File->Examples->Demos->Graphic->Planets) and got NullPointerException in the line 113 of Planet.pde:   

shape(planet2);

**Comment by benfry** [comment]
Working fine here. What system are you running? (Mac/Windows/Linux? 32- or 64-bit?)

**Comment by ewelinka** [comment]
Mac Yosemite

**Comment by ewelinka** [comment]
64 bits

**Comment by codeanticode** [comment]
I'm getting the NPE in beta1, but working fine after the [latest fixes](https://github.com/processing/processing/commit/974d9a58d9bbc8269656666462c589a3e8489c23) from @JakubValtar. I think we can close it, but we can double check that there is nothing serious behind it.

**Comment by benfry** [comment]
Sounds good to me. I think I might do a beta 2 this morning to get a few of these out.

**Comment by codeanticode** [comment]
Ben is getting NPE, on a 4K retina machine, so reopening it.

**Comment by JakubValtar** [comment]
If you are building processing from the source, please make sure that all the shaders in `processing/opengl/shaders` on your machine have the same filenames as in the main repository. It turns out that on Ben's machine one of the shader files had lowercase L (`Texlightxxx`) in the name instead of uppercase one (`TexLightxxx`) which was used in the code.
