### ISSUE TITLE
Should printArray() work with ArrayLists?

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3587]
This code:

```java
String[] test1 = {"one", "two", "three"};

ArrayList<String> test2 = new ArrayList<String>();
test2.add("one");
test2.add("two");
test2.add("three");

printArray(test1);
printArray(test2);
```

yields:

```
[0] "one"
[1] "two"
[2] "three"
[one, two, three]
```

Should `printArray()` work with an `ArrayList` like with an array?  I expected it to, but not sure if this change introduces too much complexity behind the scenes.

**Comment by benfry** [comment]
Easy enough to add, but this code should be using `StringList` and its `print()` method. The only cases where people should use `HashMap` or `ArrayList` are when they want to use objects that aren't `int`, `float`, or `String`. 

If we add it, it should be `printList()`, however, since `xxxxArray` methods only work on `[]` arrays everywhere else in the API.

**Comment by shiffman** [comment]
Yes, I just made this as a quick test to confirm behavior, the example I'm working on uses an `ArrayList` of `File` objects.  I think this is pretty edge case, let's skip it esp. given we've got it covered for the more common `XXXList` objects.
