### ISSUE TITLE
Horizontal scrollbar does not scroll textarea all the way

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#3591]
1. Create new sketch
2. Write a line wider than the window
3. Grab horizontal scrollbar and scroll all the way to the left an to the right
4. There are still hidden characters on the right. Selecting the text by mouse scrolls it to the limit.

Windows 8.1

**Comment by joshgiesbrecht** [comment]
Looking into this today.

**Comment by benfry** [comment]
Thanks Josh!

**Comment by joshgiesbrecht** [comment]
Leaving a note to myself / whoever re: an almost-certainly-related bug: if you c&p this into an empty sketch:

////// wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww

and then hit 'Home', it does not quite scroll all the way to the very left and gets stuck in a weird state until you use the mouse on the horizontal scroll bar.  (On my machine, with I think? default font and window sizes. the 2nd line is just a bit wider than the text area.)

Currently poking around in system/JEditTextArea.java and figuring things out.

**Comment by joshgiesbrecht** [comment]
Leaving a note again since quiet concentration time has been getting rarer:
My current suspicion is that updateScrollBars() inherited from JEditTextArea isn't playing well with the pdex textarea class because of the extra line number stuff on the left.

**Comment by joshgiesbrecht** [comment]
Found time again!

The 'extent' used for the scroll bars is based on the painter width, but (I believe) that width includes the new guttertext area on the left.  So the val+extent ends up being bigger than the max, and so it truncates something.

The additional typing bug I'm seeing is related to the white gutter area just to the left of typed code; still trying to sort that out.  (too much debug text dumping to console, juggling two weirdnesses at once, must get back to other work shortly)

If this helps anyone wrap this up, grab it and take over.  I'm not sure how to resolve the painter.getWidth() call being misleading since it's in the updateScrollBars() that's in the original processing.syntax.JEditTextArea class, but the new painter is in the subclassed stuff in the pdex folder.  I'll poke at it some more when I can but that might be a day or twelve.

**Comment by joshgiesbrecht** [comment]
Ok, I have a cheap hack fix for this that works for me.

In processing.syntax.JEditTextArea.java, the updateScrollBars() method, change:

int painterWidth = painter.getWidth();

to:

int painterWidth = painter.getWidth() - 50;

50 because that seemed to be enough to compensate for the new guttertext width.

_Ideally_ we'd call something instead of getWidth() that returns only the actual scrollable text area's width, but since this code is in processing.syntax it doesn't know anything about the subclassed painter object made for pdex.  So in a perfect world when the pdex stuff is refactored back up to processing.syntax this could be fixed for reals.

Want this submitted as a fix?  Or hold off and let someone who knows the pdex stuff better than me take this and do something less ugly?

(this fixes the original bug but not the second thing I mentioned earlier; if it keeps bothering me I'll file it as a new bug and try harder)

**Comment by benfry** [comment]
Added something like that as a workaround in https://github.com/processing/processing/commit/0af52e3af8349bf37d9a343e5d04cc0d648ce86a, let me know if that works.

**Comment by benfry** [comment]
Oops, I shouldn't be doing this before I wake up... Added another try. 

Also see that there's more mess inside `updateScrollBars()`, confirming that this whole thing just needs more attention.

**Comment by benfry** [comment]
So at the moment, we're likely "mostly" fixed for 3.0 beta 7, but this should be kept open to find a real fix.

**Comment by joshgiesbrecht** [comment]
Checked and it works for me.
