### ISSUE TITLE
Demos/Graphics/LowLevelGL needs glVertexAttribPointer (should be available on GLES2)

### ISSUE THREAD

**Issue by gohai** [processing/processing#3621]
Please close if this is expected behavior - I am currently testing all P2D/P3D examples with GLES2 hardware, and came across a few examples that try to use functions unavailable to GLES2.

I am receiving an error that "GL function glVertexAttribPointer() is not available", but the function should be available in GLES2 according to [this documentation](https://www.khronos.org/opengles/sdk/docs/man3/html/glVertexAttribPointer.xhtml). The current code in PJOGL.java:1961 checks if gl2x if gl2x is not null and continues to call the method on this object, if it is not. Any chance that this would be also available for gl2?

**Comment by gohai** [comment]
It seems the function is being called with a buffer rather than an offset. And JOGL only supports the latter for GLES2. Could either the example be changed, or the function be made to transparently handle this case? (I found this [GL2ES2 demo](http://jogamp.org/jogl-demos/src/demos/es2/RawGL2ES2demo.java) from the JOGL team, that shows how they suggest to do it, I think)

**Comment by JakubValtar** [comment]
@gohai I can't find this function in the JOGL api anywhere. If you know which class implements it, please let me know, otherwise we are out of luck.

**Comment by JakubValtar** [comment]
This function is not going to work anymore because we moved to GL2ES2 and we are not getting legacy GL2 functionality on desktop.

Removed the example and added two new ones to show how it should be done: https://github.com/processing/processing-docs/pull/289
See examples: `Demos/Graphics/LowLevelGLVboInterleaved` and `Demos/Graphics/LowLevelGLVboSeparate`
