### ISSUE TITLE
Problems with rendering text at very large sizes in P2D

### ISSUE THREAD

**Issue by jensschulze** [processing/processing#3722]
I’m having problems with displaying big sized text in processing.

Text will be rendered incorrectly on:
* Windows 10 (Java 8u51, Processing 3.0b5, set to 4096MB max. memory): some characters incomplete
 
Text will be rendered correctly on:
* Windows 7 (Java 8, Processing 3.0b3)
* Mac OS X 10.9.5 (Java 8u51, Processing 3.0b3, set to 4096MB max. memory)

Another error (flickering screen) occurs on:
* Mac OS X 10.9.5 (Java 8u51, Processing 3.0b5, set to 4096MB max. memory): switching between desktop and processing sketch each frame

```processing
int iFontSize = 256; // The rendering issue on the Windows 10 system starts at font sizes above roughly 160. The weird flickering on the Mac has nothing to do with font size, it just happens always.
String sTextAbc1 = "ABCOPQRST";
String sTextAbc2 = "ABCQRSTUV";
PFont pfFont;

void setup()
{
  fullScreen(P2D); // No difference if we use fullscreen() or size()
  colorMode(RGB, 255, 255, 255);
  background(255, 0, 0);
  fill(255, 255, 255);
  pfFont = createFont("Arial Black", iFontSize); // No difference if we create the font here or in the "Tools" menu
  textFont(pfFont, iFontSize);
  text(sTextAbc1, 0, 340);
  text(sTextAbc2, 0, 740);
}
```

**Comment by benfry** [comment]
I suspect this has more to do with the size of the font and the capabilities of the machine's graphics card/chipset on which you're running the examples. The missing characters are usually an indication that you're running out of OpenGL graphics memory, which has nothing to do with the RAM on your machine (or the memory allocated in Preferences). 

A 256 pixel font usually requires about 500x500 pixels of image area to render. If you're using a machine with limited graphics capabilities, that'll fill up quickly. And it'll be worse on Windows 10 because of all its desktop effects chewing up more memory.

**Comment by jensschulze** [comment]
Just for the sake of completeness I tried it with Processing 3.0b3 on the Windows 10 machine (AMD Radeon HD8470D), and indeed I encountered the same problem. Of course the Windows 10 machine is the computer my Sketch has to run on …
![texttest-windows10-0000](https://cloud.githubusercontent.com/assets/4244824/9554126/f88d4816-4dc3-11e5-9ae1-a20990fb6e19.png)
So the question how to render big characters in my sketch remains. Would it maybe make sense to use a library like NextText?

**Comment by JakubValtar** [comment]
@jensschulze Your GPU is in the processor and uses part of RAM as its memory. Try to dedicate more RAM to your graphics card, it may be possible to do this in BIOS. If that does not help, you can use `textMode(SHAPE);` to draw the characters as a shapes instead of textures, it may hurt your performance a lot though.

**Comment by jensschulze** [comment]
I cannot access the BIOS, but textMode(SHAPE) does the trick. It seems to affect the anti-aliasing but I think i’ll use it anyway.
Many thanks to both of you!

**Comment by dariusk** [comment]
Just wanted to chime in and add that I've been running into missing characters rendering large fonts made with `createFont()` in P2D/P3D in Android mode as well. The android device is definitely low-powered when it comes to graphics memory and I'm seeing it at even smaller sizes (90px for some fonts). I agree with @benfry; this is a hardware limitation. The workaround I'm trying instead is rendering text as vectors instead of bitmaps.

**Comment by codeanticode** [comment]
I will close it, as it seems to be due to insufficient video memory when dealing with large fonts.
