### ISSUE TITLE
Implement xlink+def support in SVG

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#373]
_Original author: niho...@gmail.com (July 30, 2010 21:07:19)_

SVG offers the possibility of declaring reusable graphics, using a &lt;defs&gt; element to define standard blocks of SVG code, which can then be recycled in the SVG main 'code' using &lt;use/&gt; elements. And example of this is given on http://www.svgbasics.com/defs.html

Especially for dynamically generated SVG (using the PShape(new XMLEelement(...)) approach) this would be a really nice feature to have available.

_Original issue: http://code.google.com/p/processing/issues/detail?id=334_

**Comment by JakubValtar** [comment]
Not sure if we want more features in the SVG import or not.

**Comment by benfry** [comment]
I think it'd be a matter of someone building a much more feature complete version based on the Batik library that's now included w/ SVG Export. But I don't see anyone emerging to do that anytime soon, especially when it'd need to work across each of the renderers. 

I think we need an "unlikely" category for things like this (and others like RTL support). They're huge things, are unlikely to be implemented, but should be documented somewhere since they're brought up more than once.

**Comment by benfry** [comment]
Rolling SVG requests into https://github.com/processing/processing/issues/5935
