### ISSUE TITLE
beginShape(POINT) vs beginShape(POINTS)

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#3776]
It's related to the documentation. I opened an issue for that here:
https://github.com/processing/processing-docs/issues/307

In short, the documentation shows as parameter POINT where it should be POINTS.

Using POINTS in P3D for example causes nothing to appear.

It would be really great if createShape does a simple to check.
For example:

````java
PShape createShape(int kind) {
    if (kind == POINT) {
        // print warning or kind = POINTS
````

**Comment by JakubValtar** [comment]
I just fixed a bug where createShape would not take three parameters in 3D, but it is not the problem here.

We don't have `createShape(int kind)`, there is only `createShape(int type)`, which can be only `GROUP`, `PShape.PATH` or `PShape.GEOMETRY`.

Correct ways to create point shape are:
```processing
size(200, 200, P3D);

background(0);

strokeWeight(10);
stroke(255, 0, 255);

// Can be only one point
PShape s0 = createShape(POINT, 100, 100);

shape(s0);
```

```processing
size(200, 200, P3D);

background(0);

strokeWeight(10);
stroke(255, 128, 0);

// Can be multiple points
PShape s1 = createShape();
s1.beginShape(POINTS);
s1.vertex(66, 66);
s1.vertex(133, 133);
s1.endShape();
    
shape(s1);
```
You are right that reference needs to be more clear about this, but there is nothing we can do in the code. We can't check for `createShape(POINT)`, because the `POINT` constant has the same value as `PShape.PATH`, which is valid.

**Comment by benfry** [comment]
For 3.0 beta 6, changed the value of the `PRIMITIVE`, `PATH`, and `GEOMETRY` constants in PShape so that we can detect when a user (incorrectly) does this.
