### ISSUE TITLE
Update libraries don't work on few libraries

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#3802]
The update library don't work on "QrCode", "RiTa" and "Blobscanner" the download and the install is like ok, but not the finalization. the button stay orange and the text indicate it's necessary to update the library.
![capture d ecran 2015-09-15 a 21 51 37](https://cloud.githubusercontent.com/assets/3332269/9888351/e3ed4566-5bf4-11e5-9cfc-34f9e4e26df4.png)

**Comment by Akarshit** [comment]
@shiffman For QRCode
The contribs.txt file shows that a version 3(0.3a) is available but the library.properties file shows only a version of 2(0.2a).

**Comment by benfry** [comment]
Paging @prisonerjohn...

**Comment by prisonerjohn** [comment]
A couple of things happening here:
* `QRCode`, `Blobscanner`, and 'YahooWeather' have different library.properties files at the download URL and in the ZIP package, so that's why the updates aren't "registering". I'll email the authors to let them know.
* `RiTA` was quarantined because it was broken, and should have appeared greyed out in the PDE (unless you had already downloaded it). I just tested it and it's mostly working, so I'll enable it again.

If this becomes a common problem that we want to avoid in the future, we could add a step where we cross-check both library properties files and make sure the version numbers match up.

**Comment by shiffman** [comment]
Thanks for the alert, I'll double-check the library.properties file in `QRCode` later today and report back.

**Comment by mrzl** [comment]
I'll check YahooWeather asap and give you feedback.

**Comment by shiffman** [comment]
Ok, I believe I've resolved the issue for `QRCode`, let me know if anyone still sees a problem.  Thanks!

**Comment by benfry** [comment]
Are we all set here?

**Comment by mrzl** [comment]
I fixed it for YahooWeather!

**Comment by prisonerjohn** [comment]
I haven't heard back about Blobscanner. Should I just disable it until I get some news?

**Comment by benfry** [comment]
Yes, let's do that.
