### ISSUE TITLE
Contribution Manager does not update a library

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#3885]
I installed this library today and the update was there immediatelly after the installation. When I click update it executes the update, but the version stays the same and it offers me to update again.

![1](https://cloud.githubusercontent.com/assets/3177098/10124747/dd4b022c-652a-11e5-8979-f407658a82bf.png)

**Comment by joelmoniz** [comment]
Hmm... I have a feeling this might be because the version number in the
.properties file inside the contribution does not match with the version
number in the contributions.txt file. If this is the case, it might be
because the library's <download_link>.txt file used to generate the
contributions entry (if the library's download link is <download_link>.zip)
is out of synch with the library.properties file inside the contribution
itself.

**Comment by Akarshit** [comment]
Duplicate of #3802

**Comment by JakubValtar** [comment]
Ah, didn't notice that one.
