### ISSUE TITLE
Really portable

### ISSUE THREAD

**Issue by SebCanet** [processing/processing#3948]
Hi, I'm working in schools and I would to use a portable version, usable on USB stick. Also because there are securities, and as I work in different school there are different securities. On Processing3 I didn't find all the option I could find in Processing2 preferences to make quite portable (because it still write in c:\Users\AppDatat\etc

Thanks a lot for helping me.

**Comment by GambogeGoose** [comment]
Hi,
preferences.txt file should allows you to give the program relative paths, that includes smartcards ("." or "..").
Try playing with it!

**Comment by SebCanet** [comment]
Hi,
no, even with modification (on any version of Processing) like "sketchbook.path.three=perso", it always uses/creates a folder in "c:\Users\AppDatat\Roaming\Processing\preferences.txt

**Comment by GambogeGoose** [comment]
I think it is meant to save configs from one version to another!
I usually have a copy of processing folder in my USB stick and I paste it in Documents folder every time I need it...
I know it is a poor workaround, but it is better than nothing.

Compromises are that you use always default preferences and you copy processing folder again from Documents folder to USB stick in order to have always the latest version of your files!

Ah, another thing...
This way makes processing "discard" of your last opened files because of its location is always in Roaming folder.

I'm sorry for a quite late reply.

Hopefully enough some developer will see our request of portability and would include it in the next version...
I'm using 3.2.3 and it is still not fully portable.

**Comment by olliebean** [comment]
A very belated reply, but seeing as the issue is still open... I have managed to make Processing (v3.5.4) fully portable in Windows by placing a batch file (e.g., `ProcessingPortable.bat`) in the same directory as the program, containing the following code:

```
SETLOCAL
SET USERPROFILE=%~dp0\settings
processing.exe
```

Running the batch file will start Processing, with the current user profile directory redirected to `.\settings`, so all the `AppData\Roaming\Processing` files will go in there. You'll still need to change the Sketchbook location in the settings to a relative path. (And remember always to run Processing via the batch file, not by running the `processing.exe` file directly.)

**Comment by GambogeGoose** [comment]
Thank you @olliebean [:

**Comment by SebCanet** [comment]
Many thanks! But it still is not a solution for Processing, like a setting, or something 'automatic' when you create a folder named 'portable' in Arduino IDE.
I'll post it on v4 github repo.
Thanks.

**Comment by benfry** [comment]
No need to repost the same issue in the new repo (or in the case of processing/processing#6189, in the same repo). 

If I have a chance to re-implement this, I'll just move the issue over once finished.

**Comment by benfry** [comment]
Will be possible in 4.0 beta 4 as of https://github.com/processing/processing4/commit/1a49263a94a2d7af2b4686286406f7896d207cd9. 

With the latest version of the source, or with beta 4 when it's posted, create a file called `settings.txt` in the `lib` folder that's part of the download. Put `settings.path=/path/to/your/folder` in there and give it a shot.
