### ISSUE TITLE
Update to JogAmp JOGL 2.3.2

### ISSUE THREAD

**Issue by xranby** [processing/processing#3979]
I am happy to announce that JogAmp JOGL 2.3.2 has been released
http://jogamp.org/wiki/index.php/Release_2.3.2

This release contain many important fixes and some superb new features:

	Add OpenGL ES 3.2 and new OpenGL GL 4.5 Extensions support
        Supports all Mesa3D GPU drivers for use on embedded ARM GNU/Linux systems.
        Improved user experience when using the Rapberry Pi Broadcom driver.
        Works with the latest NVIDIA beta drivers.
        Fixes many issues reported on MacOSX
        Restored compatibility with WindowsXP

For a complete list see:
http://jogamp.org/wiki/index.php/SW_Tracking_Report_Objectives_for_the_release_2.3.2

**Comment by gohai** [comment]
Awesome, thanks @xranby @sgothel!

I was wondering about the rationale behind having the gluegen & jogl sources in processing.git. Since they're > 25 MB, would it perhaps be feasible to remove them when Processing upgrades to 2.3.2, and replace them e.g. with a text file that references the particular Git(hub) commit (and URL) those were build from? (cc @benfry)

**Comment by codeanticode** [comment]
Hi @gohai, I just pushed the update with https://github.com/processing/processing/commit/9a71778618ceb3a9a0bbafbc2285b2b120c466dc, including the sources, before seeing your comment. I think the jogl sources were traditionally included since Processing 1.x, but they were probably smaller back then. I defer to @benfry about removing them.

**Comment by gohai** [comment]
Thanks @codeanticode! Let's leave this open to catch Ben's eye re removing the sources for the future.

**Comment by benfry** [comment]
Yeah, I didn't realize they'd grown that large. @codeanticode if you're not removing them, please go ahead and remove them.

**Comment by gohai** [comment]
see pull request #3982

**Comment by xranby** [comment]
Thank you for the report, i will take a look if the source zip have bundled something that is not sources that bumps up the size.

Starting with JogAmp 2.3.2 we provide a "fat" jar, that is an all in one jar deployment option including all jogamp modules, with matching src zip.
The source zip for the "fat" jar deployment option is "only" 5.8Mb containing the sources for all jogamp modules.
http://jogamp.org/deployment/jogamp-current/fat/
jogamp-fat-java-src.zip	10-Oct-2015 05:02 	5.8M

Processing 3 is currently using the "slim" deployment option using the contents from the jogamp-all-platforms.7z
http://jogamp.org/deployment/jogamp-current/archive/jogamp-all-platforms.7z
As you say the source zip found inside the jogamp-all-platforms.7z used for the "slim" deployment option is larger than 25Mb then i need to look into it and check why the two deployment options "slim" vs "fat" source zip's differ that much in size.

**Comment by xranby** [comment]
I have filed a JogAmp bugreport to track the src zip sizes:
https://jogamp.org/bugzilla/show_bug.cgi?id=1252
