### ISSUE TITLE
P3D alpha channel not working

### ISSUE THREAD

**Issue by shirish47** [processing/processing#3991]
I am using a texture png. and when I use it in p3d mode in my windows, alpha channel does not work. it works only when I do hint(ENABLE_DEPTH_SORT)
this also ruins 3d objects like spheres.

also blendMode(ADD) seem to have no effect its same as normal image display.

:(

**Comment by shirish47** [comment]
![01862](https://cloud.githubusercontent.com/assets/6296507/10441010/d35a6210-7161-11e5-8f6d-9468f25249ea.jpg) when two plan come in contact even when enable_depth_sort. I transperancy fails.

**Comment by codeanticode** [comment]
Hi @shirish47, I cannot address your issue report properly without seeing any code, but it seems to me that blending is not working properly in P3D precisely because you need to enable depth sorting, without it semi-transparent geometry will not look correct.

Also, you would need to subdivide your planes along the intersection line for depth sorting to work properly ([this discussion](https://twitter.com/JoshuaDavis/status/644508925535064064) on twitter might be relevant).

**Comment by shirish47** [comment]
ok
ya I think I have sorted it out ...it took me playing around with depth .. I still don't understand exactly what is happening here .. but I think its z-fighting ..
