### ISSUE TITLE
While problems when using it with mousePressed

### ISSUE THREAD

**Issue by Cyroux** [processing/processing#4028]
When I use while with a boolean and an if with the mousePressed, the program crashes and if I look at the Windows Task Manager I can see that Java is using all the ram and CPU.
I wanted to use the mouse to repeat a routine but the while makes it crash.
I attach a simplified version of my code. I tried with different computers and different Processing versions it always crash.

![while error](https://cloud.githubusercontent.com/assets/15202741/10590560/995559ee-76b1-11e5-8765-bbdc4ffd79e0.png)

**Comment by JakubValtar** [comment]
mousePressed is only updated outside of setup() and draw(). It will not be updated if you block the flow with while loop.

Put your code into draw() function instead of while loop, it will get called repeatedly for you.

For more coding questions please ask on the forum http://forum.processing.org/two/ first, these questions are not appropriate here. Please post here only when you are certain something is broken. Good luck!
