### ISSUE TITLE
parseJSONObject() has no error handling

### ISSUE THREAD

**Issue by smay4finger** [processing/processing#4036]
The only way to handle parsing errors is to catch a RuntimeException. The function parseJSONObject() should throw a special JSONParseException.

**Comment by benfry** [comment]
That's by design. Check out the rest of the API—exceptions aren't used anywhere. If you know what a `RuntimeException` is, you should write a try/catch block for it.

**Comment by smay4finger** [comment]
So you honestly mean I should put a try-catch-block catching RuntimeException around parseJSONObject()? 

```java
try {
  parseJSONObject("illegaljson");
}
catch(RuntimeException e) {
  // could be a parse error, could be something else
}
```
Maybe in the Processing world everything is going well all the time. But parse errors from data outside of the program is a very common problem. So my conclusion is the programmer should have a decent way to check for validity of data. A decent JAVA way would be to throw an own Exception for parsing errors. This exception could be also unchecked without breaking existing code and surprisingly there is the commented JSONException lying around in JSONObject.java. Why isn't it used?

If the Processing way is to hide all this exception handling from the programmer, there should be a method for checking the validity of JSON data. I would like to propose a function isValidJSONObject(String) returning true for valid JSON data.

**Comment by benfry** [comment]
You're missing the point. We don't use exception handling because it's not suitable for the target audience. When something goes wrong, `null` is returned, because for the primary audience, the code isn't going to continue anyway. But having to teach users about try/catch blocks within the first few minutes of writing code is not appropriate. 

If you want to write Java code with full exception handling, do so. You can use any Java-based JSON library to get the advanced results you want. You can even do that alongside Processing code.

**Comment by smay4finger** [comment]
But what about a function isValidJSONObject(String) returning a boolean?
