### ISSUE TITLE
Text rendering differ on different mode+ ellipse 

### ISSUE THREAD

**Issue by thierry75** [processing/processing#4066]
Processing 3.0.1 is so fast in P2D or P3D, i'm amazed
but text rendering is less clear and some artefact on rendering ellipse and line, a little bit like if noSmooth() doesnt work for P2D and P3D

Processing 3.0.1 on osx yosemite
Thanks for the fabulous job you ve done
eg, 
![p3 0 1](https://cloud.githubusercontent.com/assets/372161/10720506/3db3db6a-7b98-11e5-870c-1e997b8a8ee3.png)

**Comment by codeanticode** [comment]
It is not possible to emulate 100% the text output of the default renderer with OpenGL due to the very different way text is handled in P2D and P3D. In general, the OpenGL renderers are optimized for performance over quality. The blurriness you can sometimes notice is the result of OpenGL's texture sampling and not something we can actually fix. The wiki [mentions a few ways](https://github.com/processing/processing/wiki/Advanced-OpenGL#Textures) to control texture sampling from Processing using the ```hint(DISABLE_TEXTURE_MIPMAPS)`` hint and the ```((PGraphicsOpenGL)g).textureSampling(2)``` call, maybe these can help you tweak your text output.
