### ISSUE TITLE
problem with certain fft font files

### ISSUE THREAD

**Issue by jonnystokes** [processing/processing#4109]
![screenshot](https://cloud.githubusercontent.com/assets/3003761/11006111/cc5bc6de-8476-11e5-9120-a21623846f97.png)
i was trying to display a counter by combining a string and a int.
i thought i was doing something wrong because the numbers weren't showing up as numbers for they were characters.but when i used the print function it showed up right.

i found out it was the fft font file [Porter_Bold.ttf](https://www.dropbox.com/s/a3pz1zrl1lljg7d/Porter_Bold.ttf?dl=0) and when i put another font [FIRESTARTER.TTF](https://www.dropbox.com/s/k73e0lhk93s0fvw/FIRESTARTER.TTF?dl=0) it worked fine. and with no font being default works fine. so the problom could be in the file or in processing.

here's the code

```processing
void setup() {
  size(500, 255);

  background(0);

  String myString = "counter " + 321235532 + " test";

  PFont font;
  font = createFont("Porter_Bold.ttf", 16);
  textFont(font);

  println(myString);

  text((myString), 10, 130);
}

void draw() { }
```

the files from dropbox
[dropbox FIRESTARTER.TTF](https://www.dropbox.com/s/k73e0lhk93s0fvw/FIRESTARTER.TTF?dl=0)
[dropbox Porter_Bold.ttf](https://www.dropbox.com/s/a3pz1zrl1lljg7d/Porter_Bold.ttf?dl=0)

**Comment by cameyo42** [comment]
I have the same problem.
Some fonts work with createfont(), some fonts work with loadFont() and some other fonts don't work at all.
i have found that all work with newly installed fonts (seem).

**Comment by JakubValtar** [comment]
@jonnystokes Porter Bold does not work because it is a demo version and it does not contain numbers (if you open the font you will see there are DEMO characters where 123456789 characters should be). Get font with numbers and it should work alright.

@cameyo42
- `createFont()` works for TTF fonts loaded from file (*.ttf) or fonts loaded from system (run `printArray(PFont.list());` to see all system fonts you can use on your machine.
- `loadFont()` works only for vlw bitmap fonts (you can create these with Tools - Create Font...).

Please look in the [createFont() reference](https://processing.org/reference/createFont_.html) and [loadFont() reference](https://processing.org/reference/loadFont_.html).

**Comment by jonnystokes** [comment]
problem solved.
it seems to be that some fft font files replace the numbers with the word    DEMO   
thanks

**Comment by cameyo42** [comment]
Thanks !!!
