### ISSUE TITLE
rectMode(RADIUS) make text(words,...) invisible

### ISSUE THREAD

**Issue by ProDarek** [processing/processing#4111]
Hi All,

```
/*
tested on:
    Processing 2.2.1
    Processing 3.0.1
with:
    Windows XP (32-bit and 64-bit)
    Ubuntu Linux 14.04 (32-bit and 64-bit)
and:
    Java 7 Update 10
*/

String words = "for ex. Dariusz Kubiak - ProDarek";

void setup()
{
  size(400, 400);
  rectMode(RADIUS); // this make text(words,...) invisible !!!
}

void draw()
{
  text(words, 10, 80, 400, 400);
  text("word", 10, 30); 
}
```

ProDarek

**Comment by JakubValtar** [comment]
Hi @ProDarek, this is because you are drawing of outside of the window. Rect mode RADIUS means that first two coordinates are center of the rect and other two coordinates are half the width and height of the rect. So what you have is like `text(words, -390, -320, 800, 800)` in CORNER mode. Please read the [rectMode reference page](https://processing.org/reference/rectMode_.html) and ask on [the forum](https://forum.processing.org) for any other coding questions.
