### ISSUE TITLE
NullPointerException inside buildCoreModes() when starting 3.0.1 on Windows

### ISSUE THREAD

**Issue by camelbob** [processing/processing#4128]
After downloading and unpacking version 3.0.1 I get a window titled "We're off on the wrong foot" Contents of window include, "An error occurred during startup" " java.lang.NullPointerException at processing.app.Base.buildCoreModes(Base.java:357).   See attached jpeg.

I am running windows 7 enterprise with service pack 1 on a HP Folio 13 -2000 notebook PC. All recent versions of processing have installed and run ok
![wrong foot](https://cloud.githubusercontent.com/assets/15783364/11064423/0d613d1c-87b5-11e5-93d8-4d3dc2636cf1.jpg)

**Comment by IAMFALL** [comment]
bump

**Comment by subject117** [comment]
I get the same error message on linux with processing 3.1.1. Any suggestions for what to do here?

**Comment by benfry** [comment]
I have no idea; I've never seen this and can't find a way to reproduce it. 

The error seems to be happening because it can't find the folder that contains "Java Mode". Is there something strange about how the files have been unpacked from the archive? Have you messed with the Processing folder itself somehow?

**Comment by subject117** [comment]
Thank you! Your reply stimulated the insight I needed to fix this. It only took a few minutes after I sat down in front of my computer.

The problem was my Java CLASSPATH. For reasons related to a project I did a few years ago, I had a set of Processing jar files (probably 2.2.1) in a directory that was always in my CLASSPATH. I realize now that this is not a good idea but it made sense at the time.

When the Processing startup script runs it adds its own files and directories to the end of the CLASSPATH before launching the application. Since my other set of Processing jar files were ahead of the correct jar files, the JRE would load classes from those jars first. Not surprisingly, that is bad for Processing.

To fix it, I simply had to simply remove my addition to  my CLASSPATH. It worked right away after that.

**Comment by benfry** [comment]
Agh; that's an exceptionally bad idea. How were you setting the CLASSPATH? Environment variable? It shouldn't be using the machine's CLASSPATH at all so I need to figure out how to avoid that.

**Comment by subject117** [comment]
> Agh; that's an exceptionally bad idea.

I agree! I was young and foolish.

> How were you setting the CLASSPATH? Environment variable?

I was setting it with an export CLASSPATH=... statement in my .bashrc file. I have a Linux (Ubuntu) box.

> It shouldn't be using the machine's CLASSPATH at all so I need to figure out how to avoid that.

True. If there is anything I can do to help you do figure out how to do that, please ask.

**Comment by benfry** [comment]
Added workaround for Processing 3.2, see #4608

But let me know if that doesn't fix it; it's possible that `CLASSPATH` is handled differently.

**Comment by subject117** [comment]
Nice. Happy to contribute to progress.
