### ISSUE TITLE
mouseWheel() not working when using FX2D renderer

### ISSUE THREAD

**Issue by biggestpleb** [processing/processing#4169]
When using the FX2D renderer mouseWheel() is not called when the mouse wheel is moved. 

```
void setup() {
  size(100, 100, FX2D);
}

void draw() {} 

void mouseWheel(MouseEvent event) {
  float e = event.getCount();
  println(e);
}
```

The other mouse functions (mousePressed(), mouseReleased() etc.) all work fine. The above sample code works if the renderer is changed to anything other than FX2D. 

(Win 8 64bit)

**Comment by brendanmatkin** [comment]
Can confirm this for OSX 10.11.1, Processing 3.0.1.

**Comment by CoenB95** [comment]
Why has this bug not been fixed yet? Because of this i am forced to use JAVA2D (or P2D or P3D) in order to receive scroll-inputs. But I would really want to use FX2D because of its fastness (sorry for my English). Looking through the code I discovered that mouse wheel events are handled by `fxMouseWheel(ScrollEvent)`, which does nothing (read: is an empty method). Some testing made it clear that only one line of code is needed to make it work (to be placed in 'fxMouseWheel(ScrollEvent)': 
```
postEvent(new MouseEvent(event, System.currentTimeMillis(), MouseEvent.WHEEL,
							0, (int) event.getX(), (int) event.getY(), 0, 
							(int) (event.getDeltaY()/event.getMultiplierY()*-1))); 
```
(In order to achieve the same results as JAVA2D, I divided delta_y with its multiplier and inverted the result)

Using some very dirty coding i was able to override the listener passed to `setOnScroll()` of the javafx Canvas of PSurfaceFX and can confirm that the above code works on at least Windows 10 with Processing 3.0.2, but it should work on all platforms.

To the Developers: please implement scrolling on FX2D so I don't need to use JAVA2D or this detour anymore.

**Comment by Dolphin101546015** [comment]
In Windows 10 x64, also not working.
Also not working mouse buttons:
left and right buttons have one event.

**Comment by tarabishy2020** [comment]
This is still a problem in the latest release! any work around for this?
It behaves differently when FX2D is used (event.getCount() returns zero a lot while the scroll is being used and then some times suddenly jumps to -2 or 2) and when it is not (event.getCount() returns 1 or -1 consistently if you are scrolling up or down)

**Comment by turbotilman** [comment]
I am having an similar issue in release 3.3.4 on macOS 10.14.5.
event.getCount() returns a lot of zeros and some ones while scrolling slowly.
When I'm scrolling faster it suddenly returns high numbers in the range from 6-12.
