### ISSUE TITLE
NoSuchMethodError Minim Library

### ISSUE THREAD

**Issue by lunabug** [processing/processing#4174]
I have been using the code BeatWrite to sync LED's to music, and it was working up until I updated my Processing, Minim (2.2.2)  and Arduino libraries, and Java. I am desperately trying to get this to work, but I keep getting an error saying:

NoSuchMethodError: You may be using a library that's incompatible with this version of Processing. java.lang.NoSuchMethodError: ddf.minim.spi.AudioStream.read(Lddf/minim/MultiChannelBuffer;)I at ddf.minim.javasound.JSAudioOutput.readStream(JSAudioOutput.java:125) at ddf.minim.javasound.JSAudioOutput.run(JSAudioOutput.java:74)

I have tried manually inserting the minim file into the sketchbook>libraries file and that still doesn't seem to work.

PLEASE help.... this is for a grade in my class and I am running out of time...

**Comment by alignedleft** [comment]
@lunabug It looks like you are using a library that's incompatible with your version of Processing… just as the error says. :-)

With Processing 3.0.1 try using the new Sound library instead of Minim, or try Minim with an older version of Processing, like 2.x.

Either way, this is not a bug, so please don't report it here. Instead, ask these sorts of questions in the forum: forum.processing.org

Good luck!
