### ISSUE TITLE
PDE is 2x smaller on high-res (hidpi) screens on Linux

### ISSUE THREAD

**Issue by adriaanb** [processing/processing#4183]
I set up my retina MacBook Pro with Linux and I am unable to find a suitable solution to work with the Processing IDE in a productive way as the interface of the IDE is rather small.

Sketches do not scale as well, but this is a limitation I can work around.

As the recognition of pixel densities in Linux appears to be somewhat complicated, the introduction of the possibility to manually set the DPI scaling factor via the settings dialogue or a config file could be a practical solution.

In the meantime any kind of workaround would probably do.

Here is a screenshot showing Processing next to a (patched) Arduino IDE with 200% scaling factor:
![processing_ubuntu_hidpi](https://cloud.githubusercontent.com/assets/16139611/11569698/8cfa6e72-99f3-11e5-89e9-532bbc094d41.jpg)

**Comment by benfry** [comment]
No upstream patch from the Arduino folks, unfortunately.

**Comment by grg2rsr** [comment]
I have the same problem on dell XPS 13 with a QHD display, running Ubuntu 16.04. Scaling factor set via the Unity config GUI doesn't affect scaling in the Processing IDE.

**Comment by steve2718** [comment]
I found the same issue and reported it in #4420, before I found this thread. Like grg2rsr, I have a high-density display. The issue is not just with Linux; it's also present in Windows (at least in 8.1). It might be more properly called a hi-dpi display issue. "...upstream patch"? Where did the Arduino folks add their "Interface scaling" property (<-which works like a charm)? Wouldn't that code be very similar, if added to the PDE?

**Comment by Tyekai** [comment]
I have a similar problem...
Operating on Windows 10 with a 17" 3840x2160 display.
The program is actually unusable at this size in my opinion.

Windows 10 comes with a 'Scale all things' option that is set to 250% and works for everything else...
But when I downloaded Processing on to this computer for my first time since buying it I got this:
[http://oi63.tinypic.com/2qa0488.jpg](url)

I mean how am I supposed to read (much less type) lines of code that are 1/13 the size of a desktop icon?

**Comment by Rondte** [comment]
Same here on my Kubuntu 16.04 installation, with 2560 x 1440 display. More or less impossible to work with the application because of it. Processing (3.1.1) seems to be immune to the 'scale display' option in the Kubuntu settings menu, so a solution does not seem at hand.

**Comment by Tyekai** [comment]
I'm not even on Linux -_-
Windows 10 here.

**Comment by polyphant1** [comment]
+1 Linux HiDpi, Gnome, currently unusable

**Comment by benfry** [comment]
Most of the editor has been fixed for 3.3, though sketches are still small: https://github.com/processing/processing/issues/4895

**Comment by jcelerier** [comment]
@benfry has it really been fixed ? for me it is minuscule (Processing 3.4.1). Is there an env var to set or something ?

![processing](https://user-images.githubusercontent.com/2772730/51438083-a7b0aa80-1ca7-11e9-8255-e0c242f88e9a.png)

thanks !

**Comment by benfry** [comment]
There's no API for this on Linux, so you have to set it in Preferences.
