### ISSUE TITLE
java.lang.IllegalArgumentException on resize of window.

### ISSUE THREAD

**Issue by jsuijs** [processing/processing#4235]
Hi,

When you setup a window to be resizeable and move the lower edge of the window all the way up, the program throws an exception:

java.lang.IllegalArgumentException: Width (500) and height (0) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.awt.GraphicsConfiguration.createCompatibleImage(GraphicsConfiguration.java:186)
	at processing.awt.PGraphicsJava2D.checkImage(PGraphicsJava2D.java:318)
	at processing.awt.PGraphicsJava2D.beginDraw(PGraphicsJava2D.java:328)
	at processing.core.PApplet.handleDraw(PApplet.java:2361)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1527)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)

The sketch to reproduce the issue:

public void setup() {
  size(500, 360);   
  surface.setResizable(true);  
}

public void draw() {
}

**Comment by Akarshit** [comment]
I was testing this issue on Linux but was unable to reproduce this but in the effort got some weird result while resizing the window using the same code as above. Following are the screenshots of the window while resizing:
![screenshot from 2016-01-20 18 53 02](https://cloud.githubusercontent.com/assets/7762605/12450253/8d454a66-bfa8-11e5-9e45-93f72fc88e47.png)
![screenshot from 2016-01-20 18 53 17](https://cloud.githubusercontent.com/assets/7762605/12450321/f96d1e08-bfa8-11e5-9573-0e7d9066992e.png)
![screenshot from 2016-01-20 18 53 52](https://cloud.githubusercontent.com/assets/7762605/12450327/ffee4c0c-bfa8-11e5-9c19-6610e9ee6482.png)

I am not sure what is the cause of these or if they are related to the issue. Should i open another issue for these?

**Comment by jsuijs** [comment]
Got the issue on win7...

Joep

**Comment by payal97** [comment]
Got the same result as Akarshit on ubuntu 14.04

**Comment by benfry** [comment]
Sounds like a window manager problem on Linux, that it's letting you resize windows so that they have a height of zero. I don't know what we'd even do in that case—it's sort of a nightmare fix to try to support an edge case where your window is not visible, since a sketch is fundamentally about making things show up on the screen.

**Comment by jsuijs** [comment]
Hi Ben,

I think your comment refers to the adittional issue, reported by others.
The original issue is definitly *not* a linux issue. It is about an
exception in processing, while running on Windows 7 and Windows 10. This
exception terminates the execution of the sketch.

My sketch is used for logging of test cycles and this issue means that
resizing the sketch window could terminate data collection while the test
is still running. An incomplete test data mostly means the test is useless
and needs to be repeated.

I hope you consider reopening this issue.

Regards,
Joep


Op zondag 14 februari 2016 heeft Ben Fry <notifications@github.com> het
volgende geschreven:

**Comment by jsuijs** [comment]
Hi Ben,

Just verified with the new version of processing and, as expected, the
issue is still there.
Below a screenshot from the crash on my Win10 pc. Note that this is with my
large program, but the issue has been verified with a small program too to
exclude issues with the libraries used and minimize those of my own (see my
first posting).

I would be happy to look into this in more detail, but as an embedded C++
developer, I have no idea how to build a Java app from source code, let
alone debug an (undoubtedly complex) Java application like Processing...

Please advise if this issue can be re-opened or a new issue has to be
submitted.

Regards,
Joep

[image: 2016-02-14 10_21_30-RobotPresenter _ Processing 3.0.2.png]

Op zo 14 feb. 2016 om 07:15 schreef Joep Suijs <jsuijs@gmail.com>:

**Comment by benfry** [comment]
Linux or not, the problem is that there isn't a good way to not have a renderer that has size zero. Processing assumes that a renderer is always present, and some part of the screen is drawable. Changing that assumption would be a really messy fix. 

The bottom line is that users shouldn't resize the window until it can't be seen... You could instead do something like set the minimum size of the window, but for that you'd need to dig into how the native window is handled by `PSurface`. Or you could file a feature request that we include `setMinimumSize()` as a function in `PSurface`.
