### ISSUE TITLE
syntax highlighting messed up

### ISSUE THREAD

**Issue by lpdunwell** [processing/processing#4286]
syntax highlighting confuses code for comments every now and then.
a solution is to scroll past the beginning or end of a multiline comment.

**Comment by nad5305** [comment]
Same problem here.  One of the ways to trigger the bug is to create a new tab.  Click in a commented section of code.  Then, go back to the first tab.  The code in the first tab shows as all commented color coded.  The user must scroll to the fifth line at the top to get rid of the coloring effect.  All other tabs are unaffected by the glitch.

**Comment by JakubValtar** [comment]
Thanks, I noticed this was happening before, will try reproduce it with your instructions.

**Comment by JakubValtar** [comment]
Thanks folks. Fixed by #4761, will be part of the next release.
