### ISSUE TITLE
glPolygonMode() + glLineWidth() not working in 3 (but worked in 2)

### ISSUE THREAD

**Issue by hype** [processing/processing#4327]
@codeanticode can you look at this ? I just noticed that opening a file that worked fine in 2.2.1.

when calling this in 2.2.1 with...

`import javax.media.opengl.GL2;`
`GL2 gl = ((PJOGL)beginPGL()).gl.getGL2();`
`gl.glPolygonMode( GL2.GL_FRONT_AND_BACK, GL2.GL_LINE ); `
`gl.glLineWidth(3.0f);`
`endPGL();`

you could change the `glLineWidth` and the stroke of the mesh adopts whatever line weight specified.

but after the move and update to 3.0.2 with...

`import com.jogamp.opengl.GL2GL3;`
`GL2GL3 gl = ((PJOGL)beginPGL()).gl.getGL2GL3();`
`gl.glHint( GL2GL3.GL_POLYGON_SMOOTH_HINT, GL2GL3.GL_NICEST );`
`gl.glPolygonMode( GL2GL3.GL_FRONT_AND_BACK, GL2GL3.GL_LINE );`
`gl.glLineWidth(3.0f);`
`endPGL();`

the mesh displays in lines but `glLineWidth(1.0f)` or `glLineWidth(10.0f)` makes no difference - I seem to be forever locked in 1.0f, any thoughts ? (using p3.0.2 on OSX 10.10.5)

**Comment by codeanticode** [comment]
Hi, are you looking at changing the stroke weight of the shapes drawn with Processing's API, or trying to set the line width for your own GL calls?

**Comment by hype** [comment]
`gl.glPolygonMode( GL2.GL_FRONT_AND_BACK, GL2.GL_LINE );`
`gl.glLineWidth(3.0f);`

this would turn a mesh into wireframe mode basically and set the wireframe line weight to 3 - worked fine in 2.2.1 with `import javax.media.opengl.GL2;` but after updating to 3 to `import com.jogamp.opengl.GL2GL3;` line weight never updates `gl.glLineWidth(3.0f);` you can change that to any number and it never leaves 1.0f visually.

**Comment by codeanticode** [comment]
I you are doing everything through GL, including the geometry mesh, then the line width should work... Could you post some code for me to loo at?

**Comment by hype** [comment]
sure no problem... lets take your blue marble example / https://github.com/codeanticode/pshader-experiments/tree/master/BlueMarble

for processing 2 sketch lets...

`import javax.media.opengl.GL2;`

`  shader(earthShader);`
`  pushMatrix();`
`  rotateY(earthRotation);`
`    GL2 gl = ((PJOGL)beginPGL()).gl.getGL2();`
`      gl.glHint( GL2.GL_POLYGON_SMOOTH_HINT, GL2.GL_NICEST );`
`      gl.glPolygonMode( GL2.GL_FRONT_AND_BACK, GL2.GL_LINE );`
`      gl.glLineWidth(6.0f);`
`      shape(earth);`
`      gl.glPolygonMode( GL2.GL_FRONT_AND_BACK, GL2.GL_FILL );`
`    endPGL();`
`  popMatrix();`

run in processing 2.2.1 and the earth mesh is a wireframe with a line weight of 6

for processing 3 sketch lets...

`import com.jogamp.opengl.GL3;`

  `shader(earthShader);`
  `pushMatrix();`
  `rotateY(earthRotation);`
    `GL3 gl = ((PJOGL)beginPGL()).gl.getGL3();`
      `gl.glHint( GL3.GL_POLYGON_SMOOTH_HINT, GL3.GL_NICEST );`
      `gl.glPolygonMode( GL3.GL_FRONT_AND_BACK, GL3.GL_LINE );`
      `gl.glLineWidth(6.0f);`
      `shape(earth);`
      `gl.glPolygonMode( GL3.GL_FRONT_AND_BACK, GL3.GL_FILL );`
    `endPGL();
  `popMatrix();`

I've tried

`import com.jogamp.opengl.GL3;`
`import com.jogamp.opengl.GL4;`
`import com.jogamp.opengl.GL2GL3;`

anything the line weight still remains at 1.0f

**Comment by codeanticode** [comment]
Ok, I got it now. The problem is that in Processing 3, the default profile is [GL2ES2](http://jogamp.org/deployment/jogamp-next/javadoc/jogl/javadoc/). This is a fully programmable profile without support for GL lines() (strokes are generated by Processing's built-in shaders, so the old fixed-function glLineWidth() has no effect.

An easy solution could just be to initialize the sphere PShape with stroke enabled:

```java
earth = createShape(SPHERE, 200);
earth.setStroke(true);
earth.setStrokeWeight(6.0f);
earth.setSpecular(color(125));
earth.setShininess(10);
```

The second alternative is to force the P3D renderer to use the old fixed-function pipeline, where you still have glBegin(), glLineWidth(), etc. You achieve this by setting PJOGL.profile to 1 in the settings() function, like so:

```java
void settings() {  
  size(600, 600, P3D);
  PJOGL.profile = 1;
}
```

Note that when you use setting(), you cannot call size() in setup. And then, you can use the GL2 profile as you did in Processing 2:

```java
import com.jogamp.opengl.GL2;

 ...
  shader(earthShader);
  pushMatrix();
  rotateY(earthRotation);
  GL2 gl = ((PJOGL)beginPGL()).gl.getGL2();
  gl.glHint( GL2.GL_POLYGON_SMOOTH_HINT, GL2.GL_NICEST );
  gl.glPolygonMode( GL2.GL_FRONT_AND_BACK, GL2.GL_LINE );
  gl.glLineWidth(6.0f);
  shape(earth);
  gl.glPolygonMode( GL2.GL_FRONT_AND_BACK, GL2.GL_FILL );
  endPGL();
  popMatrix();
...
```

**Comment by hype** [comment]
awesome sir. I've already moved most of my 2.2.1 files to 3 using void settings() is there any disadvantage to forcing the profile.

**Comment by codeanticode** [comment]
From the perspective of the Processing API, none I can think of. Of course, you won't be able to use newer versions of GLSL, nor GL functionality available in 3+ (such IBOs, geometry & tessellation shaders, etc). Also, there is a slight overhead when using the fixed-function pipeline, because the old projection and modelview matrices are still being copied over to the GPU, while Processing handles its own matrices independently through shaders, but I think this is negligible.
