### ISSUE TITLE
Renderers but JAVA2D have problem for mouseButton under P3

### ISSUE THREAD

**Issue by iizuna** [processing/processing#4361]
while left mouse button is plessed, mouseButton ignores that right mouse button plessed or released.

```
void setup() {
  size(100, 100);
  //size(100, 100, P3D);

  fill(255);
}

boolean LMB, RMB;

void draw() {
  if (LMB) {
    background(0);
    if (RMB) {
      rect(30, 30, 40, 40);
    }
  } else {
    background(255);
  }
}

void mousePressed() {
  if (mouseButton==LEFT) {
    LMB=true;
  } else {
    RMB=true;
  }
}

void mouseReleased() {
  if (mouseButton==LEFT) {
    LMB=false;
  } else {
    RMB=false;
    if (LMB) {
      println("success");
    }
  }
}
```

for more details here: https://forum.processing.org/two/discussion/15531/how-to-detect-right-mouse-button-press-release-while-left-mouse-button-is-plessed-in-p3d-mode

**Comment by codeanticode** [comment]
Must be related to the event handling in JOGL's NEWT. Will look into it. This is on windows, right?

**Comment by codeanticode** [comment]
It looks like this is due to an upstream bug in JOGL, see [this thread](http://forum.jogamp.org/MouseListener-mouseWheelMoved-and-Shift-td4031233.html), in particular [this comment](http://forum.jogamp.org/MouseListener-mouseWheelMoved-and-Shift-tp4031233p4031247.html). I can reproduce this behavior, i.e.: releasing the right button when both left and right are pressed does not differentiate between which was actually released.
