### ISSUE TITLE
Ortho() + noSmooth()  + point() don't show anything

### ISSUE THREAD

**Issue by ragekit** [processing/processing#4374]
Hello all
It seems that since processing 3, using ortho combining with noSmooth and then trying to write point doesn't write anything to PGraphics (wether the main scene or an offscreen buffer)
Not using Ortho or nosmooth work fine though.

I'm on windows 10 using the processing 3.0.2

**Comment by codeanticode** [comment]
What strokeWeight() are you using? If the stroke weight is small and you are also placing points far from the camera, they might end up taking less than a pixel when drawn on the screen, in which case they won't be visible if smooth is disabled. This is due to how graphics are rendered by OpenGL, and not an error in Processing.
