### ISSUE TITLE
setTexture() does not work with imported OBJ Pshapes

### ISSUE THREAD

**Issue by paraclete-pizza** [processing/processing#4378]
A texture cannot be applied to PShapes created by loading a *.obj file. SetTexture() does work for shapes created by other means, however. Here is some example code, where I load in a model, and create a sphere, and apply the same texture to both. In this case, only the sphere has a texture.

```
PShape model;
PShape globey;
PImage pizza;

void setup() {
  size(500, 500, P3D);
  pizza = loadImage("pizza.jpg"); // load the texture
  model = loadShape("mammoth.obj");
  model.setTexture(pizza); //this does not work, the model is just black
  globey = createShape(SPHERE, 1000);
  globey.setTexture(pizza); //this DOES work. The sphere has a texture from pizza.jpg
  globey.setStroke(false);
}

void draw() {
    lights();
    directionalLight(51, 102, 126, -1, 0, 0);
    directionalLight(255, 0, 100, 1, 0, 0);
  scale(.1);
  shape(globey);
  shape(model);
}
```

![image](https://cloud.githubusercontent.com/assets/6827480/14128140/15aae202-f5ec-11e5-89b7-7044ad1729b0.png)

**Comment by codeanticode** [comment]
The .obj file needs to include texture coordinate data (UV values) for Processing to display the texture correctly. Built-in primitives have pre-calculated texture coordinates, that's why the texturing works on them.

Try setting an arbitrary texture in the Basics|Shape|LoadDisplayOBJ, and you will see it does work.
