### ISSUE TITLE
Communication over SPI on Raspberry-Pi

### ISSUE THREAD

**Issue by ANKITSHA** [processing/processing#4429]
I am trying to send and receive data over SPI using processing. Although i am able to transmite data using command adc.transfer() but  i am not able to receive data. Also proper documentation related to receive part is not available. If any one has idea about it or has worked on it please help.

**Comment by gohai** [comment]
Hi Ankitsha,

SPI is synchronous - so whenever you (the "master") sends a byte, you're at the same time also receiving a byte from the device you're talking to. The return value of the transfer() method is an array of bytes that got read in. Does this make sense to you?

If you're trying to communicate between two Raspberry Pis using SPI: this won't work, since both can only place the "master" role.

**Comment by gohai** [comment]
Closing. Feel free to re-open if needed.
