### ISSUE TITLE
Processing doesn't start

### ISSUE THREAD

**Issue by MaxZmys** [processing/processing#4565]
Hi,
I have install  Processing 3.1.1 under Windows 10, 64 bits. The software start and work the first time I have used it. But the next time, Processing doesn't start. When I click on it, a start-up screen appears during a few seconds, and nothing happens. I desinstalled and install again it, but I have the same problem.

Thank you in advance for you answer.

**Comment by MTPLLibrary** [comment]
I also have had this issue with the 64 bit version on a windows 7 64 bit machine.  The Banner comes up, disappears after 30 seconds and then, eventually the application launches after 5 minutes has passed.  I also tried to uninstall & reinstall, try the 32 bit version and lastly go back to version 3.1.  And each time, I still had the 5 minute launch issue.  Any help would be appreicated.

**Comment by gohai** [comment]
Do you see anything printed when you try to start Processing 3.1.1 from a terminal?

**Comment by MaxZmys** [comment]
Nothing else just the start up screen

**Comment by gohai** [comment]
What's the full path Processing is installed to? Anything special about
your username in C:\Users? (spaces, special characters?)

**Comment by MTPLLibrary** [comment]
The path was the default path.  I then tried reinstalling it to a more generic path C:\users\username\processing311 (taking out the dash and dots) and again same issue.  Are there any known conflicts?

**Comment by matinhus** [comment]
I'm using the Windows 10 Pro (64bits). The same issue was happening with me: crashing on startup, at the welcome screen, any button I clicked the program freezes. I tried to execute as administrator and so far it's working now. Haven't tried any complex sketch yet.

**Comment by liquidzym** [comment]
hey，did you using any vpn software? i had same issue b4,the java get crashed with proxy issue,can't recall what is.

**Comment by benfry** [comment]
Please use forum.processing.org for debugging startup issues. If you find something repeatable that's broken, please report it here. But since I'm not sitting in front of your computer, I can't help you with a report that "Processing doesn't start". 

More to the point, we now have three different, probably unrelated, reports here: 

* Processing doesn't start at all
* Processing starts after being stuck for several minutes
* Processing freezes on the welcome screen and cannot proceed

These are all likely different issues, so please report them when there's something for me to pursue, i.e. "when I'm using a proxy, it doesn't work." Or a separate issue that says "Processing only starts after a long delay... Here's my system setup." 

Thanks for your help in tracking these down.
