### ISSUE TITLE
PGraphics.text() takes unreasonably long time to execute

### ISSUE THREAD

**Issue by darthyoshi** [processing/processing#4567]
Processing 3.1.1
Linux kernel 4.5.7-202.fc23.x86_64 (Fedora 23)
Java 1.8.0 update 92 (openJDK)

The first time that PGraphics.text() is called, it takes ~20s to execute. All subsequent calls execute immediately, even if invoked by a different PGraphics object. This is auboptimal, but still workable, from the Processing editor, but standalone applications (sketches exported from Eclipse, for instance) will time out.

Demo code:
[textTest.txt](https://github.com/processing/processing/files/355492/textTest.txt)

.

**Comment by gohai** [comment]
Does the same happen with Oracle's JVM? Did earlier versions of Processing behave the same?

**Comment by darthyoshi** [comment]
Yes, the same thing happens with the latest Oracle JVM (1.8.0 update 91) as well. I only recently started seeing this a couple of days ago, so this definitely wasn't an issue with previous versions of Processing. I also tried this on Windows with the latest Oracle JVM, and that worked fine.

**Comment by gohai** [comment]
Could you perhaps try some older versions of Processing and give us a rough idea which version made it so much slower?

**Comment by GKFX** [comment]
The first call to `text()` is usually slowed down by `defaultFontOrDeath()`. Can you time that instead of the first `text()`? The next `text()` should be sped up by having `defaultFontOrDeath()` called first. You'll need my [test code, DfodTest.pde](https://github.com/processing/processing/files/356031/DfodTest.pde.txt), as it's a protected method. On my Linux system, `defaultFontOrDeath()` only takes 400-500ms.
If `defaultFontOrDeath()` is the culprit, then you've got a problem with loading the font Lucida Sans. Are you likely to be loading it over a network? Can you work around it by creating a .vlw font from Tools → Create Font and loading that instead?

**Comment by darthyoshi** [comment]
Yep, the culprit is `defaultFontOrDeath()`. Explicitly loading a custom PFont and passing it to `textFont()` appears to fix it. I wonder why Lucida Sans isn't being loaded.

**Comment by ihsanyounes90** [comment]
I have the same issue, for me calling PGhraphics.text() is always slow.
Looking at the code I've seen that it uses a long logic to calculate the correct positions and then display one pice at time, which causes calling N times text() primitives of the current native PGhraphics. 
A hook i did in my code to resolve this issue is directly call java.awt.Graphics2D.drawString(), with this I got 10x faster performance in text().

**Comment by benfry** [comment]
@darthyoshi You may have a bad font on your system if it's taking that long. We have to call `getAllFonts()` there to deal with cross-platform differences in how fonts are named. Otherwise, it wouldn't be possible to specify fonts by name and have them work across different platforms (OS versions, versions of Java, etc).

@ihsanyounes90 That's a different issue; if you have examples of the problem, file them as bugs so that they can be fixed.

**Comment by benfry** [comment]
Found some ways to improve this performance for the next release (3.4.1 or 3.5).

**Comment by benfry** [comment]
With 3.5, I believe we've fixed this as well as we can, however I can still reproduce *very slow* behavior when a lot of (>500) fonts are installed on macOS. It's a [Java bug](https://bugs.openjdk.java.net/browse/JDK-8179209) so we'll have to keep an eye on that.
