### ISSUE TITLE
"cannot reduce visibility" of an inherited method in an inner class

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#4583]
When we use interface, Processing display an error ''''Cannot reduce the visibility of the inherited method...```` happyness the sketch run good. I use the example to show this error message https://processing.org/reference/implements.html
![capture d ecran 2016-07-23 a 17 12 20](https://cloud.githubusercontent.com/assets/3332269/17078667/1718524c-50f9-11e6-9b77-bd43cd9d5359.png)

**Comment by benfry** [comment]
As a workaround, add `public` to the different versions of `move()` (and `display()` for that matter).

**Comment by JakubValtar** [comment]
@benfry Is this code supposed to run? Adding public to methods in inner classes is not a feature we support. Rather it's caused by "dumbness" of the method regexp, which adds public to all void methods. If you change return type to something else then void it won't work. I'd mark this as an enhancement.

**Comment by benfry** [comment]
@JakubValtar The problem is that `public` is being added to some methods not others... So in this case, it appears that `move()` inside `Dot` has `public` added, but the same isn't happening in `CircleDot` and `SquareDot`. 

Not sure what you mean re: return types changing—I don't see that in the code here.

**Comment by JakubValtar** [comment]
@benfry Ah, sorry about the return type. I thought about a wrong regexp.

Is the preprocessor supposed to add `public` to _all_ methods without a visibility modifier? Problem here is that the error checker leaves inner classes alone, while the old preprocessor goes inside.

Should I modify the error checker to visit inner classes when adding `public`? Right now it adds it only to top-level methods.

**Comment by benfry** [comment]
Yeah, if that's what we were doing before, by all means.

**Comment by benfry** [comment]
Fix incorporated for 3.1.3.
