### ISSUE TITLE
Version 3.2 won't run from paths with spaces on Windows

### ISSUE THREAD

**Issue by kmwright** [processing/processing#4623]
On startup the About box is displayed and then Processing quits.

**Comment by TerribleKraal** [comment]
Hi ! I can tell that it is also the case for me on windows 8.1 64-bits.

It is a laptop with 2 graphic cards (optimus from Nvidia) 1 GT750M and 1 Intel HD4600 (which is inside the Core i7), if it helps.

**Comment by benfry** [comment]
Working fine here. Have you tried anything from the Troubleshooting instructions? 
https://github.com/processing/processing/wiki/Troubleshooting

<img width="1392" alt="screen shot 2016-08-18 at 9 59 25 am" src="https://cloud.githubusercontent.com/assets/1623101/17776419/7d71bd5e-652a-11e6-96ca-8cb14eaa1d69.png">

**Comment by TerribleKraal** [comment]
Hi,

I am ashamed, I did not read the troubleshooting section first. I will try what is described there and will report if success or not.

Have a nice day

**Comment by benfry** [comment]
You're not the first—we need to figure out how to make it more accessible and obvious for folks. It's possible that you're hitting [this bug](https://github.com/processing/processing/issues/4626) and it's preventing the software from starting on your machine. If so, I'll be posting a fix soon. If not, please report back if you find anything!

**Comment by kmwright** [comment]
On startup the About box is displayed and then Processing quits.

I tried deleting Users → myusername → AppData → Roaming → Processing → preferences.txt -- didn't help.

Ran C:\Users\...mypath...\processing-3.2\processing.exe --l4j-debug, got the following output:

Version:	3.8
CmdLine:	C:\Users\...mypath...\processing-3.2\processing.exe --l4j-debug
WOW64:		yes
Working dir:	C:\Users\...mypath...\processing-3.2\.
Bundled JRE:	java
Check launcher:	C:\Users\...mypath...\processing-3.2\java\bin\javaw.exe (OK)
Heap -Xmx:	Requested 256 MB / 0%, Available: 3590 MB, Heap size: 256 MB
Substitute:	EXEDIR = C:\Users\...mypath...\processing-3.2
Add classpath:	lib\pde.jar
Add classpath:	core\library\core.jar
Add classpath:	lib\jna.jar
Add classpath:	lib\jna-platform.jar
Add classpath:	lib\antlr.jar
Add classpath:	lib\ant.jar
Add classpath:	lib\ant-launcher.jar
Launcher:	C:\Users\...mypath...\processing-3.2\java\bin\javaw.exe
Launcher args:	-Xmx256m -Djava.ext.dirs=C:\Users\...mypath...\processing-3.2/java/lib/ext -Djna.nosys=true -Djna.boot.library.path=lib -Djna.nounpack=true -classpath "lib;lib\pde.jar;core\library\core.jar;lib\jna.jar;lib\jna-platform.jar;lib\antlr.jar;lib\ant.jar;lib\ant-launcher.jar" processing.app.Base
Args length:	304/32768 chars
Exit code:	1

Other suggestions on the troubleshooting page don't help.

**Comment by benfry** [comment]
What happens if you put the folder into a location with no spaces? For instance, in the root of your C:\ drive instead of your user directory or Program Files?

**Comment by kmwright** [comment]
Ok I moved the whole package to C:\processing-3.2 and guess what, it starts up ok! Not sure whether to call this a bug, or a feature... Obviously 3.2 doesn't like spaces in filenames, but 3.1.2 had no problem with that.

**Comment by benfry** [comment]
Definitely a bug... It's a regression due to the fix for #4608, which ironically is about fixing a whole host of other startup problems. I'll try to get a 3.2.1 release out shortly. Thanks for testing...

**Comment by Phlosioneer** [comment]
Why was a bug this noticeable advertised on the download page as a _stable_ build? If @benfry is right, and it's because of #4608, then there were 13 days to test this bug. If no one tried to put it in program files during that time, then everyone must be using a development environment to test processing builds. I don't contribute to this project, so I don't know much about how testing and releasing is done, but going straight from the repo to a stable build on the processing homepage _seems_ like a bad idea.

**Comment by benfry** [comment]
@Phlosioneer Because @benfry is doing this in his free time and is neither omnipotent nor does he have an infinite amount of time to test releases, so sometimes problems—even obvious ones—are missed. Or put another way, during those 13 days, there wasn't a single person using Windows who was working with the code to notify me or anyone else of a problem. Suffice to say, complaining about it won't make more volunteers show up, nor motivate those who *are* working on it to spend more time.

**Comment by Phlosioneer** [comment]
My apologies. I'm too used to projects with larger contributers.
