### ISSUE TITLE
Could not find required fonts.  Please Re-install Processing

### ISSUE THREAD

**Issue by nbregman17** [processing/processing#4634]
Pops up on launch.  Brand new install of unbuntu.  Reinstalled processing and got the same error message.

**Comment by GKFX** [comment]
Can you double-check what Java executable you're using? With Processing just having been opened, the procedure is [here](http://askubuntu.com/a/49030/309061), typing `java` instead of update-notifier. It should be `<processing install location>/java/bin/java`, and  then `<processing install location>/java/lib/fonts` should contain the following:
````
AnonymousPro-Bold.ttf
AnonymousPro-LICENSE.txt
AnonymousPro-Regular.ttf
Carlito-Bold.ttf
Carlito-LICENSE.txt
Carlito-Regular.ttf
fonts.dir
LucidaBrightDemiBold.ttf
LucidaBrightDemiItalic.ttf
LucidaBrightItalic.ttf
LucidaBrightRegular.ttf
LucidaSansDemiBold.ttf
LucidaSansRegular.ttf
LucidaTypewriterBold.ttf
LucidaTypewriterRegular.ttf
SourceCodePro-Bold.ttf
SourceCodePro-LICENSE.txt
SourceCodePro-Regular.ttf
SourceSansPro-LICENSE.txt
SourceSansPro-Regular.ttf
SourceSansPro-Semibold.ttf
````
If either of those things isn't true, that's the problem.

**Comment by benfry** [comment]
Make sure you're using the latest version of Processing—I don't think this message is even present in the current release.

**Comment by GKFX** [comment]
This message is still in Toolkit.java and it works; I got it to appear when I was writing the advice above.

**Comment by benfry** [comment]
Sorry, I misspoke—this should be fixed in the next release with some changes to how fonts are handled. (See https://github.com/processing/processing/pull/4639)
