### ISSUE TITLE
println(int(byte(245))); throwing error

### ISSUE THREAD

**Issue by x13420x** [processing/processing#4652]
println(int(byte(245)));
Throws error **_error in"byte"**_
but it does seem to work 
this error has existed for at least 3 months now

**Comment by JakubValtar** [comment]
Hi @x13420x, thanks for the report! We'll fix it.

_Note for myself: SourceUtils.java, TYPE_CONSTRUCTOR_REGEX does not handle two immediately following type constructors without any other character in between, because last non-capturing group of the first match overlaps with the first non-caturing group of the next potential match. TODO: Figure out how to get around this or run the regex multiple times._

**Comment by x13420x** [comment]
It wasn`t doing this on P3.02  It started with the mothers day p3.10

**Comment by JakubValtar** [comment]
That's correct, we got a new error checker in 3.1 :)
