### ISSUE TITLE
Processing 2 does not run alongside Processing 3 on OS X

### ISSUE THREAD

**Issue by jeremydouglass** [processing/processing#4676]
I'm not sure if this is by design, or an unintended behavior.

**Steps to reproduce:** (tested on OS X 10.10.5 Yosemite)

1. Install Processing 3.2.1 into Applications folder as "Processing.app"
2. Install Processing 2.2.1 into Applicaitons folder as "Processing 2.app"
3. Launch Processing 3
4. Launch Processing 2

**Unexpected behavior:**

When Processing 2 is launched, it spawns a new sketch window **in the open Processing 3 app**, then it immediately quits (leaving the new sketch open in 3).

Perhaps this is by design? However, if I just launch Processing 2 while Processing 3 is not running, then Processing 2 runs as expected.

I encountered this issue when seeing a [report on the forum](https://forum.processing.org/two/discussion/17997/processing-2-2-1-can-t-start-in-mac-osx-el-capitan-java-8) of Processing 2.2.1 not running on OS X 10.11 El Capital.

**Comment by sonic414** [comment]
From https://github.com/processing/processing/wiki/Changes

If you try to run more than one copy of Processing at a time, it will steadfastly refuse (and simply quit again). This isn't quite complete yet. Instead of just quitting the application it needs to bring the existing application to the front, and/or open the document you were trying to open with a new instance of Processing. But this will be sorted before 2.0 is released.

I believe this is by design.

**Comment by jeremydouglass** [comment]
Ah -- in that case it appears this is by design. If so this should be closed.

**Comment by benfry** [comment]
Yes, by design. It does that mostly so that more than one copy of the same version isn't running at the same time, but a side effect is that it prevents 2.x and 3.x from running simultaneously. Having more than one copy running at a time is asking for trouble, and invites a whole set of obscure issues that would be really difficult to track down.

**Comment by mitical** [comment]
Hi, I am not able to run any version of Porcessing in Capitan OSX. I already put down the System Integrity Protection and reboot. Processing launches but it vanish. Did not happen before with my old OS. Java 8. Do I need to install processing-java to work?  Can anyone help? Thanks.

**Comment by benfry** [comment]
@mitical That has nothing to do with this issue; please file a new issue if you've found a bug, or use the forum for general questions like that.
