### ISSUE TITLE
Does processing support armv7l ?

### ISSUE THREAD

**Issue by jiapei100** [processing/processing#4699]
Hi, all:

From [https://processing.org/download/?processing](https://processing.org/download/?processing), it's clear that processing supports **ARMv6hf**, but how about raspberry pi's architecture, say: **armv7l**?

Cheers
Pei

**Comment by gohai** [comment]
Yes. ARMv7 is backwards compatible with ARMv6 code. We picked armv6hf as the baseline, because the Raspberry Pi Foundation does the same in their *Raspbian* distribution. (The original Raspberry Pi as well as the Raspberry Pi Zero both have ARMv6 cores in them.)

If your question pertains to OpenCV with Processing on the Raspberry Pi: you can download a modified library that works [here](https://github.com/processing/processing/wiki/Supported-Platforms#library-opencv). There is a pull-request for getting this incorporated into the opencv-processing library: https://github.com/atduskgreg/opencv-processing/pull/88

Feel free to re-open if you come across a specific issue, for general questions like this one please use our [Forum](forum.processing.org/two/categories/raspberry-pi).
