### ISSUE TITLE
frameRate() below 1 fails for P2D & P3D

### ISSUE THREAD

**Issue by GoToLoop** [processing/processing#4716]
``` pde
void setup() {
  //size(800, 600, JAVA2D); // JAVA2D works w/ below 0 frameRate().
  //size(800, 600, FX2D); // FX2D works w/ below 0 frameRate().
  size(800, 600, P2D); // P2D doesn't work w/ below 0 frameRate()!!!
  //size(800, 600, P3D); // P3D doesn't work w/ below 0 frameRate()!!!

  frameRate(.5); // below zero argument.
}

void draw() {
  background((color) random(#000000));
}
```

**Comment by codeanticode** [comment]
This is due to a limitation in JOGL's FPSAnimator, which we are currently using to drive the rendering loop in the OpenGL renderer and only accepts an [integer fps](https://jogamp.org/deployment/jogamp-next/javadoc/jogl/javadoc/com/jogamp/opengl/util/FPSAnimator.html#setFPS(int)). We would need to file an upstream issue with JOGL or consider other alternatives for controlling the framerate.

**Comment by GoToLoop** [comment]
Oh, I got it!

**Comment by GoToLoop** [comment]
Dunno why "under P3" was removed from the title, since it implies it WORKS under P2!
On 2nd thought, why would it work for all renderers under P2 but fail under P3?
Clearly the approach used under P2 was compatible fro all renderers, no matter whether they were OpenGL-based or not.

**Comment by benfry** [comment]
@codeanticode Can you just have it return an error or warning in that case? Probably capping the minimum rate at 1 and using `showWarning()` when it's lower would be the right approach. (Rather than halting the sketch with an error in that case.)

**Comment by codeanticode** [comment]
Ok, done in https://github.com/processing/processing/commit/2a77ed8ff9149381f208b836c9676afcda4719e6

**Comment by benfry** [comment]
Cool, thanks.
