### ISSUE TITLE
pre() doesn't get called consistently among renderers

### ISSUE THREAD

**Issue by nakednous** [processing/processing#4721]
just run the following sketch to reproduce the issue:
```java
//Choose P2D or JAVA2D
//with P2D pre() gets called continuously
//with JAVA2D pre() gets called only once
String renderer = P2D;
    
void setup() {
  size(200, 200, renderer);
  registerMethod("pre", this);
}

void pre() {
  println("pre() called @" + frameCount);
}
```

which one is the supposed expected behavior?

**Comment by benfry** [comment]
That's two different bugs, actually. The `JAVA2D` implementation is correct, however:

1. There's a bug in your code… Because you don't have a `draw()` method, your sketch halts once `setup()` is finished.

2. That means `P2D` also has a bug where it's not correctly halting after the first `draw()` call. That's now filed as https://github.com/processing/processing/issues/4722
