### ISSUE TITLE
Error if Client not available in processing.net.*

### ISSUE THREAD

**Issue by jewe** [processing/processing#4764]
The example https://processing.org/reference/libraries/net/Client.html works without an error if the Client is not available:

```
import processing.net.*; 

Client myClient; 
int dataIn; 
 
void setup() { 
  size(200, 200); 
  // Connect to the local machine at port 5204.
  // This example will not run if you haven't
  // previously started a server on this port.
  myClient = new Client(this, "127.0.0.1", 5204); 
} 
 
void draw() { 
  if (myClient.available() > 0) { 
    dataIn = myClient.read(); 
  } 
  background(dataIn); 
} 
```

But if you add the command 
`size(1200, 700, P3D);
  frameRate(15);
`
it throws an error:
`Waited 5000ms for: <f268a27, 1e175b3>[count 2, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] ...`

Tested with Processing 3.1.1

**Comment by gohai** [comment]
I believe this is somewhat expected - the 3D drawing part of your code times out while the program is stuck connecting to the port that nobody answers. Could be done perhaps a bit more elegant, but you would hopefully not see this all to often.

**Comment by benfry** [comment]
Yeah, this isn't really a bug… You're starving the main animation loop for several seconds while it's unable to connect. Possible fixes include 1) connecting to something that exists or 2) running the connection code in another thread that can send an update to the main drawing loop. The "Waited 5000ms" message is just a warning coming from the OpenGL library we use, so it's out of our control (and usually helpful—since as you can see here, it's telling you that the sketch is frozen).
