### ISSUE TITLE
IDE debug stepping key short-cuts not working

### ISSUE THREAD

**Issue by timescale** [processing/processing#4804]
Using the key short-cuts to debug (Ctrl+J and Ctrl+Shift+J) put newlines into the code.  Ctrl+Alt+J does not.  The debug command does run but it litters the code with newlines.

Processing 3.2.3, on Windows 10.

**Comment by joelmoniz** [comment]
I can reproduce this from the current source on Windows 10. Also, placing the cursor in between a line before hitting `Ctrl+J` or `Ctrl+Shift+J` makes the new line start from the cursor.

The error broadly seems to be because the auto-indent code gets erroneously called in the [handlePressed()](https://github.com/processing/processing/blob/0abee5af6ad3b11cf2b73bb794b8a97c157c4762/java/src/processing/mode/java/JavaInputHandler.java#L62) method. I'm working on narrowing down the exact cause, and should hopefully have a fix in soon.

**Comment by timescale** [comment]
Thanks for looking into it Joel, as a fellow programmer (though not proficient in Java [yet?] )I know that replicating the bug is at least half of the battle.

**Comment by benfry** [comment]
Duplicate of https://github.com/processing/processing/issues/3830
