### ISSUE TITLE
How to do imports with Processing?

### ISSUE THREAD

**Issue by Qwerp-Derp** [processing/processing#4835]
I have two `.pde` files, in two separate folders:

    sketch
    - sketch.pde
    other
    - button.pde

I want to separate my class files from my other files, but I can't include them if I do that, without building first. Is there no way to "import" `button.pde` before building the actual Processing files?

I know this issue has been brought up in the past (and closed immediately), but I believe that this is actually useful if it's not implemented.

**Comment by benfry** [comment]
So when the issue was brought up and closed, what was said at the time? 

The PDE is meant to be a very simple editor that covers the vast majority of what people want to do. We trade ease of use for keeping things minimal. What you describe would be better handled by a full-featured Java IDE. I'd recommend you use one of those.
