### ISSUE TITLE
classNotFoundException:processing.awt.PGraphicsJava2D;

### ISSUE THREAD

**Issue by honeyraghu2495** [processing/processing#4838]
I get this error when i try to run the ads1292r sketch.
I do not know where is that processing.awt package is missing.
Please help me with this issue asap.

**Comment by GKFX** [comment]
I assume you mean the sketch at https://github.com/Protocentral/ADS1292rShield_Breakout/tree/master/Processing. I don't see anything in that sketch that is obviously the fault. The class `processing.awt.PGraphicsJava2D` is part of the core Processing library so you shouldn't be seeing this error because that class should always be available. What version of Processing are you using? Also, are you working in the default Processing IDE, in Eclipse, or something else?

**Comment by benfry** [comment]
This isn't a Processing bug; someone has set up a project incorrectly. Probably trying to use core.jar from 2.x with code that's been written for 3.x.
