### ISSUE TITLE
Huge memory leak with image() and its input looped

### ISSUE THREAD

**Issue by dzaima** [processing/processing#4858]
Windows 10 & Processing 3.2.3
When 'image()' is called with a new image or PGraphics it creates a memory leak.
If `image()` doesn't exist its fine, if the `frame` creator is in setup, its fine, but both in a loop aren't.
```Processing
void draw() {
  PGraphics frame = createGraphics (500, 500);
  image (frame, 0, 0);
}
```

**Comment by JakubValtar** [comment]
Hi, thanks for your report, but this is not a memory leak. Memory leak happens when a program does not release some unused memory properly. Our code is working alright, everything is properly collected. 

However, by running your code, you are creating 60 MB of image data every second, which means a lot of memory is wasted.

Why do you want to do this? You should be reusing one PGraphics instead of creating a new one 60 times per second. Your sketch will be much faster and use less memory that way.

```processing
PGraphics frame;

void setup() {
  size(500, 500);
  frame = createGraphics(500, 500); // create only one PGraphics
}

void draw() {
  frame.beginDraw();
  frame.background(0); // clear frame to black
  // draw whatever to frame
  frame.endDraw();
  image(frame, 0, 0);
}
```

For more coding questions, please ask at [the forum](https://forum.processing.org/two/).

**Comment by dzaima** [comment]
I know how to fix it, but just saying that someone new to processing would make something like that and after a couple minutes wonder why their computer is freezing up.
There also isn't anything holding those images in memory - even a weakReference to it in `image()` doesn't help. Those 60MBs every second could be easily deleted is what I'm saying.

**Comment by JakubValtar** [comment]
They are being deleted. Garbage Collector clears then during the next collection. Your example sketch runs without a problem. Memory stays in the range of 100-250 MB.

So what happens when you run the example sketch you posted? You said it's not fine. Could you please go into more detail what is the problem?

We can add a line to the reference saying that people should reuse existing PGraphics instead of creating new one every time, but I think that's all I can do I this case.

**Comment by dzaima** [comment]
I guess I never ran this particular example for very long, trough it does sit at around 1.7 gigs idle (I assume that the garbage collector kicks in then).
The project where I found this, however, used up all the ram available (and the pagefile I assume), didn't seem like the garbage collector was doing its work. I almost had to restart my PC to kill the process.

**Comment by JakubValtar** [comment]
If you start the sketch with a large heap and start creating large objects, garbage collector will adapt and use all the heap available, collecting less frequently. If you set the heap larger than your available RAM, then yes, you pc can run out of memory.

In Task Manager it looks like the ram usage is constant, because that's what is reserved by the Virtual Machine. However, if you look inside the heap with VisualVM or other profiler, you'll see that the amount of used heap is jumping up and down like crazy as you abuse the memory and garbage collector is keeping up.

System.gc() is not a good tool to fix your bad code. If you have to use it, it usually means you are doing something wrong. If you do this correctly as I shown you, you end up with 70 MB heap and constant 10 MB used heap.

I recommend starting up jvisualvm.exe, which is a part of JDK, and checking out yourself how often GC runs and how much heap is used.

If you want to know more, please ask at the forum https://forum.processing.org/two/
