### ISSUE TITLE
Warn user to use L when creating a number constant that won't fit into an int

### ISSUE THREAD

**Issue by pxgator** [processing/processing#4878]
Processing's support for the 'long' data type is mostly useless. The statement like:
long c = 55666777888 is not allowed..?? It would be nice if the next edition would
support the use of 'long' in functions.

**Comment by gohai** [comment]
Interesting. It does work when postfixing the literal with `l`, like so

    long c = 55666777888l;

Perhaps this hint could simply added to the [documentation](https://processing.org/reference/long.html)? Or the error message? ("The literal 55666777888 of type int is out of range")

**Comment by pxgator** [comment]
Interesting indeed....I'm wondering why Processing doesn't support 'long' like Java 8 does ?

**Comment by JakubValtar** [comment]
Processing supports `long` exactly like Java 8 does, `long c = 55666777888;` should not compile in any Java IDE (integer number too large).

We should show a better error message (number is too large for `int`,  suffix it with `L` to make it `long` literal).

I would be against preprocessor adding `L` automatically, because then people are going to have other problems, e.g. when assigning to `int` they would have to cast to int manually or numbers would overflow.

**Comment by pxgator** [comment]
Thank you for the information Jakub.

**Comment by benfry** [comment]
Changing the title to reflect the actual issue.

**Comment by benfry** [comment]
Fix incorporated for the next release (3.4 or 3.3.4).
