### ISSUE TITLE
Could not initialize class com.sun.jna.Native on startup

### ISSUE THREAD

**Issue by emma666** [processing/processing#4929]
it shows  "A serious problem happened during startup...", I attached the problem screenshot, please check it. 
![processing screenshot](https://cloud.githubusercontent.com/assets/25942762/23193873/feecc28a-f8e5-11e6-8850-4fcc0b13236f.png)

Thanks

**Comment by gohai** [comment]
@emma666 Thanks for your report.
Are you running a 64-bit or 32-bit OS? Are you running the 64-bit or 32-bit version of Processing?

Could you go back and see if earlier versions of the software start up for you?

**Comment by emma666** [comment]
64bit, I tried to use processing2.0(Iused it last year), but it comes up with another problem,"it requires a 1.6 compliant jvm", I have no idea what should.I do now?
Shall I use windows10? then the problem can be solved?
Thanks

?取 Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by gohai** [comment]
@emma666 Try those versions:
https://github.com/processing/processing/releases/tag/processing-0256-3.2.4
https://github.com/processing/processing/releases/tag/processing-0248-3.0.2
And please report back if any of those work!

You are running a 64-bit version of Windows 8? (Just checking)

**Comment by emma666** [comment]
Hi， Thanks. None of those versions work on my computer. My computer is 64bit Windows8.



________________________________

**Comment by emma666** [comment]
Hi ,


I just reinstalled Java7, and Processing2.2 works, all the other versions couldnot work with this java version.


But at least I can start my job now although using the old version, hope my information can help you to improve the Processing Tech, Many  thanks for your efforts.



________________________________

**Comment by gohai** [comment]
@emma666 Thanks for your message. Processing 2.2 is very old, though...

You could try installing Processing 3.3 into a path that doesn't contain spaces, or extended (non-"Western") characters. Like `C:\Processing\`. Does this help?

**Comment by benfry** [comment]
Comments from @gohai about how to debug: https://github.com/processing/processing/issues/4996#issuecomment-292806777

**Comment by jeremydouglass** [comment]
We're seeing more of these error reports -- the thing they have in common is displaying the "was not meant to be" / "a serious problem" error message dialog:

https://github.com/processing/processing/blob/f65616ae74b97ffc1762380141b7dbfe9cca4693/app/src/processing/app/Base.java#L120

Some seem to be Windows specific might be related to attempts to run while the Processing download still inside the zip (Windows now makes it harder for some users to understand what a zip even is, as it can browse straight into them without expanding first as if they are normal folders).

**Comment by gohai** [comment]
@jeremydouglass Agree - would be nice to sort this out, or change the messaging to be more clear about what steps the user should take to make it work.

Besides executing while it being ZIPed, the other lingering suspicion I got while triaging issues was that any extended characters in the path (e.g.: username) could be an issue. Not sure this would specifically explain the _It was not meant to be_, but it's at least an issue for setting the `java.library.path`, as reported [here](https://github.com/processing/processing/issues/5511).

**Comment by RegisLeRoy** [comment]
problem is linked to the installation. If you install windows defender detects some mallware. SO i think it removes some of the necessary files. I had no problem with previous installs (3.3.6 fi) on the same machine, but i have the same problem installing 3.3.7

**Comment by tymonaghan** [comment]
Hi, this is my first time contributing to an issue on GitHub so apologies and please do let me know if I'm doing anything incorrectly.

I recently encountered this same "It was not meant to be" error. I am on Windows 10, 64-bit, using the 64-bit version of Processing. I can confirm that I unzipped the Processing files, they were living in c:/program files. I have been using that install quite often for at least a few weeks.

When I went to work with Processing today the exe would not start and I got the "It was not meant to be" error, simultaneous with Windows notifying me of a threat detected. Below I have pasted the screen from the Windows Defender Security Center that I hope will be helpful. It seems core.jar is being recognized as a Trojan by Windows. 

"Restoring" the file through the Security Center seems to solve the issue for me. Also, the 32-bit version of Processing does include core.jar, but Windows is not recognizing any threats when I scan it. I'll try an offline scan and the malicious software removal tool and update if anything changes, but it seems the issue is just with the 64-bit install. 

![image](https://user-images.githubusercontent.com/33797221/41495255-a183e700-70e8-11e8-87fd-ea754b5096c3.png)

**Comment by benfry** [comment]
Added an extra check for this in 3.4.
