### ISSUE TITLE
textLineImpl() float coordinates as int

### ISSUE THREAD

**Issue by 239** [processing/processing#4941]
The coordinates in `processing.awt.PGraphicsJava2D.textLineImpl(char buffer[], int start, int stop, float x, float y)` are casted to integers, leading to wrong offset:

`g2.drawChars(buffer, start, length, (int) (x + 0.5f), (int) (y + 0.5f));`
![text_int](https://cloud.githubusercontent.com/assets/7075008/23567665/a4240df8-0057-11e7-8f17-b967631d925c.png)

This looks better (and draws not the same with scaling):

`// better to use drawString() with floats? (nope, draws the same)`
`      g2.drawString(new String(buffer, start, length), x, y);`
![text_float](https://cloud.githubusercontent.com/assets/7075008/23567668/a7d7ca84-0057-11e7-8744-ecead9124af1.png)

**Comment by benfry** [comment]
I'll have to check, but I believe the use of ints there is a tradeoff between text that moves having a rippling effect as it moves around the screen while animating versus really extreme cases like this one where you've apparently used `scale()` in a way that's going to cause terrible placement. 

You've not shared your code but it's not clear why you wouldn't be using a larger text size in this example, rather than intentionally breaking the placement.

**Comment by 239** [comment]
Why is it considered an extreme case that causes wrong placement? I just tried to achieve the same proportions for text and geometry regardless of the dimensions, so I used `scale()` for convenience:

```scala
translate(ox, oy)
scale(sf, sf)
for (x <- 0 until L.width)
  for (y <- 0 until L.height) {
    pushMatrix()
    translate(x, y)
    fill(111, 111)
    ellipse(0, 0, 1, 1)
    rect(0.1f, 0.1f, 0.8f, 0.8f)
    fill(222, 111)
    text(('!' + x + y * L.width).toChar, 0.5f, 0.3f)
    popMatrix()
  }
```
I could scale text, object and stroke size manually but I don't see the advantages.
![text](https://cloud.githubusercontent.com/assets/7075008/23581719/f51b15fe-0119-11e7-92bb-a95d899dbfa6.png)

By the way, I can't find the reason for the white border on the right side (only in JAVA2D).
Should I open a new issue for that?

**Comment by benfry** [comment]
Confirmed that this is about the rippling effect that happens when text is moved using decimal values. That issue is far more problematic, and far more likely to be seen by average users than this specific case where tiny text sizes and drastic `scale()` commands are used for placement. Just one of those tradeoffs we have to make. 

Luckily, you can work around it by not using `scale(100)` or `scale(1000)` as seen here.
