### ISSUE TITLE
Arabic characters not supported in default fonts used in the PDE

### ISSUE THREAD

**Issue by 11maxed11** [processing/processing#4944]
Hey,
I am working on adding Arabic translation to Processing. Most things get viewed correctly. However, some of them (as viewed in the picture) are not. Any idea on the reason behind that, and whether a quick fix exists for that?

![capture](https://cloud.githubusercontent.com/assets/3680307/23592954/b694b192-0208-11e7-9833-2a36316a7d93.PNG)

![untitled2](https://cloud.githubusercontent.com/assets/3680307/23592955/b696b398-0208-11e7-95db-2cb57c323f6c.png)

Any notes on the support for Right-to-Left languages in Processing?

**Comment by 11maxed11** [comment]
@benfry Hello, do you have any thoughts on this? If the reason cannot be pointed out, I can do a partial translation that involves all the parts that work and leaves out the errors, in addition to providing a full translation document to be used later on --if the issue gets fixed.

**Comment by benfry** [comment]
Thanks for looking into it. The issue with the boxes is that the built-in font (Source Sans Pro) doesn't have Arabic characters, so we need to figure out how to set a [fallback](https://docs.oracle.com/javase/8/docs/technotes/guides/intl/font.html) font when the characters are out of range. It looks like it involves messing with these [configuration](https://docs.oracle.com/javase/8/docs/technotes/guides/intl/fontconfig.html) files, though it'd be nice to figure out if we can handle it from code.

Assuming you're not looking to dive into that part of it, though, some ideas to get things moving:

* If you modify `lib/theme.txt` and swap `processing.sans` with `Dialog`, more of those characters should start working
* If some, but not all, are working, please report back and I'll make sure that all of them can be edited from that file so you can continue your work

Longer-term, I'm not sure what sort of right-to-left issues we might have, since we use many custom components in the interface, but I'd love to see how far we can get without requiring a huge rewrite. (The editor text area, I can almost guarantee, is unlikely to be happy about RTL rendering, for instance.)

Let me know how it goes!

**Comment by 11maxed11** [comment]
Hey!
Thanks for the support. I am willing to look further into this.
I'll do the experimentation advised by you, and try to get some clear results while solving any issues along the way. I'll also try to check how well RTL languages are handled and highlight the result, so we'll see how well can this go with the current codebase.

**Comment by 11maxed11** [comment]
I went ahead and submitted a PR with the translation file in PR #4970 . This problem can be addressed later in a separate PR.
I'll hopefully try to work on solving this issue once I get some free time in ~6 weeks

**Comment by benfry** [comment]
This should be fixed for 3.3.1, which will also includes your translation. Check it out!

<img width="772" alt="arabic working" src="https://cloud.githubusercontent.com/assets/1623101/25315894/db854334-282a-11e7-8386-894c35393528.png">
