### ISSUE TITLE
Processing Impacting Apple iMac login 

### ISSUE THREAD

**Issue by RichieMcMullen** [processing/processing#4949]
Everyday I switched on my iMac it would take 5 to 10 minutes to startup / login. I just couldn't figure it out. This drove me NUTS for a few days, until I discovered what it was. I've just noticed that when I'm NOT working on a processing application, my mac starts up without any issues, 30 seconds max.

But when I do work on a processing app and run it multiple times to test, view what I've created etc.... once I shut down the mac it takes 5 to 10 minutes to start it up again. Its pretty obvious that whatever the processing app or the functionality of the processing app is causing issues with the system startup.

As a back up test to try an replicate this issue, I tested the same scenario on a 2nd iMac, which produced the exact same results, 5 to 10 minutes startup time, sometimes longer.

Both iMacs running "macOS Sierra"

I hope this is looked into.

Regards,
Richie

**Comment by gohai** [comment]
@RichieMcMullen Is this when the Processing application (IDE) is being loaded upon startup, or, when an application/sketch that you've created with Processing is being loaded?

Trying to clarify, since we've #4783 that concerns the startup time of P3D application/sketches. But I haven't heard of anything like this affecting the IDE.

**Comment by benfry** [comment]
Processing does nothing when you start your Mac or log in to your account. In fact, it cannot do anything when you start up, because we have no way of controlling what happens when your Mac starts up. Doing so would either require 1) an installer (which Processing does not use), or 2) your password to add Processing.app to your login items (we don't ask for your password). 

The only thing that could affect startup time is if you manually added it to System Preferences > Users & Groups > Login Items, but we're certainly not doing that.

**Comment by RichieMcMullen** [comment]
@gohai No. Let me give you a scenario. I start up my iMac, I then begin a new processing project and start working on it. After I'm finished working on the project I save it, and shutdown my iMac.

Here's where the problem is.... This next time I try tarting up my iMac it takes 5/10/15 minutes to boot into the login screen of my actual iMac. This only happens If I have been using "Processing" before the iMac was last shutdown.

I know, its really strange and I dont know why its happening. And again, this issue is happening on both my iMac's that are both running macOS Sierra.

@benfry I understand that, but based on my scenario I'm assuming that "processing" is doing something when its being used which then has an affect on the machine when re-booted.

**Comment by gohai** [comment]
@RichieMcMullen Do you have "Reopen windows when logging back in" checked in the shutdown dialog?

**Comment by RichieMcMullen** [comment]
Actually I do. But would that come into play before the actual login screen ? I assume it does that after credentials are entered and not before.

**Comment by benfry** [comment]
Try turning it off and see if it fixes the problem?

**Comment by benfry** [comment]
Closing this unless we have better evidence that Processing is somehow involved. The 're-open windows' option could be an issue, but as mentioned earlier, it's not like we have any control over the startup process on the Mac, which would generally require an installer.
