### ISSUE TITLE
Java Error 1114 when using Intel Graphics 2000 or 3000 on Windows 10

### ISSUE THREAD

**Issue by manaspace** [processing/processing#4972]
.dll initialization problem. load library error 1114

**Comment by gohai** [comment]
Are you on Windows XP?

**Comment by manaspace** [comment]
in windows 10

**Comment by manaspace** [comment]
processing 3.3

**Comment by gohai** [comment]
@benfry https://youtu.be/AL3ayVu98Vw (warning: audible mouse clicks)

**Comment by manaspace** [comment]
thank you

**Comment by manaspace** [comment]
same .dll initialization error in running example sketches

**Comment by benfry** [comment]
You still get the error after following the instructions in the YouTube video?

**Comment by adso85swe** [comment]
I have the same problem as described above by several people, i.e. I get the 1114 error message regarding the DLL initialization failure. The problem is, the only suggested fix on the internet is to change your power settings to "maximise performance", but this does not help me at all. Is there any other method I could try? The annoying thing is that all other programs work perfectly fine on my computer, it's only Processing that triggers this issue. Any help would be greatly appreciated.
