### ISSUE TITLE
Inconsistent folder names for mac binaries

### ISSUE THREAD

**Issue by monkstone** [processing/processing#5006]
There is an inconsistency in the naming of the folder containing MacOS binaries, the sound library uses plain `macosx`, whereas the video library uses `macosx64`.

**Comment by gohai** [comment]
That's likely a workaround in the video library, since the external library it depends on (GStreamer) might not have existed in a "universal binary" form (i.e. support for x86 and x64 in the same file).

But the proper library folder for macOS is `macosx`.

**Comment by monkstone** [comment]
@gohai thanks for swift response, but I'm not much wiser, I kind of knew `macosx` was the proper folder, I'm not sure whether you closed issue, because a fix is in hand or whether my input is unwelcome.  I'm in the process of a major refactor of the library loader for JRubyArt and propane (successors to ruby-processing) so the naming is important to me. By the way video library is broken on Archlinux and I'm not quite sure why, if I get the mojo I might take a serious look at it, but may'be that would be unwelcome too?

**Comment by gohai** [comment]
@monkstone While there are guidelines and recommendations, at the end libraries have quite a bit of autonomy how they go about doing things... for some particular reason, the video library uses `macosx64`, which is due to [this line](https://github.com/processing/processing-video/blob/master/src/processing/video/Video.java#L178) in its code, and _not in Processing (proper)_. My guess is that this was required to support both x86 and x64, the former of which seem to have been removed since. To this end, to this end this seems to be a valid observation, and thanks for reporting, but just an implementation detail in a core library.

If you care about this misnomer, feel free to create an [issue in processing-video](https://github.com/processing/processing-video/issues), or send a PR there as well. But given that the naming alone isn't much of a show-stopper for using the library (as least that's how I understood your submission), and our resources are constrained, I am not sure if this will be acted upon there either. That's why I closed the issue. Hope this clears it up.

**Comment by monkstone** [comment]
@gohai thanks for clarification, my resources are even more restrained (ie so far its only me) so for the moment I won't be doing anything about Archlinux (it is only a minor distro) and Mint (and hence probably other Debian/Ubuntu) still work fine.  Problem may due existence of gstreamer-1.0 which is supposed to co-exist with gstreamer-0.10 but may'be not in this case.

**Comment by benfry** [comment]
Libraries that are 64-bit specific should have the 64 prefix, same for 32-bit libraries. But on macOS, it doesn't really matter either way, because there's no such thing as 32-bit on macOS anymore. So using `macosx` and `macosx64` gives you the same result.

**Comment by benfry** [comment]
Come to think of it, maybe it's fine as-is. I just need to [remove the warning about 32-bit](https://github.com/processing/processing/issues/4971) not being available when exporting with the video library.
