### ISSUE TITLE
String escape issue in preprocessor

### ISSUE THREAD

**Issue by ottenm** [processing/processing#5016]
I have a sketch that compiles and runs in P2.  In P3 it says { missing a matching }.  It works after removing the comment below from the code:

 // 720x960 = 7.5" x 10" (0.5" borders)

**Comment by gohai** [comment]
can you attach the full sketch, so we can try to replicate?

**Comment by ottenm** [comment]
Hope this helps!

// compiles and runs in 2.2.1.  In P3 I get this when I try to run: "found a { that's missing a matching }"
String exportPath = "c:\\files\\";
String exportFile = "XXX get above setup() XXX";

void setup() {
  size(720, 960); // 720x960 = 7.5" x 10" (0.5" borders)
  background(255);
  textFont(createFont("Garamond", 18, true));
  text("test", 20, 30);
}

**Comment by gohai** [comment]
I reduced the issue to

    String foo = "\\";
    
    void setup() {
      // "
    }

In the first line, the preprocessor seems to be thrown-off by the escaped backslash (@ottenm: you need to add two backslashes for paths, since a single one starts an escape sequence, see [here](https://docs.oracle.com/javase/tutorial/java/data/characters.html)). This alone only causes the syntax to be colored erroneously, but the sketch still starts.

The second issue a comment with an odd number of quotation marks. On its own this doesn't cause an issue, but here it does.

**Comment by JakubValtar** [comment]
Thanks @ottenm & @gohai, your code helped to track down the issue.

**Comment by ottenm** [comment]
Glad to help Jakub!  Been way up in drifty user-land for a few years, it's
a bit of a thrill to have something to offer at this level.
Stay on top!
