### ISSUE TITLE
Javaw process wont close after the exit of my program (Eclipse)

### ISSUE THREAD

**Issue by TPRammus** [processing/processing#5037]
So I am using Processing via Eclipse and the processes just wont close after the exit of my program. I noticed it after my computer startet to get really slow and I opened the task manager and yay 10 javaw processes! When I use the Processing editor however, it does close the processes normally.

regards, TPRammus

I already created a [post on the forums](https://forum.processing.org/two/discussion/comment/96582) and someone told me to report it here so here I am.

**Comment by benfry** [comment]
This sounds like you're not exiting the program? Are you calling `exit()`? This isn't likely to be a Processing bug: with Eclipse you're on your own and may want to read up more on how Java applications work.

**Comment by TPRammus** [comment]
@benfry Well I am not sure what to do exactly.
I mean can you even call something after the user clicks the red X button at the top right?

**Comment by benfry** [comment]
No problem; just tricky for us to support: we set up the PDE and everything else so that you don't have to think about this sort of thing. But when folks don't use that, there's just a wide array of things that can go wrong and require more familiarity with Java, with coding in general, with how the innards of p5 work, etc…
