### ISSUE TITLE
Movie playback doesn't work at all

### ISSUE THREAD

**Issue by cordboy** [processing/processing#5089]
Hi!

I really hope someone could help me out with this issue since I need to use Processing in public performance in a month.

I get only this black/blank screen while trying to play .mov or mp4 files inside my Processing sketches. There's no error messages or sound playing like in some of the similar cases I found online.

I'm using MacBook Pro with Sierra and newest versions GStreamer framework and ffmpeg are installed. Files are in /Data folder.
Tutorial code and example sketches don't work either.

Thanks in advance!

**Comment by gohai** [comment]
@cordboy Sounds like your issue is with the Video library, for which you could ask the folks on the [forum](https://forum.processing.org/two/categories/questions-about-libraries) for help. (This library is used by many people on similar machines as yours, so I'd first see if its perhaps anything in your input files that makes them not compatible...)
