### ISSUE TITLE
sin(PI)=cos(PI)=... -8.742278E-8 ?

### ISSUE THREAD

**Issue by MrAnima** [processing/processing#5108]
Everything is in the title.
Since I use degrees, I first thought that the problem had something to do with radians(), but every trigonometric function return weird results like this.

**Edit:** After a little bit of testing, I figured out that the problem was coming from Java's "Math.sin()" function itself, but I cannot understand why it does that...

**Comment by AmnonOwed** [comment]
Java uses scientific notation for some numbers when converted to a String, for example in this case a very small floating point number. The E-8 at the end just means the decimal point should be placed 8 positions to the left. Scientific notation saves printed space, because otherwise you'd have a lot of extra zeros.

There are several methods to specify the number formatting you want when converting from number to String. For example in this case you could use nf() to set the number of digits on the left and right of the decimal point. Then you would see the number in a way that is probably more what you would expect.

```Processing
float value = sin(PI);
println(value);
println(nf(value, 1, 25));
exit();
```

This is really more of a question for the forum, than an issue.

**Comment by tolkanabroski** [comment]
I run into really strange floating point errors those days. 
lost and found: https://processing.org/bugs/bugzilla/1015.html

**Comment by benfry** [comment]
Not a bug, as explained in the ancient bug report linked in the previous comment.

**Comment by MrAnima** [comment]
Ok, thanks for your answers! And I really thought it was a bug (even though
I can't believe such a huge issue could have been left in Java), next time
I'll go on the forums first.

**Comment by benfry** [comment]
Yeah, I guess "not a bug" doesn't really cover it since it's certainly not the behavior one *wants*, but it's something that's just an accepted quirk of (32-bit) floating point numbers. 

For use in drawing on screen and most calculations, the value being -.00000008742278 instead of 0 generally won't affect much, but it's certainly confusing.
