### ISSUE TITLE
Exported macos application switches dock icon to default processing sketch icon on launch

### ISSUE THREAD

**Issue by dillones** [processing/processing#5123]
Hello!

I have been having some troubles with exported macos applications. After the exported application launches the dock icon switches from the custom icon I set to the default processing sketch icon. The icon used for the application in finder works, it only changes on the dock after the application is launched

I have also tried changing the default sketch icon in Processing.app/Contents/Java/modes/java/application and modifying the template icon as well, but still no luck.

I found another user on the forum describing the exact same issue.
https://forum.processing.org/two/discussion/21789/exporting-to-mac-dock-icon

![screen shot 2017-06-10 at 11 28 30 am](https://user-images.githubusercontent.com/22481085/27004941-62684a3e-4dd0-11e7-8d58-3cbfb66d70b0.png)
![screen shot 2017-06-10 at 11 28 36 am](https://user-images.githubusercontent.com/22481085/27004942-62a1347a-4dd0-11e7-82d8-fdbd4505df2b.png)

**Comment by benfry** [comment]
Are you using `Surface.setIcon()` or just messing with the application? 

Looks like we need a little update here… https://github.com/processing/processing/wiki/Export-Info-and-Tips

**Comment by dillones** [comment]
I have tried surface.setIcon(), although based off the guide I thought that function was Windows specific. When I place surface.setIcon() in setup() I get a prompt telling me to use it in settings(). When I use it in settings() I get a NullPointerException. I assumed this was because I am trying to access a windows feature on macos.

**Comment by benfry** [comment]
The Windows-specific text is what I was referring to as needing an update. 

`surface.setIcon()` should be working from `setup()`. Are you sure the prompt about using it in settings wasn't about `size()` or another function? `setIcon()` doesn't do that prompt.

**Comment by dillones** [comment]
I attached a screenshot. I am pretty sure it relates to the `setIcon()` function.
![screen shot 2017-06-15 at 7 30 40 pm](https://user-images.githubusercontent.com/22481085/27208257-ea551672-5201-11e7-88df-418e57c36a0f.png)

**Comment by benfry** [comment]
@codeanticode what's this error message? And why is it telling people to use `PJOGL`?

**Comment by codeanticode** [comment]
@benfry Looking at the code to refresh my memory, it seems that the Newt windowing toolkit in JOGL only allows to set the application icons while [initializing the display](https://github.com/processing/processing/blob/master/core/src/processing/opengl/PSurfaceJOGL.java#L475), before creating the Newt window, so that custom icons could only be set by the user inside settings(). However, the surface object is not yet initialized when settings() gets called, so that should be reason for the static [PJOGL.setIcons()](https://github.com/processing/processing/blob/master/core/src/processing/opengl/PJOGL.java#L174) method.

I don't remember the exact details of how this particular code came to be, although [here it is](https://github.com/processing/processing/commit/29bc3cb79a8e749459b28c10ad2ce93584271804) the specific commit that introduced not only the PJOGL.setIcons() method but also initIcons() in PGraphicsJOGL. I'd say this was a temporary workaround that did not get any further updates, and just sat around untouched since then.

Perhaps it is worth revisiting the [NewtFactory.setWindowIcons()](https://github.com/processing/processing/blob/master/core/src/processing/opengl/PSurfaceJOGL.java#L498) call to make sure if can only be used before the window is created, or looking for a different icon setting mechanism.

**Comment by benfry** [comment]
Yeah, that's super messy. We need a better solution (as you can see from this report…)

**Comment by codeanticode** [comment]
Ok, I will see what can be done. According to the JOGL docs, [setWindowIcons](https://jogamp.org/deployment/jogamp-next/javadoc/jogl/javadoc/com/jogamp/newt/NewtFactory.html#setWindowIcons(com.jogamp.common.util.IOUtil.ClassResources)) can only be used before creating the window instance, and requires at least two icons, one for lower and another for higher resolution, but maybe there is a way around it. Recreating the output window while the sketch is running in order to change the icons is probably not a good idea :-)

**Comment by benfry** [comment]
I think we just need to be clear… The problem is that in this case, the `surface` object doesn't exist during `settings()`, and during `setup()` it's too late. We can't/shouldn't load images during `settings()` because those are often renderer-dependent. 

So… that probably means window icons need to be handled differently somehow. For instance, maybe we make it automatic, and check for an `icon.png` file in the sketch directory. If it exists, then it'll automatically be set as the icon (and not overridden by the PDE). That would also help when bundling the sketch, since we could bundle the proper image.

The next tricky part is the multiple resolutions. On macOS you have to build an "iconset", which includes all those variants, and then bundle it into a `.icns` file. Windows does something similar… Which suggests that we actually need to have a *folder* called icon, with images inside that use names like `32.png`, `64.png`, and `256.png`. Hooray! That's nice and complex…

**Comment by codeanticode** [comment]
I see, and agree that we need a new mechanism to set window icons. What you suggest is quite similar to what happens in the android mode. There, we currently look for images inside the root of the sketch folder, named icon-36, icon-48, etc. But I like the idea of using an icon subfolder better.

**Comment by benfry** [comment]
Yeah, I wrote that code. :)

**Comment by codeanticode** [comment]
I think is good that setting custom icons works the same across the Java and Android modes. Are you or Jakub planning to implement the new method on AWT/JavaFX?  I will work on the OpenGL bits. However, most of it should be renderer independent, right?

**Comment by benfry** [comment]
Opening a new issue for this: https://github.com/processing/processing/issues/5225 

I'd like to get this implemented for the next release. We can continue any discussion over there…
