### ISSUE TITLE
eclipse marketplace

### ISSUE THREAD

**Issue by aster94** [processing/processing#5142]
hello, it is not an issue, it s more some kind of suggestion

i think it would be nice if you make an package for the eclipse marketplace instead of the [guide](https://processing.org/tutorials/eclipse/)

maybe there are reasons that makes it difficult, not practical and i am not aware of them
Thanks

**Comment by jm-duarte** [comment]
Hey there!

What you're requesting is different from the guide. The Eclipse Marketplace serves the purpose of offering plugins, etc for Eclipse.

The guide's objective however is being able to use Processing inside your Java project by including it in your build path.

This way, unless Processing turns to be a Eclipse plugin, it won't be going anyway in the Eclipse Marketplace 😄

I hope I helped you! 

PS: Next time be more descriptive in the issue title

**Comment by benfry** [comment]
In 2010 we did a Google Summer of Code project to create an Eclipse Plugin: https://github.com/processing/processing-eclipse but we haven't had any contributors willing to work on it since, so it doesn't work anymore and hasn't been updated for a long time. 

It'd be great to have it working and in the marketplace, since as you note, it'd be easier to work with than the guide, but nobody's volunteered to work on it.
