### ISSUE TITLE
Quil mode - Feature Request

### ISSUE THREAD

**Issue by mefuru** [processing/processing#5167]
Are there any plans to introduce a [Quil](quil.info/) mode to the Processing Development Environment?

Thanks for building such an amazing tool.

**Comment by jeremydouglass** [comment]
This is probably a question to ask Quil developers on their repo. Developing new modes is generally not core development -- it is taken on by individuals or teams with expertise in that mode.

-  https://github.com/quil/quil
-  http://quil.info/

If a mode *is* developed a listing and URL can be submitted to PDE Contributions Manager so that new users can do a quick install.

**Comment by mefuru** [comment]
Thanks @jeremydouglass. I'll take it over there.
