### ISSUE TITLE
PDF Library - No CurveVertex

### ISSUE THREAD

**Issue by chrsmlls333** [processing/processing#5173]
Processing 3.3.5

The PDFs I'm saving consist of a squiggle shape made of curveVertex spline points. Something in this process does not carry over to the PDF export, which consists of straight lines as if I had only used the vertex function. 

Is this a pdf vector limitation or a problem on our end?

Thanks for any help on this.

**Comment by benfry** [comment]
`curveVertex()` should work just fine in PDF, so it sounds like a problem in your code.

**Comment by chrsmlls333** [comment]
For anyone else having this problem, it resolved when I stopped trying to store it in a PShape object, which displayed correctly but didn't seem to transfer over to the PDF recording. Instead I just remade the shape each time with normal beginShape() and endShape on the canvas and it worked like normal.

**Comment by benfry** [comment]
Can you explain that? That sounds like a bug in `PShape`.

**Comment by kikinna** [comment]
I think that what he meant was that when you create PShape object with curve vertices and render it using shape() function (using P2D), then in the canvas you see the curved object (shown in the left image), but if you store it into PDF you get an object as if you were using vertex() instead of curveVertex() (shown in the right image).


![image](https://user-images.githubusercontent.com/11555522/42128346-8a334b28-7ca9-11e8-89bc-defa8c1ee98a.png)

**Comment by makakken** [comment]
I see the issue is old, but.... same error happens if you don't specify a renderer in your sketch:
- size(400,400)
- s = createShape()
- add some s.curveVertex()
- shape(s)

And there will be no Shape on the screen ;)

**Comment by Aldofermaldo** [comment]
This is interesting, I've got a sketch writing to PDF using curveVertex, and even when declaring P2D I still get an output pdf as if I'm only using vertex. SVG behaves the same as well.

**Comment by dkyy** [comment]
Hello -- I can confirm that this is happening for me, too.

If I create a shape, do some CurveVertexes, and then draw that shape onto a PGraphics ... I get sharp edges. If I do the CurveVertexes directly on the PGraphics, things are nice and curvey.
