### ISSUE TITLE
The inherent value of the color datatype?

### ISSUE THREAD

**Issue by WinnerEX** [processing/processing#5174]
Am I missing something here?
In the reference, it says a possible way of "writing" a color is via variables v1, v2, and v3, yet these are not access points to change a variable within color. 
 color rgb = color(100,120,140);
How are you supposed to adjust the "r" in rgb? 
rgb.v1
rgb.x
rgb.r
rgb.a
None of these work.  What is the point of storing a  variable this way when it functionally forces it to be a constant, while it would otherwise work as an actual variable stored as a PVector instead?

**Comment by benfry** [comment]
You can't make adjustments to it, but you can just do the `color()` cast again to rewrite it if you'd like. 

The technical explanation is that it's done this way for performance reasons. Internally, `color` is a "primitive" data type like `int`, `float`, and others, which are much faster to work with than classes/objects. Uppercase types (`PImage`, `PVector`) are classes that have elements like x, y, z, etc. Though underneath, `color` is just an alias for `int`, because it stores the rgba value as an integer number. The "color" name was added because the idea of a color being an `int` seemed more confusing than necessary for people first learning to code.

**Comment by WinnerEX** [comment]
so is the color integer stored as aaaaarrrrrgggggbbbbb or whatever? 

I'm not sure how converting that in the background is suppose to make more sense for learning programmers. It's fairly hard to understand something if you can't see why or how a change is occurring, no? So that's why I was wondering about the inherent value of this datatype.

**Comment by REAS** [comment]
https://processing.org/reference/color_datatype.html
