### ISSUE TITLE
void printConstants()

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#5208]
I write a method to list CONSTANT Processing and check the type of this one. May that's can be helpful for the people to access easily to Processing CONSTANT ? How that's work on https://github.com/StanLepunK/Rope to test how that's work. If you think it's pertienent I can write the code to implement in Processing.

++

**Comment by jeremydouglass** [comment]
I see that in https://github.com/StanLepunK/Rope/commit/91d8b8b75cf09406b4f8ec63ff42c881a586bdb9#diff-1ce6d390b4533501ae95cc9d7cccac83 you have built a list and added each constant by name to that list.

For a programming discussion on the forum about how to access PConstants dynamically -- e.g. using reflection -- see this new post: https://forum.processing.org/two/discussion/23721/access-processing-pconstants-dynamically-using-reflection

**Comment by StanLepunK** [comment]
Whaouuuu, perfect ! I read the article in the forum. that's great, I change my code to don't do that manually, sure it was a very very very bad idea from me ! I go immediately refactoring my code on your professional way. On a side can you think, that's can helpful to add in Processing a method to do that in one line ? Thx for the trick.

**Comment by jeremydouglass** [comment]
Let's continue discussion of programming [on the forum](https://forum.processing.org/two/discussion/23721/access-processing-pconstants-dynamically-using-reflection) -- feel free to respond there.

I am happy to be corrected -- I am not a core developer! -- but I doubt that Processing would build in a method of programmatically accessing PConstants (for display or otherwise) because very few people would ever use that feature. It could be useful for specialty libraries / modes that use the API, which are complex programs that can implement reflection themselves. Otherwise a programmer can just look at the source code if they ever need to know the list of constant names / values.

**Comment by benfry** [comment]
Thanks for the follow-up @jeremydouglass…
