### ISSUE TITLE
Processing does not work with JDK 9

### ISSUE THREAD

**Issue by unrealkate** [processing/processing#5275]
## Description
Processing 3.3.6 (x64) does not seem to work with recent JDK 9 (x64)

## Expected Behavior
Normal execution

## Current Behavior
Run fails with error: ArrayIndexOutOfBoundsException at PApplet.java:122

## Steps to Reproduce
1. Create New project in IntelliJ IDEA
2. Add core.jar to libraries section in "project structure" window
3. Create main class that extends PApplet
4. Add main, settings, setup and draw functions
5. Compile and try to run

## Your Environment

 

* Processing version: 3.3.6 (x64)
* Operating System and OS version: Windows 8.1 (x64)
* Other information: JDK 9 (x64)

## Possible Causes / Solutions
Decompling bytecode leads to line with this code:
    javaPlatform = parseInt(split(javaVersionName, '.')[1]);
it seems that JDK 9 version is just "9" but not "9.0".

**Comment by skooter500** [comment]
Hey this is also an issue on the mac with Java 9:

Running a Processing program from the command line like this:

java -classpath /Applications/Processing.app/Contents/Java/core.jar:. ie.dit.Main

Generates this runtime exception:

Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at processing.core.PApplet.<clinit>(PApplet.java:122)

Looking at the source code here:

https://github.com/processing/processing/blob/master/core/src/processing/core/PApplet.java

I can see that the line of code that generates this exception is:

PApplet.parseInt(PApplet.split(javaVersionName, '.')[1]);

I tried using the -D command line flag to specify the java.version as 9.0, but this does not work.

Hope it can be fixed soon!
