### ISSUE TITLE
Refactoring and Documenting

### ISSUE THREAD

**Issue by christianbender** [processing/processing#5328]
hello, 

I wanted to ask whether refactoring or documenting of code is wanted?
I've seen that much code is comment out. And is a lack of comments in the code. 

greetings 

Christian

**Comment by benfry** [comment]
Not especially, thanks for checking. For the commented-out code, see here: 
https://github.com/processing/processing/wiki/Style-Guidelines#philosophical

The general guideline is that refactoring should be done while fixing problems, not for its own sake. We have *tons* of things that are a higher priority (almost 400 issues!) Good places to start are any of the items marked "help wanted," because those can be solved more-or-less independently of more complicated parts of the code, or are things that I'm unlikely to ever find time to fix.
