### ISSUE TITLE
FX2D Breaks curves in some programs

### ISSUE THREAD

**Issue by calebccff** [processing/processing#5332]
## Description

When drawing a lot of curves (see code below) using the FX2D renderer, it draws lines instead.

## Expected Behavior

The expected output IS shown when using the default renderer

## Current Behavior

Sharp lines are drawn.

## Steps to Reproduce

Run the following code:
```
final int LEN = 1000;
boolean run = false;
PVector[] pos = new PVector[LEN];
void setup() {
  fullScreen();
  strokeWeight(10);
  noFill();
  noCursor();
}
void draw() {
  background(0);
  if (run) {
    for (int i = 0; i < LEN-3; i++) {
      stroke(255, 0, 0, map(i, 0, LEN-3, 0, 255));
      curve(pos[i].x, pos[i].y, pos[i+1].x, pos[i+1].y, pos[i+2].x, pos[i+2].y, pos[i+3].x, pos[i+3].y);
    }
    stroke(0, 0, 255);
    for (int i = 0; i < LEN-1; i++) {
      point(pos[i].x, pos[i].y);
      pos[i] = pos[i+1];
    }
    pos[LEN-1] = new PVector(mouseX, mouseY);
  }
}
void mouseMoved() {
  if (!run) {
    for (int i = 0; i < LEN; i++) {
      pos[i] = new PVector(mouseX, mouseY);
    }
    run = true;
  }
}
```

## Your Environment

 

* Processing version: 3.3.6
* Operating System and OS version: Ubuntu Linux 17.04
* Other information: Default processing version of java

## Possible Causes / Solutions

Appears to be a glitch in how FX2d handles drawing curves.

**Comment by christianbender** [comment]
Have you tried pass the FX2D constant into the fullScreen-function?

```
fullScreen(FX2D);

```
[fullScreen()](https://processing.org/reference/fullScreen_.html)

**Comment by JakubValtar** [comment]
This looks like a problem in your program. This line:
```processing
pos[LEN-1] = new PVector(mouseX, mouseY);
```
adds a new point every frame, so in a lot of places you will have series of points at the same position or very close to each other. This happens more in FX because it probably runs much faster than the default rederer, so more points at one position are added.

Try to add new points only when the mouse position is at some distance from the previous position (like 10 pixels).
