### ISSUE TITLE
processing-java doesn't handle sketch exceptions by quitting the sketch

### ISSUE THREAD

**Issue by biziclop** [processing/processing#5375]
## Description

I run my sketches from a plain text editor (TextWrangler) via the script below, nothing special:
`processing-java --force --sketch="$(dirname "$BB_DOC_PATH")" --output=/SomeWhere/Processing/tmp --run --no-java`

## Expected Behavior

I would expect `processing-java` to quit the sketch that have thrown an exception immediately.

## Current Behavior

When exceptions thrown, sketches are "running" forever.

## Steps to Reproduce

For example, create and run this one-liner sketch via `processing-java`, and it will beachball forever:
`Integer i = null;  i++;`

## Your Environment

 

* Processing version: 3.3.6
* Operating System and OS version: macOS El Capitan 10.11.6 (15G18013)
* Other information:

## Possible Causes / Solutions

Thank you for creating and maintaining Processing. :)

**Comment by calebccff** [comment]
Temporary fix (depending on your workflow):

Bind a key to `pkill java` and use it to kill the sketch when an exception occurs.

**Comment by benfry** [comment]
Hm, this is by design—it's the same behavior as when running the software from the PDE (where the sketch window stays open). Because you're usually looking for what's happening visually (leading up to the Exception), killing the process immediately would make things frustrating/impossible to debug in most cases.

If you have a use case where you'd like things to exit immediately, you might try a workaround where you create a [default exception handler](https://www.google.com/search?q=java+default+exception+handler) that calls `System.exit()`. That might be problematic with OpenGL and JavaFX sketches, but it'd at least give you the behavior you're looking for.

**Comment by biziclop** [comment]
Dear @benfry, thank you for your answer, I'll try this.
