### ISSUE TITLE
floor(18662399) returns 18662400

### ISSUE THREAD

**Issue by RectangleWorld** [processing/processing#5381]
floor(18662399) returns 18662400, which can be observed with a simple println statement.

(It's not just a matter of a rounded print out either, the value of a variable calculated this way is causing an index out of bounds on my array of size 18662400.)

To reproduce, simply run a sketch with one line:
println(floor(18662399));

Windows 10, Processing 3.3.6

**Comment by RectangleWorld** [comment]
I should mention that

(int) Math.floor(18662399)

returns the value 18662399 as expected, so it may be a suitable alternative. I was just surprised by this because I didn't think 18662399 was large enough to be a float vs. double issue, but maybe I'm wrong.

**Comment by skrillcon** [comment]
So I found the cause of the issue. 

When you have 18662399.0 as a float it gets rounded to 1.86624E7. Since processing converts the input for _floor_ to a float first before it floors it, it changes to 18662400. _Math.floor_ will return the proper value if you use an int variable or if you case it like RectangleWorld had mentioned. 

So the solution is either to use Math.floor and cast it as an int or there could be another floor function in processing for ints.

**Comment by RectangleWorld** [comment]
Yes, sorry, I realized this was a floating point issue, and not a bug. The workaround for that kind of accuracy is to use Math.floor which works with doubles. I think I'll close the issue!
