### ISSUE TITLE
Why is runSketch method protected?

### ISSUE THREAD

**Issue by cansik** [processing/processing#5394]
I am using processing core a lot together with a JavaFX UI to control the parameters of the scene in real time. So first the JavaFX UI is started and then the processing sketch gets started from the UI itself.

To run the processing sketch, I have to possibilities:

First, to run the processing sketch with the static method, which is kind of ugly because of the class name I have to provide as a string (in regards to refactoring):

```java
PApplet sketch = new MyProcessingSketch();
PApplet.runSketch(arrayOf("MyProcessingSketch "), sketch)
```

Second, I could add a helper method in the sketch itself, which calls the *protected* `runSketch` method:

```java
void run()
{
    runSketch();
}
```

So my question is, why the `runSketch()` method is protected?
Because as developer which is using just the processing core, this is a bit cumbersome.

**Comment by benfry** [comment]
Methods are only made public when we're committed to supporting them as API features (meaning that we're comfortable with how they fit the rest of the API, that they should actually be used, knowing that people will use them, etc…), or because of an external factor that requires them to be public. 

In this case, it fails the first test… Your use case is outside our mainstream use case, but it's protected (not private) so that it's possible, if less elegant, for situations like this one.
