### ISSUE TITLE
Framerate caps at 1000 in P2D and P3D mode

### ISSUE THREAD

**Issue by mriklojn** [processing/processing#5404]
## Description
Setting the frame rate above 1000 in setup() gives an error and does not work, but only if the renderer mode is P2D or P3D

## Expected Behavior
If the frame rate is set above 1000, the sketch would be expected to work as normal with a frame rate which is above 1000. P2D and P3D modes should not be capped at 1000 fps.

## Current Behavior
Currently the console gives an error "Non-positive period" and the sketch opens as an empty window. The code in draw() is not executed and the sketch has to be closed. P2D and P3D modes give this error whereas default mode and FX2D modes do not give the error and work fine at much higher framerates.

## Steps to Reproduce

1. In `setup()` method, include a call to `frameRate(1001)`
2. Ensure the renderer in size() function is set to P2D or P3D
3. Run the sketch
4. Error is produced.

Example code:
```
void setup() {
  size(640, 480, P2D);
  frameRate(1001);
}
```

## Your Environment
* Processing version: 3.3.6
* Operating System and OS version: Windows 10 Home
* Other information: Java 1.8.0_151

**Comment by gohai** [comment]
@mriklojn Do you have any actual use-case in which you'd require a framerate of > 60? Thanks.

**Comment by mriklojn** [comment]
@gohai For example, I have a random walk sketch which draws very slowly at 60 fps, being barely visible until quite some time has passed. Setting the frame rate to 1000 solves this to an extent, but it still takes some time so I would like to set the frame rate higher, but still use the P2D render mode.

**Comment by benfry** [comment]
@codeanticode we should catch this case and provide a better error message. 

@mriklojn this is something that shouldn't be handled with frame rate—it's not a matter of updating the screen that quickly, and a better solution is to write your code to either loop a certain number of times on each frame, or even have the content updating separately in its own thread. (Though the latter is more complicated than necessary, because then you'd have to sync it up with the graphics thread.)

**Comment by codeanticode** [comment]
Capped frame rate at 1000 with https://github.com/processing/processing/commit/8ff6fb6b5c1909859ee140bc37f4a73e8ccf2802

**Comment by benfry** [comment]
Thanks @codeanticode
