### ISSUE TITLE
Modern Launch4j alternatives

### ISSUE THREAD

**Issue by gohai** [processing/processing#5408]
Just wanted to share [this blog](https://steveperkins.com/using-java-9-modularization-to-ship-zero-dependency-native-apps/) post I came across, which discusses `javapacker` and `jlink`. Not sure if any of this would be feasible for P5 though...

**Comment by benfry** [comment]
Thanks for the link. Sadly, the modularity stuff in Java 9 doesn't help us much since we're a development environment and we can't anticipate much about what features people will want. 

Also wish that javapackager weren't such a mess… it's a drag to have separate builders for Windows and macOS (not to mention our rigged version for Linux).

**Comment by gohai** [comment]
Thanks for pondering over it, Ben!
