### ISSUE TITLE
Feature req.: "advanced" preferences

### ISSUE THREAD

**Issue by YoshiRulz** [processing/processing#5425]
## Description
Instead of a paragraph at the end of the preferences window explaining how to edit `preferences.txt`, it would be more beneficial to "advanced" users (looking to further customize the IDE) if there was more UI for the extra settings. In previous Issues/PRs related to the preferences UI, it was suggested that a table like Firefox's `about:config` page would be sufficient.
If implemented, this would prevent complaints of overcrowding the existing window and also allow streamlining of which settings are shown in the existing window (for "novice").

## Your Environment
* Processing version: future
* Operating System and OS version: all

**Comment by gohai** [comment]
Ideally you would not need to edit "advanced" settings to begin with. Users interested in further customizing the PDE are likely to have the skills to find and open a text document on their drive. Closing.

**Comment by benfry** [comment]
I've considered building this in the past (and there's even an item in `todo.txt` for it), but haven't done so due to 1) lack of time/priority, and 2) the likelihood that this will create far more problems than it solves. It'd be too easy to break things by having people mess with those preferences, and at least in the current situation, the extra effort at least sets the expectation that it's up to the user if something goes wrong.
