### ISSUE TITLE
Support for Nvidia TX1/TX2 platforms???

### ISSUE THREAD

**Issue by kaisark** [processing/processing#5470]
Does processing support the Nvidia TX1 platform (arm64)??? Should we use the DragonBoard410c directions for the TX1?

Have you heard of ExaGear Desktop???

Thanks.

--------------
Introduction
The DragonBoard410c by Arrow Electronics / 96Boards contains an 64-bit Cortex A53 Snapdragon 410E CPU, 1GB RAM, 8 GB of internal storage, Wifi, Bluetooth, GPS and an Adreno 306 OpenGL ES 3.0 GPU graphics core.

The DragonBoard 410c comes pre-installed with Android, however for running Processing it is necessary to install Linux instead. You can find instructions how to install the Linaro-supported Debian operating system here.

Download
Install Processing by running the following in a terminal:

curl https://processing.org/download/install-arm.sh | sudo sh

**Comment by gohai** [comment]
Hi @kaisark - I am closing this one because this isn't a bug in a released version of Processing. Regarding TX1: you could give it a try, as we're shipping an ARM64-bit version of JOGL. Since all versions of Oracle's Java appear to be of the _headless_ variant, we are currently not properly releasing versions for this architecture, but you could always try running Processing in combination with non-headless OpenJDK builds for ARM64. (try replacing the `java` directory of e.g. the `armv6hf` download by a symlink to your JDK installation)

Feel free to comment with your experiences!
