### ISSUE TITLE
fullscreen on Windows 10 scaled display is not fullscreen

### ISSUE THREAD

**Issue by quinton-ashley** [processing/processing#5479]
On Windows 10 if you use a display scale factor of anything other than 100% in the OS settings the processing sketch will not be fullscreen.  There needs to be a multiplier like `pixelDensity(displayDensity());`, which only works on macOS at the moment.

**Comment by quinton-ashley** [comment]
both

**Comment by quinton-ashley** [comment]
It was because I'm using Eclipse.  I will test this out tomorrow.
https://github.com/processing/processing/issues/5414

**Comment by JakubValtar** [comment]
And which version of Processing core.jar are you using in Eclipse?

Either you downloaded some version of Processing and included core.jar into your project, or you are building Processing core from this github repo, in which case I need to know the hash of the latest commit you have.

Depending on the version, I will either tell you to update, because I already fixed it, or there is indeed bug in our code which is not fixed yet.

**Comment by quinton-ashley** [comment]
I'm using the latest stable version 3.3.7

**Comment by JakubValtar** [comment]
Ok, thanks for the reply. I'll try to figure out what the problem is.

**Comment by quinton-ashley** [comment]
Any luck?
