### ISSUE TITLE
Nonsense "not used" warning.

### ISSUE THREAD

**Issue by chrisjj** [processing/processing#5520]
## Expected Behavior
Used variable NOT warned.

## Current Behavior
Used variable warned:

![image](https://user-images.githubusercontent.com/6157073/40809820-ac877bb0-6523-11e8-86a2-516ab9d796e0.png)

Proof it is used:

![image](https://user-images.githubusercontent.com/6157073/40809831-b28ffdf2-6523-11e8-8937-7d27257cdb50.png)

Better would be to warn "redundant code".

## Your Environment
* Processing version: 3.2.1
* Operating System and OS version: Windows 7

**Comment by Transistorsis** [comment]
You are editing the variable, but you never assign anything to it, or use it as a parameter. It is therefore, "not used".

**Comment by chrisjj** [comment]
It says the value of the variable is not used, and that's untrue.  Better would be to warn "redundant code" - added to report.

**Comment by JakubValtar** [comment]
Thanks for the report, but I think the message is fine. You are writing the value, but never reading it. You are incrementing `count`, but not using the value of `count` for anything. The variable is used, the value of the variable is not. If you remove the variable and the code which is modifying it, the program will still work the same.

**Comment by chrisjj** [comment]
>  If you remove the variable and the code which is modifying it, the program will still work the same.

Sure? I thought it would run slower.

**Comment by JakubValtar** [comment]
Why do you have `count` there if you are not using it for anything?

The message is trying to tell you that this:
```processing
float neighbordist = 10;
int count = 0;
for (Boid other : boids) {
  float d = PVector.dist(position, other.position);
  if ((d > 0) && (d < neighbordist)) {
    count++;
  }
}
```
does the same thing as this:
```processing
float neighbordist = 10;

for (Boid other : boids) {
  float d = PVector.dist(position, other.position);
  if ((d > 0) && (d < neighbordist)) {

  }
}
```
If you don't use the value of `count` after the loop, there is no point in having it there.

As soon as you use the value for something, the warning will go away:
```processing
float neighbordist = 10;
int count = 0;
for (Boid other : boids) {
  float d = PVector.dist(position, other.position);
  if ((d > 0) && (d < neighbordist)) {
    count++;
  }
}
println(count); // reading the value and using it for something
```

**Comment by jeremydouglass** [comment]
@chrisjj -- "not used" as in not utilized, not incorporated into some resulting operation in which the value is displayed, sent, or written.

For example:

> I'm going to buy milk, eggs, flour, sugar, and an elephant, then bake a cake with milk, eggs, flour, sugar, then serve the cake.
>
> > Warning: elephant not used. (did you want to 

This warning **is not Processing-specific** -- you would encounter this warning in almost *any* Java programming environment -- for example, in Eclipse. Here is one example of a general discussion:

https://stackoverflow.com/questions/11062919/java-error-value-of-local-variable-is-not-used?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

You will also encounter this warning in several other programming languages. Many compilers will happily identify your mistake and throw it away (the variable never becomes code at all, because it is pointless) but they still want to warn you that you are doing it, because it may reflect a design flaw or misunderstanding. If not: ignore the warning!
