### ISSUE TITLE
Request mouseDown() function

### ISSUE THREAD

**Issue by Hendiadyoin1** [processing/processing#5553]
## Description
  A function that is called every frame if mouse is down
like:
`void draw(){
  if(mousePressed){
    ....
  }
  ....
}
`

**Comment by gohai** [comment]
I think it is unlikely that the language (API) will be changed at this point to include this. To my eyes, the snippet you posted looks quite understandable - whereas I wouldn't know if I could keep `mouseClicked()`, `mousePressed()`, `mouseDown()` apart - in what they do

**Comment by jeremydouglass** [comment]
@Hendiadyoin1 -- When needed I sometimes create my own `mouseIsDown()`, called using the hook in draw as you indicated:

```
void draw() {
  background(255);
  if (mousePressed) {
    mouseDown();
  }
}

void mouseIsDown() {
  background(0);
}
```

One potential confusion with the long-established API is that `mousePressed` describes a state, while `mousePressed()` processes an event. It can also be confusing because `keyPressed()` may generate multiple key events, depending on how the keyboard repeat signaling works in hardware and OS, while `mousePressed()` does not -- we don't expect a depressed mouse to be generating many discrete click events like an electric typewriter.
