### ISSUE TITLE
Error during download and install of Video

### ISSUE THREAD

**Issue by Volts-s** [processing/processing#5661]
## Description
Video library from the Processing Foundation cannot be installed via the  Contribution Manager.

## Expected Behavior
Successful installation

## Current Behavior
Installation of the processing-video library (from the Processing Foundation) via Contribution Manager fails with the following error message: "Error during download and install of Video." The error seems to be specific to the video library.  Other libraries can be installed and removed.

## Steps to Reproduce
Attempt to install Video | GStreamer-based video library for Processing

## Your Environment

 

* Processing version: 3.4
* Operating System and OS version: Windows version 10.0.17134.283
* Other information:

**Comment by Volts-s** [comment]
I attempted to install the library with Processing 3.3.7; this failed the same way.

**Comment by Volts-s** [comment]
I successfully installed via Processing 3.3.7 Contribution Manager on OSX Sierra.  Then installed manually on Windows by copying the files from the Mac.  The video library is now working in Processing 3.4 on Windows.

**Comment by vlna** [comment]
I have simillar issue with Processing 0265 on Archlinux. It looks it is not possible to download (all?) packages hosted on Github. wget says URL returns 302 and sends downloader to Amazon AWS.

**Comment by vlna** [comment]
I tested official prebuilt binary version and Manager works properly. It looks like Archlinux package issue only.

**Comment by imilas** [comment]
I'm getting this error with video and sound libraries.

Using manjaro linux

**Comment by xyproto** [comment]
Hi,

I'm the current maintainer of the Arch Linux package for `processing`.

I believe Manjaro also uses this package.

When installing the "AI for 2D Games" package, it works fine, but the "Video" package fails with:

    Error during download and install of Video.

I wish the error message was more informative.

Building `processing`  from source involved writing a custom `build.xml` file, because:

* Packaging the binary package is not an option, for Arch Linux.
* Processing does not build "out of the box" on Arch Linux.
* `ant` wants to download files at the `build` stage, but all Arch Linux packages should download any files in advance, before the `build` stage, where they are checksummed.

This may be a packaging issue on Arch Linux, since the binary release apparently works when installing the Video library, but without a more informative error message, it's hard to pinpoint where the problem lies.

This could also be related to OpenJDK vs Oracle JDK (which should be avoided, IMO).

Since this problem also exists on Windows, and since some libraries can be installed just fine, it's also possible that this is not a packaging issue at all, for the case of the Arch Linux package.

Help in pinpointing the issue is welcome.

**Comment by xyproto** [comment]
Installing the MQTT library with the binary download version of Processing works fine here.

I modified the processing package on Arch Linux, so that it outputs more informative error message when this fails. Now I get:

    Can not download https://github.com/256dpi/processing-mqtt/releases/download/latest/mqtt.zip to /tmp/download186288038810673513mqtt.zip : Error during download and install of MQTT.

When downloading mqtt.zip with either "wget" or "curl" (with the -L flag, since there is a redirect) to `/tmp/download186288038810673513mqtt.zip` manually, it works fine.

Some tools, like "Ani" or "AI for 2D Games" download and install just fine.

This leads me to believe that this is not a directory/permission issue, and not an issue with downloading, but perhaps an issue related to downloading from URLs that has a redirect.

Could this be caused by using OpenJDK instead of the Oracle JDK?

**Comment by xyproto** [comment]
I guess the nest step would be to add a test to the processing source code so that it could be confirmed if this is an issue with URL redirection, or not.

**Comment by zoe1337** [comment]
I have the same problem with various items from the Contribution Manager, for example Sound library doesn't work. Same error as above. `Could not download https://github.com/processing/processing-sound/releases/download/latest/sound.zip to /tmp/download4127094086393710964sound.zip : Error during download and install of Sound.`

After I installed the processing.org provided binary, it's working as expected.
I'm running up-to-date Arch. Processing version 3.4 (build 0265) https://github.com/processing/processing/tree/processing-0265-3.4
/cc @xyproto

**Comment by benfry** [comment]
Please use the download from our page. 

If you use someone else's download, please help save my time by reporting the issue to them.

**Comment by xyproto** [comment]
I believe this issue is due to the lack of support of OpenJDK.

I believe this is the same as issue #4415, and should not be closed as invalid, but perhaps as duplicate.
