### ISSUE TITLE
Sound issue! 

### ISSUE THREAD

**Issue by namjunegg** [processing/processing#5671]
Hello, could someone help me out?

I am trying to put music and make it play. 

I followed the code as mentioned here: (https://processing.org/reference/libraries/sound/SoundFile.html)...

but I keep getting this error. (image attached)
<img width="707" alt="screen shot 2018-10-07 at 1 52 27 am" src="https://user-images.githubusercontent.com/43922874/46578690-aea2fe00-c9d3-11e8-9405-40e355d57dad.png">

Thank you

**Comment by Awalvie** [comment]
When I try to replicate this error I get a `IndexOutOfBoundsException` error.

**Comment by gohai** [comment]
@namjunegg Besides the red text in the console, does the sketch run? (Please file issues concerning the sound library here: https://github.com/processing/processing-sound)
@kevinstadler Is JSyn writing to stderr? Harmless?

**Comment by Awalvie** [comment]
For me the audio file does not seem to be running.

**Comment by kevinstadler** [comment]
@gohai JSyn's logger writing to stderr is harmless (if annoying), yes (see processing/processing-sound#12).

@Awalvie your `IndexOutOfBoundsException` should be fixed with version 2.0.2 of the Sound library, which should become available for download in the Processing contribution manager within the next 24 hours (see processing/processing-sound#11). Thanks for reporting!
