### ISSUE TITLE
Code completion with Ctrl+Space isn't working [Windows]

### ISSUE THREAD

**Issue by vermaditya1999** [processing/processing#5691]
## Expected Behavior
Type the following code:

<img width="140" alt="1" src="https://user-images.githubusercontent.com/32881318/47615832-c2c1b300-dada-11e8-864f-33f178a31295.PNG">

And hit Ctrl+Space, then auto complete suggestions should pop up like this:

<img width="187" alt="2" src="https://user-images.githubusercontent.com/32881318/47615880-6e6b0300-dadb-11e8-95e5-1fb03e74bd78.PNG">

## Current Behavior
Currently, nothing happens when I press Ctrl+Space. (Code completion with Ctrl-space is enabled in File -> Preferences).

When I set `pdex.completion.trigger=true` in preferences.txt, I am able to get the suggestions without pressing Ctrl+Space (That's how I was able to the get the second screenshot), which works as expected.

## Your Environment
* Processing version: 3.4
* Operating System and OS version: Windows 10 Home Single Language, Version: 1803, OS build: 17134.345

* Other information:
I have tried it in a fresh installation of Windows 10. Still, it doesn't work.

**Comment by hapiel** [comment]
Thank you for posting this. I have the same issue, also in win 10, but your 'solution' to set the `pdex.completion.trigger=true` works for me too.

**Comment by benfry** [comment]
It's turned off by default, because beginners often find it confusing. But you don't need to mess with `preferences.txt`. Just open the Preferences window and check the box for code completion.

**Comment by hapiel** [comment]
Hi @benfry , thanks for taking the time. 

Yes, I'm aware of the preferences window, but ticking the box has never worked for me. Not in 4.0a6 nor in 3.5.4 . 

The settings checkbox seems to affect `pdex.completion`, but no matter to what that is set I can't get completion to work. Therefor I was glad to discover that `pdex.completion.trigger=true` enables me to use completion to work nonetheless.

I don't know how common this issue is, and it must be near impossible to fix if you can't recreate it, but it does seem like a bug or glitch.

**Comment by benfry** [comment]
By turning on the checkbox, you should get completions whenever you type ctrl-space. If that's not working, I'd try using the latest 4.0 alpha release. Or check to see if there's something else on your system that has re-mapped ctrl-space to something else.

`pdex.completion.trigger` may require `pdex.completion` to also be set. Setting the `pdex.completion.trigger` preference will cause completions to pop up even when you haven't hit ctrl-space (i.e. while you're typing), which is what I was saying was confusing for new users (the majority of our audience).

From your report, I can't tell if 1) ctrl-space isn't working for you, or 2) “code completion” means completions popping up automatically—not having to hit ctrl-space—and therefore it appears broken to you.

**Comment by hapiel** [comment]
Hi @benfry , sorry for the confusion, I meant to say that my issue looks exactly like the issue of the original post.

To clarify: ctrl-space is not working for me. Not in 4.0a6 nor in 3.5.4.
Yes, I understand that as this appears to be a rare issue it could be something on my end like something else on my system that remapped ctrl-space, but I can't discover what that might be. Testing with https://keyboardchecker.com/ confirms that I can hold down ctrl & space at the same time.

If the issue only ever exists on my system then it's probably none of your concern, but since I found this issue describing the exact same problem, I figured I'd post my issue too.

Perhaps an option to remap the completion trigger hotkey could solve it?

**Comment by benfry** [comment]
Got it; I'm a little stumped. And yeah, an option to change the trigger might work, though that's a tricky thing to write and debug. Maybe easier to bring back the `.trigger` preference in the Preferences window by saying: 

Auto-completion: [ ] Disabled  [ ] Show on Ctrl-Space  [ ] Always show

**Comment by benfry** [comment]
Completion should be working better in 4.0 beta 9, and the `trigger` option is now documented here: https://github.com/processing/processing4/wiki/Preferences#completion
