### ISSUE TITLE
Cannot run rotateZ() within the PShape class

### ISSUE THREAD

**Issue by bennyHacker** [processing/processing#5770]
Whenever I try to run pshape.**rotateZ()** I run into an exception. All steps needed to reproduce and further details can all be found on this post I made on the forum:

https://discourse.processing.org/t/bug-pmatrix3d-cannot-be-cast-to-pmatrix2d/7779

I believe this is a bug only occurring after 3.5 (3.5.1 and 3.5.2)

**Comment by micuat** [comment]
```
PShape s;
void setup() {
  size(100,100,P3D);
  try{
    s = createShape();
    s.beginShape();
    s.rotate(0.1);
    s.endShape();
  }catch(Exception e){
    e.printStackTrace();
  }
}
```

gives

```
java.lang.ClassCastException: processing.core.PMatrix3D cannot be cast to processing.core.PMatrix2D
	at processing.opengl.PShapeOpenGL.transform(PShapeOpenGL.java:1390)
	at processing.opengl.PShapeOpenGL.rotate(PShapeOpenGL.java:1254)
	at sketch_190207b.setup(sketch_190207b.java:23)
	at processing.core.PApplet.handleDraw(PApplet.java:2425)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:866)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

I know `PShape` has changed a bit recently - maybe related to something around this? https://github.com/processing/processing/issues/5685 https://github.com/processing/processing/issues/5560

**Comment by wbigger** [comment]
Same issue on 3.5.3, cannot rotate on Z axis. X and Y axis rotations work fine.

**Comment by hamoid** [comment]
Same problem. My live performance setup stopped working because of this bug.

**Comment by StanLepunK** [comment]
I think it's by this pullrequest... https://github.com/processing/processing/pull/5821 i hope !

**Comment by erniejunior** [comment]
Same issue here. Please accept the PR.

**Comment by allesblinkt** [comment]
As I have wasted a good hour on this, here is a quick workaround for the time being:

Instead of 
```java
wickedShape.rotateZ(niceAngle);
```
use
```java
wickedShape.rotate(niceAngle, 0.0, 0.0, 1.0);
```

**Comment by slowizzm** [comment]
Still present in 3.5.4. @allesblinkt solution works! thanks!!

**Comment by cmasnuo23** [comment]
@allesblinkt What is niceAngle represent?

Do you need to define it? I'm new to processing.  Wrote a script where rotateZ(radians(-176)); worked perfectly, and now it doesn't.

**Comment by allesblinkt** [comment]
It represents the angle in radians -- the same you would give to `rotateZ`. That would be `rotate(radians(-176), 0.0, 0.0, 1.0);` in your case.

Aside: Is this issue still present??

**Comment by cmasnuo23** [comment]
hi @allesblinkt Thank you so much for your reply! 

I will go ahead and give it a try.  

My work around yesterday was that I was importing a point cloud as a .txt file and was trying to adjust the orientation within processing.  Instead, I figured out a way to import the pointcloud as a .ply into Rhino and export it with adjusted alignment, so that processing could read the string.

**Comment by micuat** [comment]
Just to be clear, this issue is about `PShape::rotateZ()` and @allesblinkt already posted a temporary solution https://github.com/processing/processing/issues/5770#issuecomment-500995996. If you have questions about how to use these functions, I recommend you to post on [discourse](https://discourse.processing.org/) first.

I posted a script to test this issue https://github.com/processing/processing/issues/5770#issuecomment-461277346

And @StanLepunK proposed a pull request https://github.com/processing/processing/pull/5821. @benfry (or anyone who can), could you take a look at the PR? It has not been reviewed since it was posted a year ago.

**Comment by benfry** [comment]
This is fixed in the alpha 2 release of Processing 4, you can download it here: https://github.com/processing/processing4/releases

Unfortunately I don't have the free time to maintain 3.x releases at the same time, so hopefully 4.x will work for your needs.
