### ISSUE TITLE
Broken link for download

### ISSUE THREAD

**Issue by spuder** [processing/processing#5782]
Not sure this is the correct place to report this issue. 

The processing webpage has broken links for download

https://processing.org/download/

For example the OSX download link takes you to a page that doesn't exist

http://download.processing.org/processing-3.5.3-macosx.zip

The correct link is here: 

https://github.com/processing/processing/releases/download/processing-0269-3.5.3/processing-3.5.3-macosx.zip

**Comment by AlvaroHermida** [comment]
Yes, the redirection is slightly broken (it links to 
`".../processing-0266-3.5/processing-3.5.3-*"` instead of 
`".../processing-0269-3.5.3/processing-3.5.3-*"`)

As a workaround, the five packages plus the source code can be downloaded using this alternative link:
[https://github.com/processing/processing/releases/tag/processing-0269-3.5.3](https://github.com/processing/processing/releases/tag/processing-0269-3.5.3)

**Comment by benfry** [comment]
Now fixed.
