### ISSUE TITLE
Files.exists(relativePath) returns false even if the file exist

### ISSUE THREAD

**Issue by Meowzz95** [processing/processing#5789]
## Description

`String DATA_PATH = "./data.json"`
Let's say file `DATA_PATH` is located at the same folder as the source file, `Files.exists(Paths.get(DATA_PATH))` returns false. However `loadJsonObject` and `saveJsonObject` behaves correctly using the same path(`DATA_PATH`). The same code works fine in pure Java implementation(use processing core lib to run without using PDE).

A workaround in PDE:
Wrap the path with `sketchPath()`
That is, `Files.exists(Paths.get(sketchPath(Assets.DATA_PATH)))` works fine.
## Expected Behavior

should return `true`
## Current Behavior

returns `false`
## Steps to Reproduce

1. Save a json file at `DATA_PATH`
2. Execute `Files.exists(Paths.get(DATA_PATH))` 
3. The code returns false even if the file exists.

## Your Environment

 

* Processing version: 3.5.2
* Operating System and OS version: 
![image](https://user-images.githubusercontent.com/22430379/52474459-86224f00-2bd3-11e9-89e1-0161b9fb89fc.png)

## Possible Causes / Solutions
My guess is Paths.get(relativePath) returns a wrong path?

**Comment by benfry** [comment]
This is not a Processing bug. It's why the `sketchPath()` function exists, so that you can deal with files in predictable ways. The current working directory (using `.` or no prefix at all) isn't a good way to locate files, because it's platform/OS/IDE/Java version-dependent.

The `Paths.xxx` code is just Java code; we have no control over its behavior.
