### ISSUE TITLE
Keyboard shortcut for switching tabs on Windows conflicts with accessibility keyboard shortcuts

### ISSUE THREAD

**Issue by abelaaa** [processing/processing#5794]
## Description
Using Ctrl + Alt + Left/Right [pans everything in to the left/right](https://support.microsoft.com/en-gb/help/13810/windows-keyboard-shortcuts-accessibility). _And it may matter to know that even after this rotation, the shortcut doesn't seem to work in switching between the open tabs._

## Expected Behavior
Expected to switch between previous and next tabs.

## Current Behavior
Rotates everything on the screen. Pans in the direction of the arrow keys.

## Steps to Reproduce
Try pressing **Ctrl + Alt + Left/Right**.

## Your Environment
Processing 3.5.3
Windows 10 [x64] - 1803 release.

## Suggestion [Feature]
I say it is much more convenient to press Shift + Alt + ArrowKeys than with Ctrl. And would use the mouse less often if this is the case.

**Comment by benfry** [comment]
Weird, the Windows keyboard shortcut was chosen after a lot of Windows users weighed in on what it should be and what other software was using. 

I'm gonna change it to ctrl-page down/up for the next release, since that's what we use on Linux. If you want to change it yourself in the meantime, add these lines to your `preferences.txt` file:

```
editor.header.previous_tab.keystroke.windows = ctrl pressed PAGE_UP
editor.header.next_tab.keystroke.windows = ctrl pressed PAGE_DOWN
```

To use something else (ctrl-tab or whatever), there's more here: https://github.com/processing/processing/wiki/Localization#shortcuts-and-key-bindings
