### ISSUE TITLE
Java NullPointerException at startup -ContributionManager.java

### ISSUE THREAD

**Issue by Code-Sloth** [processing/processing#5823]
## Description
Processing 3.5.3 fresh install fails to start with Java NullpointerException
## Expected Behavior
Expected processing application to start
but fails with NullPointerException
## Current Behavior
An error occurred during startup 
ContributionManager.java 621
see jpg of  issue here '(We're off on the wrong foot' dialogue):
![StartupError](https://user-images.githubusercontent.com/9049115/54494351-19d0f480-48d1-11e9-99ac-605dbe59db35.jpg)
## Steps to Reproduce
1. download processing-3.5.3-windows64.zip
2. extract all to local directory
3. move unzipped processing-3.5.3 complete to Program Files
4, Run processing.exe
5. Fails to find sketchbook
6. Alter preferences.txt in c:\users\%user%\app data\roaming\processing to include the line
sketchbook.path.three=C:\users\%user%\Documents\Processing
(between search.format=https://google.com/search?q=%s  &  update.check=true )
to overcome failure to find sketchbook on 1st run
7. Run again with error dialogue as result
Environment:
Acer B117-MP laptop dual processor 4.0 GB memory
24.9 of 118 GB ssd space free
64 bit WIN 10 OS latest update
* Processing version:
processing 3.5.3
* Operating System and OS version:
Windows 10 Home Edition version 1803 build 17134.648
* Other information:
CLASSPATH only set as an attempt to resolve:
CLASSPATH= .;.\Java\lib;Java\lib;JAVA_HOME\lib;
JAVA_HOME=C:\Java\jdk1.8.0_111

**Comment by DeerajTheepshi** [comment]
I was exactly able to recreate the error by adding the line : 
`installList = null;`
This could mean that ,  the sketchbook folder that you have set isn't pointing to the correct Path.

**Comment by Code-Sloth** [comment]
Deeraj Esavar R

Thank you for your interest & assistance

My preferences.txt file is located at 
C:\Users\David\AppData\Roaming\Processing\

My preferences.txt file includes the line 
'sketchbook.path.three=C:\Users\David\Documents\Processing'

I have a file named 'sketchTest.pde' in the folder 'sketchTest' in the 
folder 'Processing' which is located at C:\Users\David\Documents\

Whether I attempt to open processing.exe or try to open the 
sketchTest.pde file I get the same failure as before.

Given the above I do not know how to proceed.

Thank you once again

David

**Comment by Code-Sloth** [comment]
Interestingly, following the same process as on my 64 bit lap top (which has failed as above), I have  just successfully loaded and run the 32 bit version on my desktop- also current updated win 10.

**Comment by Code-Sloth** [comment]
This was mistakenly closed . I still have the same original issue with the 64 bit software on my laptop. May be I should just give up with the 64 bit and try 32 bit on this machine as well.

**Comment by Code-Sloth** [comment]
Tried 32 bit download to laptop but I get exactly the same error. So I am lost.
[NB Arduino IDE (32 bit) based on processing seems to work OK.]

**Comment by Am0rA** [comment]
I am stuck with this issue too. I tried to delete all document which is relevant with processing (except my projects) and tried to download again and again. And also tried all kind of solution i could find. 

Afterward i realized that i had also a few problems with updates which occurs due to language preferences of my laptop. (I use English, Dutch and Turkish) so i decided to change all language preferences, location en etc to same language to solve this issue. 

And it solved on this way. 

Delete every thing that you can find which is relevant on your computer (except projects). Fastest way to do this is a bit difficult. You should search the word 'processing' in your computer (everywhere!). Just be careful to delete things which is belongs to Windows or other apps.

Then change your language preferences from everywhere on Windows.

Then download the lastest version of processing. DO NOT UNZİP.

Launch it within zip document.

Then enjoy your app.

Thanks🌹

**Comment by benfry** [comment]
Added a catch to fix this in 3.5.4.
