### ISSUE TITLE
I am currently using the Processing 3.5.3 on Windows 10 and it can't process keyPressed() function

### ISSUE THREAD

**Issue by Jataro-Kemuri** [processing/processing#5855]
## Description
The function doesn't work

## Expected Behavior
 For the function to work

## Steps to Reproduce

1. Use the function void keyPressed(){}
2.
3.

## Your Environment

 

* Processing version: 3.5.3
* Operating System and OS version: Windows 10
* Other information:

**Comment by dzaima** [comment]
Do you have any example code you expect to work, but doesn't? This issue is too broad to have anything done about it, since, for me, `keyPressed` does work.

The best I can do to help without more info is to remind that for `void keyPressed() { ... }` to function, there must be a `void draw() { ...}` anywhere in the program, otherwise key presses are not processed.

**Comment by Jataro-Kemuri** [comment]
Actually that helped. Thank you
