### ISSUE TITLE
Can't open processing-3.5.3 on window 10

### ISSUE THREAD

**Issue by leyap** [processing/processing#5870]
![20190601000329](https://user-images.githubusercontent.com/5211611/58718751-c9adfc80-8400-11e9-9b3b-219baa4daaf5.png)

**Comment by kfrajer** [comment]
@leyap  Was it working before of was this a new fresh install? 

For anybody working on this issue: 
-I am suspecting it is encoding based on SO post(below) and source of NPE
-Problematic line https://github.com/processing/processing/blob/master/app/src/processing/app/contrib/ContributionListing.java#L159
-Stack Overflow **[post](https://stackoverflow.com/questions/17472878/java-tolowercase-nullpointerexception)** suggests using `String.equals()` 
-Any suggestions to find the root cause of this issue?

**Comment by leyap** [comment]
It worked fine before, but then it didn't work anymore,  And after I reinstall it, it still doesn't work.

**Comment by leyap** [comment]
@kfrajer This happens after I installed some processing libraries. maybe one of a kinect library.

**Comment by leyap** [comment]
@kfrajer I found a similar problem, but can't help me. 
https://stackoverflow.com/questions/21870454/processing-not-launching-after-osx-update-to-10-9-1

**Comment by leyap** [comment]
Finally, I found the reason, an error occurred while parsing the contribs.txt file, causing processing to fail to startup.
