### ISSUE TITLE
GitHub actions and Apache Ant JDK 8 builds

### ISSUE THREAD

**Issue by jeremydouglass** [processing/processing#5920]
This is not a feature request -- it is an observation / suggestion.

I just saw that the GitHub Actions beta now supports a workflow "Java with Ant: Build and test a Java project with Apache Ant."

A quick glance at a sample workflow shows it support JDK 8 -- not sure if you can specify the specific version, e.g. 8u202, but it seems to fit processing dev needs pretty well, and might be worth looking at using this for build workflows / ci.

Processing would need to sign up for Actions here:

https://github.com/features/actions/signup/

**Comment by jeremydouglass** [comment]
@sampottinger I seem to recall you were also potentially interested in ci of this kind for your branch.

**Comment by sampottinger** [comment]
Hey there!

Totally. I have CI currently enabled for https://github.com/sampottinger/processing via Jenkins and CD was enabled previously (deploy to S3). To see the Travis builds go to https://travis-ci.org/sampottinger/processing/builds. For the PRs, see https://github.com/sampottinger/processing/pull/87 (without CD) and https://github.com/sampottinger/processing/pull/70 (with CD). I chose Travis because we need mac containers in order to run the code sign process.

https://github.com/features/actions/signup/ is interesting... I'll take a closer look!

**Comment by sampottinger** [comment]
Just to link this in... Relates to #5753! Thanks again @jeremydouglass

**Comment by benfry** [comment]
Fixed with https://github.com/processing/processing4/pull/1 and continued development happening at https://github.com/processing/processing4
