### ISSUE TITLE
processing Discord RPC

### ISSUE THREAD

**Issue by Shikiiii** [processing/processing#5924]
So, I searched far and wide but I didn't find it.

**Is it possible to have a Discord Rich Presence for processing?** I went around and asked some people, but from what I got to know, to have the same results as [Visual Studio Code's plugin](https://marketplace.visualstudio.com/items?itemName=icrawl.discord-vscode) for example, we'll also need a little help from the processing team. I'm not sure if that's true, that's why I'm making this. I originally wanted to make it myself, but it's not as easy as I thought, apparently.

I really wish to see this being a thing one day and I'm looking forward to it.
Have a nice day/night.

**Comment by jeremydouglass** [comment]
Neat idea -- are you suggesting this as a Tool for PDE, specifically? 

...is there already a Processing Discord server? If not, who would host it, or is the idea that the tool could help you talk about Processing on any Discord?

 Right now I believe that some of the main communities are:

-  [The official forum (discourse)](https://discourse.processing.org)
-  [Stackoverflow [processing]](https://stackoverflow.com/questions/tagged/processing)
-  [Reddit r/processing](https://www.reddit.com/r/processing/)

**Comment by Thegamesbg** [comment]
Well, now that I think about it, there isn't a discord server afaik. I could make one specially for this, but it won't be official unless the processing team agrees to it. I'd like to wait for their reply, so we know how to act. It'll be nice to get all the people that use both processing and discord.

Yes, it'll be nice to have it as a plugin (a tool).

Another option is to ask around programming servers, but I'm not sure if we can make one ourselfs, because I don't think we can grab stuff like the tabs name (for example) from processing. (Correct me if I'm wrong.)

**Comment by benfry** [comment]
Hi folks, this is a better discussion for the forum… https://discourse.processing.org

**Comment by Ectalite** [comment]
As the original demand was not complished, I wanted to know if anything was accomplished since september 2019.

**Comment by jeremydouglass** [comment]
@Ectalite -- feel free to start a topic about Discord on the processing forum, linked above. Ask or propose anything that you like there.

**Comment by Ectalite** [comment]
Ok thanks will do that then 

18 mars 2020 à 01:42 de notifications@github.com:
