### ISSUE TITLE
Processing wont start with error "Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: Could not initialize class sun.reflect.misc.MethodUtil"

### ISSUE THREAD

**Issue by watchinit** [processing/processing#5959]
Processing wont start with error "Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: Could not initialize class sun.reflect.misc.MethodUtil"

What I was expecting was for it to start. It doesn't get past the first screen.

All I do is run it.

Processing version: 3.5.3
Operating System: Windows 7
Other information: Freshly installed processing multiple times.

A possible cause is either:
My java/system is screwed up,
or I have a file related to processing that is broken that I haven't yet found.

**Comment by Bobby54** [comment]
Have you tried downloading different versions of Processing, especially older ones?
Also, try updating your java Version, as this error message appears to be connected to java.

**Comment by benfry** [comment]
I would try changing your sketchbook folder (in Preferences) to an empty folder. And see if you can run things without any trouble. I don't think we even use `MethodUtil` anywhere, so I haven't a clue where that's coming from. 

Otherwise, I'd use https://discourse.processing.org/ for any follow-up.
