### ISSUE TITLE
Export Application broken in Processing 3.5.4 when using P2D or P3D renderers

### ISSUE THREAD

**Issue by dantepfer** [processing/processing#5983]
## Description
Using the Export Application function in the new Processing 3.5.4 seems to be broken when using P2D or P3D renderers. When opening the exported application, it immediately quits and MacOS displays an alert saying that the application "quit unexpectedly". Under the exact same conditions, exporting with Processing 3.5.3 works fine.

## Steps to Reproduce
Open the Array example in Processing 3.5.4, copy to a new sketch, save it. Export Application from the file menu, then open the exported app. This works — the sketch uses the default renderer. Add P2D or P3D to the size() command and export again; the exported app fails. Do the same in Processing 3.5.3, it works.

## Your Environment
OSX Catalina 10.15.2, on a 2019 MacBook Pro 16-inch.

**Comment by wdepue** [comment]
having the same issue.
pid(727)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
2020-03-10 20:36:06.088 desertSlopetesting[727:15184] Apple AWT Internal Exception: NSWindow drag regions should only be invalidated on the Main Thread!
2020-03-10 20:36:06.089 desertSlopetesting[727:15184] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'

seems to be related to #5462

**Comment by carabthompson** [comment]
Same issue here. The app just crashes. When running the sketch from Processing, it works but gives this error (no error on PCs)

0   AppKit                              0x00007fff448ce607 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 378
	1   AppKit                              0x00007fff448cb9f7 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1479
	2   AppKit                              0x00007fff448cb42a -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
	3   libnativewindow_macosx.jnilib       0x00000001273ce3fe Java_jogamp_nativewindow_macosx_OSXUtil_CreateNSWindow0 + 398
	4   ???                                 0x000000010ffafa88 0x0 + 4563073672
)

**Comment by wdepue** [comment]
You can circumvent this error if you run only the executable in the program files of the compiled processing app for some reason.

**Comment by jcdell** [comment]
I have similar problem, the exported app crashes immediately and it doesn't go way by just running the executable inside the export folder. The app **RUNS in the Processing IDE** but with the following error msg, which seems related to the export problem since both flag the same uncaught exception.


0   AppKit                              0x00007fff3120b289 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 371
	1   AppKit                              0x00007fff311f2cb2 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416
	2   AppKit                              0x00007fff311f2723 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	3   libnativewindow_macosx.jnilib       0x0000000125b023fe Java_jogamp_nativewindow_macosx_OSXUtil_CreateNSWindow0 + 398
	4   ???                                 0x00000001152e4a88 0x0 + 4650322568
)


When I try to run generated app, it crashes with the following message:

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0:
--> 
    __TEXT                 0000000104e84000-0000000104e87000 [   12K] r-x/rwx SM=COW  /Users/USER/*/stNetwork.app/Contents/MacOS/stNetwork

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
abort() called
terminating with uncaught exception of type NSException

----------------------------------
Finally, I am using the peasyCam library , which has been excellent and worked without incident in the past.

**Comment by ZOROYANG** [comment]
Same problem with 3.5.4,  not possible to output normal executable on Mac OS if P3D is employed. What we can do about that? Mojave 10.14.6

**Comment by jcdell** [comment]
Zoroyang,
Does your code throw the same uncaught Exception: **'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!** ?? In which case I suspect an implementation bug relative to this version of MacOS. I have not been able to solve this problem.

**Comment by resistdesign** [comment]
Same problem: `Mac OS X 10.15.4 (19E287)`

**Comment by johncottenwatson** [comment]
Noticed the same behavior: <code> macOS 10.15.5 (19F101) </code>

**Comment by gregt590** [comment]
Overall P2D and P3D appears broken in MacOS Catalina 10.15.5 with Processing 3.5.4.  If you fire up the simple sketch:

void setup() {
  size(900,900,P3D);
  background(255);
  println("Starting...");
}
void draw() {
  line(mouseX, mouseY, 50, 50);
}
void mousePressed() {
  exit(); 
}

It causes the following error on the console:
![Screen Shot 2020-06-14 at 11 52 59 AM](https://user-images.githubusercontent.com/3485110/84601584-1c086280-ae36-11ea-8918-6b7c414ae7c9.png)

However if you remove the P3D (or P2D) in size() the error doesn't occur.

While draw() continues, the error has other side effects like preventing a:
`String in = JOptionPane.showInputDialog(ask, defValue);`
from running.

**Comment by Beardy241** [comment]
Same here.  
Mac OS 10.14.6
Processing 3.5.4

Major problem as I need to demo to a client!  Uh oh!

**Comment by dantepfer** [comment]
Thanks @triposorbust, good to know this isn't just a Processing issue. Hopefully there'll be a fix soon...

**Comment by benfry** [comment]
This should be working in the Processing 4.x alpha releases, which use the newer version of JOGL. Be sure to embed the Java runtime when exporting.

**Comment by benfry** [comment]
Closing this one out, since it should be resolved.

If you run into the problem posted here, try with a 4.x release: https://github.com/processing/processing4/releases

And if you have a problem with a 4.x release, file a new issue here: https://github.com/processing/processing4/issues/new
