### ISSUE TITLE
unable to open processing.org with mac OS catalina because of java error

### ISSUE THREAD

**Issue by 444lcsb** [processing/processing#6007]
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by 444lcsb** [comment]
No one has responded with a solution to this problem.

**Comment by jeremydouglass** [comment]
"because of java error" is not enough information. Please provide an error code / name / text. Please provide your processing version number. Did this happen the very first time you used processing, or did was it working and then stopped? If it runs on Catalina for me you have given nothing that would help me attempt to understand your problem.

This might also help you:

https://github.com/processing/processing/issues?q=is%3Aissue+catalina

**Comment by 444lcsb** [comment]
I just discovered it was a privacy block in the Mac OS system preferences. Seems to be OK now. Thanks for your help. I made a donation.

Leroy Fass

**Comment by jeremydouglass** [comment]
Thank you so much for following up about the resolution of your problem. If you can recall or have the exact error message, please consider adding it to your issue title before closing -- it might help others in the future.

I'm assuming you resolved it by going into system prefs and giving some permission to the app...?

**Comment by 444lcsb** [comment]
Yes, it was checking “full disk access” in the system preferences that allowed the program to load instead of seeing a long list of java errors as described by others on GitHub with one or two showing the list of java errors.
