### ISSUE TITLE
Ant build system tool not working properly for Linux 

### ISSUE THREAD

**Issue by ranaaditya** [processing/processing#6011]
## Expected Behavior
On running **ant run** command project should build successfully .

## Current Behavior
On running **ant run** command inside build folder its redirecting to some Urls but these are invalid Urls on running them in separate browser  they are showing invalid page and some need OTN license  !!

## Steps to Reproduce

1. git clone https://github.com/processing/processing.git
2. cd processing 
3. gradle build or gradle --stacktrace (if it crashes then complete logs before crashing)
4. cd build 
5. ant run (you will see the error as shown below) 

![error](https://firebasestorage.googleapis.com/v0/b/test-879af.appspot.com/o/uploads%2FScreenshot%20from%202020-03-23%2001-42-00.png?alt=media&token=9c8e7bc4-7fac-4c58-88e3-e751419901d9)

**Initally I thought that it's due to internet connectivity problem but later on its showing the same error**

## Your Environment

* Processing version: 4.0
* Operating System and OS version: Ubuntu 19.04 
* Other information: x86_64 bit processor

**Comment by bmarcos81** [comment]
Ok, the problem is not only related with Linux. I have solved the same issue for Windows.
The jre downloader have an issue because Oracle is forcing the user to register before download anything.

The solution is to register with Oracle. You can fill the form with fake data except the email. There is a verification process. Unless you have a copy of the JRE version 8u202 (tar.gz file).
https://www.oracle.com/java/technologies/javase/javase8-archive-downloads.html
Download that JRE (tar.gz) for your system and copy it to the "processing/build/<your system folder>".
IMPORTANT: Rename it to "jre-8u202.tgz". Then run again the "ant run" command.
I hope this helps.

Note for Mac users: You will need the JDK 8u51 and must edit the build.xml as stated under https://github.com/processing/processing/wiki/Build-Instructions

**Comment by ranaaditya** [comment]
Thanks a lot @bmarcos81 , your idea worked :+1:
As suggested by @bmarcos81 I registered with Oracle but still I was unable to build the project from commandline so i finally download the **jre-8u202-linux-x64.tar.gz** from official Oracle website and *copy** it to **processing/build/{my_system_folder}** and **rename** it **as jre-8u202.tgz** and  run the project using **ant run** from **processing/build** and it worked.

I am closing this issue as it is solved.

**Comment by benfry** [comment]
Now fixed as of https://github.com/processing/processing/commit/89a080814895234b54201c0240625e47a5b369cf
