### ISSUE TITLE
size() Is Illegal

### ISSUE THREAD

**Issue by Jaythe64** [processing/processing#6044]
<img width="632" alt="Screenshot 2020-05-20 at 10 16 52" src="https://user-images.githubusercontent.com/65638091/82397435-0bf1a300-9a83-11ea-9d92-926d4248a410.png">

**Comment by jeremydouglass** [comment]
Because you ignored the entire issue request for information -- your Processing version number, operating system, when this started happening, etc. -- there is little chance that anyone could guess what is going on or give you a useful reply.

For programming questions, please use the Processing forum: https://discourse.processing.org

**Comment by Bobby54** [comment]
Did you use `void setup()` and/or `size(640, 360)` in a tab named differently than the sketches name?
![image](https://user-images.githubusercontent.com/47862814/82484470-433f6e80-9ada-11ea-9d62-45c870c296dd.png)
Using `setup` in a different tab than the main tab results in a similar error(probably different because of a different Processing version):
![image](https://user-images.githubusercontent.com/47862814/82484663-87cb0a00-9ada-11ea-9457-dcc6037c4b77.png)

You can fix this error either by replacing `setup()` with `settings()` or by moving `setup()` in the main tab of your sketch.

**Comment by Jaythe64** [comment]
> Did you use `void setup()` and `size(640, 360)` in a tab named differently than the sketch?
> ![image](https://user-images.githubusercontent.com/47862814/82484470-433f6e80-9ada-11ea-9d62-45c870c296dd.png)
> Using `setup` in a different tab than the main tab results in a similar error(probably different because of a different Processing version):
> ![image](https://user-images.githubusercontent.com/47862814/82484663-87cb0a00-9ada-11ea-9457-dcc6037c4b77.png)
> 
> You can fix this error either by replacing `setup()` with `settings()` or by moving `setup()` in the main tab of your sketch.

Thank you so much! It worked!

**Comment by Jaythe64** [comment]
> Because you ignored the entire issue request for information -- your Processing version number, operating system, when this started happening, etc. -- there is little chance that anyone could guess what is going on or give you a useful reply.
> 
> For programming questions, please use the Processing forum: https://discourse.processing.org

My apologies, this is my first time on the platform.

**Comment by jeremydouglass** [comment]
> My apologies, this is my first time on the platform.

No problem -- if you run into more problems while getting started, come see us on the forum first and let us help! cheers
