### ISSUE TITLE
"expecting EOF, found 'ypos'"

### ISSUE THREAD

**Issue by JayBoom** [processing/processing#6050]
[Confused](https://cdn.discordapp.com/attachments/715098631127957566/715440943465234505/unknown.png)

Doesn't make any sense why it doesn't work. It works if you put it in a plain document but not in this and i dont understand, ypos is not used anywhere else in my code.

**Comment by dzaima** [comment]
The assignment in the second line isn't allowed outside of functions. You need to either put it in a function (e.g. `void setup()`) or wrap it in braces:
```java
int[] ypos;
{
  ypos = new int[14];
}
```

Unfortunately the error points at the wrong thing, and much can't be done about it because it's from ANTLR. (note that it points at after the line in Processing 4, which is still sub-optimal)

**Comment by jeremydouglass** [comment]
> Doesn't make any sense why it doesn't work.

** For coding questions, please use https://forum.processing.org **
** This form is only for bugs in the software & feature requests **

Always post code questions to the forum ( https://discourse.processing.org/ ) -- never here.

GitHub issues are  for bugs and feature requests only. If you aren't 100% certain that it is a bug, post to the forum first -- and maybe even then, just to check.

**Comment by JayBoom** [comment]
Its weird this code works

int[] DaysinMonths;
DaysinMonths= new int [13];

But this code doesn't 

int[] ypos;
ypos = new int[14];

I guess cause the daysinmonths doc doesnt have a setup or draw is maybe why?

**Comment by jeremydouglass** [comment]
It is not weird. That is immediate mode -- which is discussed in the introductory tutorials. **Please ask on the forum!**
