### ISSUE TITLE
where is it implemented?

### ISSUE THREAD

**Issue by molo32** [processing/processing#6071]
Does anyone tell me where these functions are implemented?

draw ()
setup ()
PImage ()
PImage (). Pixels []

All I find are references to other functions.
If these functions are only high-level java abtractions, do they tell me which java functions they use?

**Comment by clankill3r** [comment]
You can find them here:
https://github.com/processing/processing/blob/master/core/src/processing/core/PApplet.java
https://github.com/processing/processing/blob/master/core/src/processing/core/PImage.java

But the renderer also plays a big role.
Instead of reading the source, it might be good to get a debugger to work (not the one in the PDE), and step threw the code to see what is going on.

**Comment by jeremydouglass** [comment]
For questions like these, please ask on the forums rather than opening issues:

http://discourse.processing.org/
