### ISSUE TITLE
Bug when accessing color() through PApplet

### ISSUE THREAD

**Issue by Anthys** [processing/processing#6083]
## Description

When I try to call color() from a PApplet object, I get a token error.

This also happen when called from a PGraphics object.

[Here is the link to the Discourse discussion about it.](https://discourse.processing.org/t/accessing-papplet-methods-in-static/23112)

## Expected Behavior

color() should be callable and not raise a token error

## Current Behavior

It raises errors when it shouldn't.

## Steps to Reproduce

1.
```
static class myclass {
  
  static int mycolor(final PApplet p) {
    int out = p.color(0);
    return out;
  }
  
}
```

2.
```
unexpected token: int
```

## Your Environment

 

* Processing version: 3.5.4
* Operating System and OS version: Windows 10

**Comment by jeremydouglass** [comment]
This is looks like a bug in the preprocessor where "color" is matched as a the color data type rather than a method. The discourse thread gives a possibly related example:

```
PGraphics pg = createGraphics(10, 10);
pg.fill(0);
pg.color(0); // unexpected token: .
```

> // unexpected token: .

**Comment by clankill3r** [comment]
Related to:
https://github.com/processing/processing/issues/5713

This bug does not apply in processing 4.
Also, you can disable color as a primitive type in the preferences, which will fix, but now you have to use `int` instead of `color` (which is fine, but it breaks the default examples etc.).

**Comment by abhi267266** [comment]
It looks like you are encountering an issue with calling the color() function from a static method inside a nested class.

In Java, it is not possible to call non-static methods or access non-static fields from a static context. Since the color() function is not static, it cannot be called directly from inside a static method.

To work around this issue, you can create an instance of the PApplet class inside your static method and use it to call the color() function:
`
static class myclass {
  static int mycolor(final PApplet p) {
    PApplet applet = new PApplet();
    int out = applet.color(0);
    return out;
  }
}
`

**Comment by clankill3r** [comment]
The original problem had to do with the preprocessor of processing.
Since a lot of things have changed for processing 4, this bug is no longer present.
So I think therefor this issue can be closed.
