### ISSUE TITLE
nf(float,0,0) not showing expected results

### ISSUE THREAD

**Issue by joepekoe** [processing/processing#6093]
## Description
nf(float,0,0) when using a "0" for "number of digits to the right of the decimal point" should produce a whole number.

## Expected Behavior
nf() appears to follow documented behavior but I think a "0" as the third parameter should produce a whole number.

## Current Behavior
nf( float, 0, 0 ) currently returns the float as a decimal number, unchanged in any way.

## Steps to Reproduce
float f1 = 999.123;

void setup()
{
  size(800,400);
  background(0);
}

void draw()
{
    text( nf( f1, 0, 0 ), 400, 200 );
}

## Your Environment
I am developing code using Processing 3.5.4 on a Win10 PC, exporting the application to Linux, copying exported files from armv6hf to Rpi Buster on Rpi 2b hardware.

## Possible Causes / Solutions
unknown

**Comment by jeremydouglass** [comment]
In `nf(f1, 0, 0)` the argument `0` means "unformatted". This enables one to format either the left part of the float or the right while passing through the other part.

In order to strip floating point digits from a float, instead use `int(f1)`, or `(int)f1`, or `floor(f1)`. If you want to format a fixed number of left-hand digits on an float and remove right-hand digits, use `nf(int(f1), 10)`.
