### ISSUE TITLE
image() is slow

### ISSUE THREAD

**Issue by molo32** [processing/processing#6158]
I have several objects on screen each with its sprite.
to show your sprite use
`image (sprite, xpos, ypos).`
but when there are many objects on the screen it becomes slow.
I realized it is due to the use of `image ()`.

there is a way to make `image ()` faster

pc spec:
processing 3.5.4
wndows 7

**Comment by StanLepunK** [comment]
If I understand well your problem in your sketch you use a lot of images in a same loop to draw all your sprites ? If it's that case, I think it's normal there is a slow-down because if I remember each time `image()` is used all the rendering is re-render. Maybe you must find another option to draw your sprite without use `image()`.  Are-you post your problem on the forum ? https://discourse.processing.org/

**Comment by molo32** [comment]
what other way is there to display an image without using image ()?

**Comment by StanLepunK** [comment]
Maybe use `PGraphics` with a specific size of your sprite. https://processing.org/reference/createGraphics_.html I think it's better to you to ask on forum.

**Comment by benfry** [comment]
Yes, please use https://discourse.processing.org/
